### PR TITLE
[V4] Bring new APIs to avocado - avocado-vt/virt-test work

### PR DESCRIPTION
**Pull request by lmr**
In the process of merging virt-test into avocado-vt (see https://github.com/avocado-framework/avocado-vt/pull/37), we mostly dropped virt-test's autotest API calls, replacing them with equivalent avocado API calls. Of course, avocado didn't have some of the expected APIs, and that's the purpose of this Pull Request: to add the missing ones.

Updates from v3:
* Rebased against latest master using --ignore-date, so now github will display the patch order correctly.
* Removed shebangs that didn't belong to some of the new libraries
* Tidied up the `service` module.

Updates from v2:
* Rebased against latest master
* Dropped `cpu.count_cpus()` per @clebergnu's suggestion.

Updates from v1: Worked on the review points made by @ldoktor:
* Updated file headers to mention previous authors
* Renamed `modules` -> `linux_modules`
* Refactored and improved the implementation for `output.display_data_size` and `output.ProgressBar`
* Added some unittests along the way

Update from v0: There's no more `exceptions.context` API added here. We decided it was best to find a better way to do that in avocado, so virt-test's got its own implementation of the context APIs.

### CODE REVIEW

**Comment by ldoktor** [comment]
OK, I'm not aware of any problems right now, but with such complex PR you never know... @clebergnu would you please be the 2nd reviewer as this is quite a big PR?

Acked-by: Lukáš Doktor <ldoktor@redhat.com>

**Comment by clebergnu** [comment]
@ldoktor sure, I'm about to review it.

**Comment by clebergnu** [comment]
LGTM!

**Comment by clebergnu** [comment]
Merged, thanks @lmr and @ldoktor !

**Pull request merged**
