### PR TITLE
Job and test runner interface

### PR DESCRIPTION
**Pull request by clebergnu**
This defines a runner interface (which the job uses) and makes all current implementations conform to it.  Runners are now visible with `$ avocado plugins` and can be defined in jobs easily (see `examples/job/podman.py`.

### CODE REVIEW

**Comment by clebergnu** [comment]
@willianrampazzo thanks so much for the review! I'll fix the conflict while merging it.

**Comment by pevogam** [comment]
Hi @clebergnu, I wonder why the `runner` is turned into a plugin but the `loader` is not? In the most recent avocado even the `resolver` is turned into plugin leaving the classical loader behind and as far as I understand it could benefit from the same changes like the ones for the runner here.

**Comment by clebergnu** [comment]
Hi @pevogam, the idea is that the loader will be deprecated/removed in favor of the resolver.  It's true that it could still be turned into a "new style" plugin like this, but it feels like it would be too much of an effort to deprecate/remove it first.

**Comment by pevogam** [comment]
I see - in that case I assume add loaders inheriting from the base loader should think about inheriting from the resolver (type of loader) instead? The runner that was moved above also seems to be old style runner and not the next generation runner or am I missing something?

**Comment by clebergnu** [comment]
@pevogam First, let me apologize for the current state of things, they're clearly confusing.

The problem with writing a resolver plugin, instead of a loader plugin, is that right now, it'd only enable the tests found by the resolver to work with the N(ext)Runner.  I'm working on the documentation to attempt to clarify some of the confusion regarding the N(ext)Runner and Resolver, but it's an ongoing task (see #3531).

And Yes, the runner that was moved to `avocado.core.plugins.runner` is based on conventional runner that works with *loaders* only.  The current *supported* scenario when one runs `avocado run ...` is based on:

 * `avocado.core.loader`: based on an older "plugin" implementation that requires loaders to inherit from `avocado.core.loader.TestLoader`, and to register plugins using `avocado.core.loader.LoaderProxy.register_plugin`.
 * `avocado.plugins.runner`: the "conventional test runner", based on a "new style" plugin interface (the interface itself is in `avocado.core.plugin_interfaces.Runner`.

Before 6dcdb6219b0683471a9e4c5411b7f99702ef9992, `avocado.core.job` would discovers tests *only* using the loader, and would run it with an implementation of the `avocado.core.plugin_interfaces.Runner` interface.  After 6dcdb6219b0683471a9e4c5411b7f99702ef9992, a Job can resort to using the `avocado.core.resolver` code, instead of the `avocado.core.loader` *only if*, the `nrunner` implementation (introduced in ae0e3cbf27e3b4dc6773b065a6eb8a6f72597e75) is chosen.  The reason is that the runner implementation (based on `avocado.core.plugin_interfaces.Runner`) needs to know that it's dealing with a resolver output, and not a loader output.

Let me know if this answers all of your questions.

**Comment by pevogam** [comment]
Hi @clebergnu, no doubt it is complicated and I am not sure I understand everything in the explanation at least when it comes to the reason why the older runner is turned into plugin and the older loader is not but just to clarify: the final anticipated state would be to have the next generation runner + the next generation loader (here called resolver) as plugins and even the currently migrated older runner will be removed later on and not just the currently nonmigrated loader. Am I correct?

**Comment by pevogam** [comment]
On a second thought, I looked through the avocado code and it seems the (base) resolver is not a plugin following any interface as well. So it seems that this was eventually only done for runners. My suggestion in this case would be to turn loaders into proper plugins as well, similarly to the more custom loaders like YAML or the resolver-inheriting loaders. I could look into it for you if you want but it makes more sense to me as a runner-loader parity.

**Pull request merged**
