### PR TITLE
Plugin fail mechanics

### PR DESCRIPTION
**Pull request by lmr**
After discussion on plugin failures, send a couple of patches that aim to avoid confusion on users about failed to load plugins.

### CODE REVIEW

**Comment by lmr** [comment]
@clebergnu, this shouldn't change much from what we had, although this makes it clear to users that they have to take action if plugins are not working.

**Comment by clebergnu** [comment]
OK, taking a look at it.

**Comment by clebergnu** [comment]
LGTM. I resent the Python 2.6 Travis job, it looks like it hanged during a timeout test.

**Comment by clebergnu** [comment]
Merged! Thanks!

**Pull request merged**
