### PR TITLE
trivial typo: quotating => quoting

### PR DESCRIPTION
**Pull request by mallove79**

### CODE REVIEW

**Comment by willianrampazzo** [comment]
Sorry, @mallove79, if my last comment was a bit confusing. When I mentioned _sign you commit_, I meant to add the sign-off message, or Travis will complain, lek here: https://travis-ci.org/github/avocado-framework/avocado/jobs/710071280.

Feel free to sing-off your commit and push force here as this patch is straight forward.

**Comment by mallove79** [comment]
> Sorry, @mallove79, if my last comment was a bit confusing. When I mentioned _sign your commit_, I meant to add the sign-off message, or Travis will complain, like here: https://travis-ci.org/github/avocado-framework/avocado/jobs/710071280.

What is the _sign-off message_ to suppress Travis messages?

Sorry for my confusion.

**Comment by willianrampazzo** [comment]
> > Sorry, @mallove79, if my last comment was a bit confusing. When I mentioned _sign your commit_, I meant to add the sign-off message, or Travis will complain, like here: https://travis-ci.org/github/avocado-framework/avocado/jobs/710071280.
> 
> What is the _sign-off message_ to suppress Travis messages?
> 
> Sorry for my confusion.

Committing with `-s` will do the trick. Check the git workflow here: https://avocado-framework.readthedocs.io/en/80.0/guides/contributor/chapters/how.html#git-workflow

**Comment by mallove79** [comment]
> > > Sorry, @mallove79, if my last comment was a bit confusing. When I mentioned _sign your commit_, I meant to add the sign-off message, or Travis will complain, like here: https://travis-ci.org/github/avocado-framework/avocado/jobs/710071280.
> > 
> > 
> > What is the _sign-off message_ to suppress Travis messages?
> > Sorry for my confusion.
> 
> Committing with `-s` will do the trick. Check the git workflow here: https://avocado-framework.readthedocs.io/en/80.0/guides/contributor/chapters/how.html#git-workflow

Ah, so lowercase `-s`, not uppercase `-S`.  Lower-case `-s` appended the _signed-off_ comment to the commit message.

https://github.com/avocado-framework/avocado/pull/4011

Is it okay now?

**Comment by PraveenPenguin** [comment]
closing this in favour of #4011

**Pull request closed without merging**
