### PR TITLE
Added disk library utility

### PR DESCRIPTION
**Pull request by PraveenPenguin**
1-Added error catching utility in avocado/utils/disk 
2-added a utility which return dictionary having  all partition info
of given partition
3-added a utility which return True and flase if
disk partiton has linux file system or not

Signed-off-by: Praveen K Pandey <praveen@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by PraveenPenguin** [comment]
@clebergnu @ldoktor can you please help me on travis failure as in my local is always passes

```
[praveen@localhost avocado]$ inspekt style --exclude=.git --disable E501,E265,W601,E402,E722
PEP8 disabled: E501,E265,W601,E402,E722
PEP8 compliance check PASS
[praveen@localhost avocado]$ 
````

**Comment by PraveenPenguin** [comment]
@clebergnu can you please help me here

**Comment by richtja** [comment]
Hi @PraveenPenguin, the problem is that Travis checks each commit of PR separately. 

Travis mesage for commit 43ea7377e13f3e1f68d9650098b1305cbd5c52fe :
`/home/travis/build/avocado-framework/avocado/avocado/utils/disk.py:37:1: E302 expected 2 blank lines, found 1
Python library autopep8 not installed. Please install it if you want to use --fix
Style: /home/travis/build/avocado-framework/avocado/avocado/utils/disk.py FAIL (FIX NOT OK)
PEP8 compliance FAIL
style FAILED`

Travis mesage for commit 9ac1fbbb3fb34daa28c49c6e80e57baf93c2db48:
`/home/travis/build/avocado-framework/avocado/avocado/utils/disk.py:125:27: W605 invalid escape sequence '\s'
Python library autopep8 not installed. Please install it if you want to use --fix
Style: /home/travis/build/avocado-framework/avocado/avocado/utils/disk.py FAIL (FIX NOT OK)
PEP8 compliance FAIL`

You have to fix all commits and then it will work.

**Comment by PraveenPenguin** [comment]
@richtja thanks a lot of help , will do change and push the code

**Comment by PraveenPenguin** [comment]
closing in favour off #3102

**Pull request closed without merging**
