### PR TITLE
avocado: Refactor logging initialization

### PR DESCRIPTION
**Pull request by ldoktor**
Hello guys,

this complex PR is a first step to refactor the logging. What it does is it changes the initialization of logging to by design avoid problems with --silent not ready during parser initialization.

The missing pieces are:

1. merge "log.py" and "output.py" as they serve the same purpose and are interconnected a lot
2. remove the concept of "View". Instead during "reconfigure" (when paginator==on) replace the stdout/stderr/enabled_logs with handler, which outputs in paginator. This again by design merge all outputs into paginator (avoids the problem where paginator overrode traceback logging streams) and also as there will be a single place to initialize, and cleanup the paginator it should make it easier to ensure cleanup is called. The "View().minor()" and similar calls should become simply "logging.getLogger(...).debug()".
3. review the "standalone", "show-job-log" and "silent" args and remove unnecessary handling (some handling is still needed until (2) is done)

### CODE REVIEW

**Comment by lmr** [comment]
Interesting, 3 failures with python 2.6. without actually researching the issue, I suspect of the log config shennanigans in `avocado.core.log.configure()`

**Comment by ldoktor** [comment]
Hi Lucas, thanks, I saw it passed on 2.7 and now I see it failed on 2.6. I'll take care of it. The only problem is in standalone, which is handled a bit differently, so something is probably different on 2.6 logging.

**Comment by ldoktor** [comment]
@lmr The problem was really simple. See the 6ebc305 ...

**Comment by lmr** [comment]
There are a few notes I made, but I like where this is going. Sorry I couldn't give a more thorough review.

**Comment by ldoktor** [comment]
Thanks for your review. I'm unhappy with the status, I really wanted to get rid of the paginator in this version, but the `stdout` and other custom hangings were quite painful to solve. It'll be simpler when we get rid of the paginator (well replace it with global paginator instead) but I could not deliver it on time... anyway I played with it and it should be possible :smile:

**Pull request closed without merging**
