### PR TITLE
avocado.utils.process: Avoid fd_drainer hang

### PR DESCRIPTION
**Pull request by ldoktor**
For some workloads on some python versions the `os.read` on subproces's
stderr descriptor does not return '' when the process is finished, but
it hangs for infinity. This was never spotted on stdout so it might be
actually a python issue.

This patch avoids such issue by using select and reading only when there
are data available. In most cases this should not be necessary, but
let's have this safety as this problem comes from real world
application:

    https://github.com/avocado-framework/avocado-misc-tests/issues/133

Signed-off-by: Lukáš Doktor <ldoktor@redhat.com>

### CODE REVIEW

**Comment by apahim** [comment]
Let's wait for the verify on https://github.com/avocado-framework/avocado-misc-tests/issues/133#issuecomment-251934993

**Comment by ldoktor** [comment]
@PraveenPenguin the failure is because by default `process` raises exception on non-zero exit status. You can disable and treat the failure manually by setting `ignore_status=True` in `build.make`.

**Comment by PraveenPenguin** [comment]
@ldoktor thanks as i mentioned earlier command not hanged , issue with make (Test itself) will fix . 

Log:

[stdout] FAIL: rt/tst-mqueue8x
[stdout] FAIL: rt/tst-shm-cancel
[stdout] UNSUPPORTED: stdlib/tst-quick_exit
[stdout] UNSUPPORTED: stdlib/tst-thread-quick_exit
[stdout] Summary of test results:
[stdout]     107 FAIL
[stdout]    2399 PASS
[stdout]      15 UNSUPPORTED
[stdout]      42 XFAIL
[stdout]       2 XPASS
[stderr] make[1]: *** [tests] Error 1
[stdout] Makefile:353: recipe for target 'tests' failed
[stdout] make[1]: Leaving directory '/var/tmp/avocado_77yUG_/1-glibc.py_glibc.test/src'
[stderr] make: *** [check] Error 2
Command 'make check' finished with 2 after 1189.76393199s
[stdout] Makefile:9: recipe for target 'check' failed

Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado_framework-41.0-py2.7.egg/avocado/core/test.py:451
Traceback (most recent call last):

**Comment by ldoktor** [comment]
The problem is I don't have a simple reproducer. I tried to find a way to make our process.run fail in the same way, but I really can't. I tried several basic scripts, finished writing simple c-writer, but it all works well:

```c
#include <stdio.h>
#include <pthread.h>
#include <unistd.h>

void *threadFunc(void *arg) {
    FILE *out = fopen("/dev/stdout", "w");
    FILE *err = fopen("/dev/stderr", "w");
    fprintf(out, "direct stdout\n");
    fprintf(err, "direct stderr\n");
    for (int i=0; i<10000; ++i) {
        write(1, "first\n", 6);
        write(2, "second\n", 7);
        printf("Stdout\nafdfsadf");
        fprintf(stderr, "stderr\ndfsdfdsaf");
        fsync(1);
        //fsync(2);
    }
    fclose(out);
    fclose(err);
    return NULL;
}



int main(void) {
    pthread_t pth[8];
    for (int i=0; i<8; ++i) {
        pthread_create(&pth[i], NULL, threadFunc, "processing...");
    }
    for (int i=0; i<8; ++i) {
        //pthread_cancel(pth[i]);
        pthread_join(pth[i], NULL);
    }
    return 0;
}
```

I'm not sure how ti introduce this bug. Basically if you try to `make check` glibc it acts weirdly under our project, but works well in pure python? I don't see anyone looking into it...

**Comment by ldoktor** [comment]
Although I don't know how the `make check` produces the `libgcc_s.so.1 must be installed for pthread_cancel to work` error message, because it always goes to the output, even when `&>/dev/null` is used. Do you know how to magically do this?

**Comment by ldoktor** [comment]
Oh, now I remember, it uses the `/dev/tty` to write to the underlying tty... I'll try several variants of that, but first attempts using that did not hang.

**Comment by apahim** [comment]
Ok, so just let me know if it's going to end up in a bug report against python. If not, I merge it as it is now.

**Comment by ldoktor** [comment]
@apahim http://bugs.python.org/issue23213 looks related. I noticed there are `ld-linux-x86-64` processes existing after killing the python process, which means the `make check` spawns them as daemons and they keep the stderr opened causing python to wait until they are closed. With our fix we only wait till the main process finishes.

**Comment by ldoktor** [comment]
So the question is whether we should actually do this. Probably we should not treat this and the python test should run the process in background and kill it when the main process finishes, because this way we are not waiting till the forked processes of the `make check` finish, which can be even worse when one actually wants this behavior (eg. one double forks the program, keeps the stdout and wants the output of this program to go to the process.run output. This would be not available in our version. I'll need to play with this first, though...)

**Comment by ldoktor** [comment]
yep, don't merge this, it allows missing output

**Comment by ldoktor** [comment]
Imagine code like this:

```c
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/wait.h>

int main()
{
    pid_t p1 = fork();

    if (p1 != 0)
    {
        printf("p1 process id is %d", getpid());
        int status;
        waitpid(p1, &status, WUNTRACED | WCONTINUED);
        system("ps");
    }
    else
    {
        pid_t p2 = fork();
        int pid = getpid();

        if (p2 != 0)
        {
            printf("p2 process id is %d", pid);
        }
        else
        {
            sleep(5);
            printf("p3 process id is %d", pid);
        }

        exit(0);
    }
}
```

When executed from a shell it prints the output of the first child, then the output of the main and finishes. One can then use terminal at free will, but in 5s a new output from the 2nd child arrives and it exits.

Now let's execute this from inside avocado.utils.process. It behaves correctly, which means it stores the output of the 1st child, the parent and waits in read until the 2nd child closes the stdout/err, which means it includes it's output and then it finishes.

With this PR, avocado detects that the main process finished and closes the stdout/stderr handlers and returns, which means that the 2nd child output won't make it into the process output and the daemon would keep running even after avocado finishes.

So to enclose the issue, the `make check` does not behaves nicely and it spawns several processes, that are not finished. Avocado behaves correctly and waits for them to finish. We could either persuade `glibc` guys to fix this issue or we could workaround this by running the process in background and wait for it's pid to finish. Then we'd kill all related processes (or force-closed the stdout/err pipes) and get the report from the process.

Uff, now I'm happy as I have a simple reproducer :smile: Thank you, Amador, for forcing me into this.

**Comment by ldoktor** [comment]
@santhosh93 do you need help with the workaround, or is this information sufficient? Also would you please try communicate this with the `glibc` guys? Basically the problem is, that when you run:

```
[medic@w541 ~ ]$ ps
  PID TTY          TIME CMD
11424 pts/30   00:00:00 bash
30814 pts/31   00:00:00 ps

[medic@w541 aaa ]$ make check -j 8
...
FAIL: rt/tst-shm-cancel
UNSUPPORTED: stdlib/tst-quick_exit
UNSUPPORTED: stdlib/tst-thread-quick_exit
Summary of test results:
    109 FAIL
   2443 PASS
     20 UNSUPPORTED
     40 XFAIL
      4 XPASS
Makefile:353: návod pro cíl „tests“ selhal
make[1]: *** [tests] Chyba 1
make[1]: Opouští se adresář „/tmp/glibc“
Makefile:9: návod pro cíl „check“ selhal
make: *** [check] Chyba 2
[medic@w541 aaa 2]$ ps
  PID TTY          TIME CMD
11424 pts/30   00:00:00 bash
16140 pts/30   00:00:00 ld-linux-x86-64
17993 pts/30   00:00:00 ld-linux-x86-64
30620 pts/30   00:00:00 ps
```
you can see that it leaves 2 ld-linux-x86-64 processes behind, which means avocado should wait for them to finish, so the glibc guys should properly close them....

**Comment by ldoktor** [comment]
Btw another possible solution would be to say this is frequent behavior and we can support `process.run(..., ignore_bg_processes=True)` to use this implementation as it might be useful. @apahim any ideas?

**Comment by apahim** [comment]
@ldoktor, great work here. Thank you for that. I read everything carefully and in my understanding we should add your code as an option, like you suggested with `process.run(..., ignore_bg_processes=True)`, since we are currently behaving correctly. Having it as an option, defaults to `False`, makes the follow-up with glibc guys optional, although desirable.

**Comment by ldoktor** [comment]
OK, thanks, I'll send a v2 (btw yes, default is of course `False` as it's really an ugly workaround, which allows keeping processes in background even after the test finishes)

**Pull request closed without merging**
