### PR TITLE
Plugins Overhaul [v1]

### PR DESCRIPTION
**Pull request by clebergnu**
OK guys, now this is for real!

This is a completely functional rewrite of Avocado's plugin mechanism and paradigm. As most of you know by now, it's based on stevedore[1], so we're dropping our custom module/plugin code.

Please help out reviewing the code, and probably even more important at this stage, by running Avocado on different scenarios.

Thanks!

---

Changes from v0:
 * Avocado command line app shows the errors that may result from loading plugins
 * The configuration file may be used to silence plugin loading errors
 * Documentation has been updated to match the new plugin architecture
 * Support for Avocado-VT (https://github.com/avocado-framework/avocado-vt/pull/303) and Avocado-Virt (https://github.com/avocado-framework/avocado-virt/pull/72 and https://github.com/avocado-framework/avocado-virt-tests/pull/18) are now available 

---

[1] - http://docs.openstack.org/developer/stevedore

### CODE REVIEW

**Comment by clebergnu** [comment]
@lmr since you reviewed the last version, I want to let you know that the additional work landed as the last 4 commits. No need to go over the previous ones! Thanks!

**Comment by lmr** [comment]
OK @clebergnu, I'm going to take a look at this and test it

**Comment by lmr** [comment]
OK @clebergnu, from the testing I've made here, this one is looking good. If you want me to do the honors, I can merge this.

**Comment by lmr** [comment]
@clebergnu, merged, thank you so much for this!

**Pull request merged**
