### PR TITLE
Utils multipath.py file is update with new definition "get_mpath_paths_status

### PR DESCRIPTION
**Pull request by maramsmurthy**
This definition accepts wwid/mpathx and returns state of all the paths of the particulat wwid/mpathx in a dictionary

### CODE REVIEW

**Review by abdhaleegit — CHANGES_REQUESTED** [review]
@maramsmurthy lets avoid some code by reusing the existing methods .. meaning

get all paths via get_multipath_details()
and than for loop over all path and reuse get_path_status(disk_path)  to get path status for all paths.

So  lets not duplicate path status check code here .. just reuse old method

**Comment by abdhaleegit** [comment]
@Naresh-ibm Please review this

**Comment by Naresh-ibm** [comment]
@maramsmurthy can you please attach the reference logs for this function?

**Comment by maramsmurthy** [comment]
> get_path_status(disk_path)

Hi @abdhaleegit ,

Run times increases if we make use of definition "get_path_status(disk_path)". Because in this case we don't know exactly what are all the disk paths, We will get to know only when we iterate through dictionary. Change will look like as follows if we intend to change

    for maps in mpath_op["maps"]:
        if maps["name"] == wwid or maps["uuid"] == wwid:
            for path_groups in maps["path_groups"]:
                for paths in path_groups["paths"]:
                    wwid_paths[paths["dev"]] = get_path_status(paths["dev"])

Dictionary will iterate once again if we call definition get_path_status(paths["dev"]). Re-iterations of entire dictionary happens for every disk identified. Obviously it increases execution time. 

Let me know your thoughts.

**Comment by maramsmurthy** [comment]
@Naresh-ibm 
Reference output for the added definition
2023-05-30 11:12:55,291 avocado.test INFO | mpathk paths state is
2023-05-30 11:12:55,291 avocado.test INFO | {'sdh': ('active', 'running', 'ready'), 'sdt': ('active', 'running', 'ready'), 'sdn': ('active', 'running', 'ready'), 'sdz': ('active', 'running', 'ready')}

**Review by Naresh-ibm — APPROVED** [review]
LGTM

**Review by abdhaleegit — APPROVED** [review]
LGTM

**Review by PraveenPenguin — APPROVED** [review]

**Pull request merged**
