### PR TITLE
Add deprecation warning messages to "string boolean" args

### PR DESCRIPTION
**Pull request by beraldoleal**
This is part of a big effort to convert all "string boolean" args to real boolean. Please check BP001 for details.

### CODE REVIEW

**Comment by pevogam** [comment]
Hi @beraldoleal, I thought all arguments are fully converted and BP0001 fully implemented by now. If not is there a list where the still unconverted arguments are tracked?

**Comment by beraldoleal** [comment]
> Hi @beraldoleal, I thought all arguments are fully converted and BP0001 fully implemented by now. If not is there a list where the still unconverted arguments are tracked?

I was tracking on a personal list, and afaict, those are the left ones.

**Review by pevogam — APPROVED** [review]

**Review by richtja — APPROVED** [review]
LGTM

**Review by willianrampazzo — COMMENTED** [review]
Isn't it better to collapse all commits and avoid failures as the unit test fix is applied in the end?

**Comment by beraldoleal** [comment]
> Isn't it better to collapse all commits and avoid failures as the unit test fix is applied in the end?
The unit test fix is applied at the begin. I prefer to have commits separeted in this case to avoid a big change.

**Comment by willianrampazzo** [comment]
> > Isn't it better to collapse all commits and avoid failures as the unit test fix is applied in the end?
> 
> The unit test fix is applied at the begin. I prefer to have commits separeted in this case to avoid a big change.

Okay, I misread the order.

**Review by willianrampazzo — APPROVED** [review]

**Pull request merged**
