### PR TITLE
avocado.pugins.replay record/replay loader options [v4]

### PR DESCRIPTION
**Pull request by apahim**
v4:
 - Test with external runner in original job.
 - Use json module (instead of ast) to load job result.

v3: #1069 
 - Rebased to use the new logging.

v2: #1056 
 - Whitelist with args options to replay.
 - external-runner-chdir defaults to None.

v1: #1046 
 - Record the loader options and reload them on job replay.

### CODE REVIEW

**Comment by clebergnu** [comment]
@apahim the errors on CI on 2.6 seems legit. One can work around them with:

```
diff --git a/selftests/functional/test_replay.py b/selftests/functional/test_replay.py
index a6c5f74..f608da4 100644
--- a/selftests/functional/test_replay.py
+++ b/selftests/functional/test_replay.py
@@ -42,6 +42,7 @@ class ReplayTests(unittest.TestCase):
 
     def run_and_check(self, cmd_line, expected_rc):
         os.chdir(basedir)
+        import codecs; cmd_line = codecs.encode(cmd_line, 'utf-8')
         result = process.run(cmd_line, ignore_status=True)
         self.assertEqual(result.exit_status, expected_rc,
                          "Command %s did not return rc "
```

But the real question is why `cmd_line` seems to include NULL bytes. It looks like the addition of the script path is the culprit. I'll take a deeper look into that.

**Comment by apahim** [comment]
Yes, seems like a bug in python26. Thank you @clebergnu.

**Comment by apahim** [comment]
Ok, the only way I was able to go around the issue in python26 was by keeping the curent jobid and results dir probe (instead of use json result to do so).

**Comment by ldoktor** [comment]
Hello @apahim, it looks quite good, just a few nitpicks and one issue regarding overriding the values.

**Pull request closed without merging**
