### PR TITLE
Fix connection-refused race condition when spawning tasks

### PR DESCRIPTION
**Pull request by pevogam**
Signed-off-by: Plamen Dimitrov <plamen.dimitrov@intra2net.com>

### CODE REVIEW

**Review by beraldoleal — APPROVED** [review]
I tried using timeout argument for the create_connection() but it will not solve the problem, so I'm ok with that.

**Comment by pevogam** [comment]
> I tried using timeout argument for the create_connection() but it will not solve the problem, so I'm ok with that. There is only one GH action failing.

Yes, the failing action is about logging which I commented to ask for your opinion first. Should we at least log the error? Or just a `pass` is enough in your opinion?

**Comment by beraldoleal** [comment]
> > I tried using timeout argument for the create_connection() but it will not solve the problem, so I'm ok with that. There is only one GH action failing.
> 
> Yes, the failing action is about logging which I commented to ask for your opinion first. Should we at least log the error? Or just a `pass` is enough in your opinion?

I think we could log there at least with a LOG.debug(), or LOG.warning()

**Comment by pevogam** [comment]
Alright, adapted accordingly to your suggestion.

**Pull request merged**
