### PR TITLE
 Added utility in disk library

### PR DESCRIPTION
**Pull request by PraveenPenguin**
1-
utility which return all supported filesystem
on running kernel

after patch

[GCC 5.3.1 20160406 (Red Hat 5.3.1-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from avocado.utils import disk
>>> disk.filesystems()
['sysfs', 'rootfs', 'ramfs', 'bdev', 'proc', 'cpuset', 'cgroup', 'cgroup2', 'tmpfs', 'devtmpfs', 'configfs', 'debugfs', 'tracefs', 'securityfs', 'sockfs', 'bpf', 'pipefs', 'hugetlbfs', 'devpts', 'ext3', 'ext2', 'ext4', 'autofs', 'pstore', 'mqueue', 'selinuxfs', 'binfmt_misc', 'rpc_pipefs', 'nfsd']
>>>

2-
utility which return root file system

[GCC 5.3.1 20160406 (Red Hat 5.3.1-6)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from avocado.utils import disk
>>> disk.get_rootfilesystem()
'ext4'
>>>

Signed-off-by: Praveen K Pandey <praveen@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by cacarrara** [comment]
@PraveenPenguin seems that you need to take a look on CI failures here. Most of the checks can be run locally with `make check`.

**Comment by PraveenPenguin** [comment]
@cacarrara thanks for looking this PR , will take care

**Comment by cacarrara** [comment]
Since this is a valuable contribution but hadn't updates for some time, I'm closing it but continuing with the changes and request adjustments in a new PR (#2962) giving the proper credit for the initial contributor. Thanks Praveen.

**Comment by PraveenPenguin** [comment]
@cacarrara thanks a lot , i miss this PR as due to some other prio work

**Pull request closed without merging**
