### PR TITLE
Massive spelling correction

### PR DESCRIPTION
**Pull request by apahim**
Signed-off-by: Amador Pahim <apahim@redhat.com>

### CODE REVIEW

**Comment by ldoktor** [comment]
Nice, I bet I'm responsible for most of them. Anyway I went through them and they look fine. I guess you used a spell checker for it, right?

**Comment by apahim** [comment]
@ldoktor yep: `pylint -E --disable=all --enable=spelling --spelling-dict=en_US *`

**Comment by ldoktor** [comment]
Nice and thanks. We should add this to our CI check :smile: (and to avocado-vt which contains unfixable amount of typos)

**Comment by apahim** [comment]
Yes, I am creating the dictionary white-list file so I can send a PR for that.

**Pull request merged**
