### PR TITLE
avocado.spec: add python-lxml to build dependencies

### PR DESCRIPTION
**Pull request by clebergnu**
Commit 8dad284 introduced a requirement on python-lxml. Let's reflect
that on the SPEC file.

Signed-off-by: Cleber Rosa <crosa@redhat.com>

### CODE REVIEW

**Comment by ldoktor** [comment]
Oh, my fault as I was reviewing it. Would you please also update the `debian/control` file?

**Comment by apahim** [comment]
My fault actually. Thank you for this.

**Comment by clebergnu** [comment]
@ldoktor `debian/control` is, AFAICT, really outdated. I think it deserves a task of its own...

**Comment by clebergnu** [comment]
The Debian "task of its own": https://trello.com/c/9YCukK4g/658-update-debian-packages

**Comment by ldoktor** [comment]
OK

**Pull request merged**
