### PR TITLE
libexec: Move libexec to package_files

### PR DESCRIPTION
**Pull request by ldoktor**
With the recent changes the "libexec" dir is only available when
installed via RPM. In order to have "libexec" files available
as standard package we have to include it in  the package_files
dir (avocado/). The benefit is that we can actually use package
resources to get the location in "avocado exec-path" command.

For packaging purposes let's simply symlink $libexec/avocado to the
packaged $avocado/libexec location so there is the usual location, but
keep using the python-location by default.

Signed-off-by: Lukáš Doktor <ldoktor@redhat.com>

### CODE REVIEW

**Comment by ldoktor** [comment]
Hello @clebergnu @apahim I really need your help here. I found out (the hard way, CI is all red) that when Avocado is installed by `make install` it does not come with the `libexec` scripts. I tried to address it here, but in order to keep the `/usr/libexec/avocado` location (as usual to users) I need to modify the `spec` file and the way I tried does not work.

**Comment by clebergnu** [comment]
What do you mean by "CI is all red"? I see the pending PRs with green check
marks.

**Comment by ldoktor** [comment]
My CI, not Avocado CI.

**Comment by ldoktor** [comment]
OK, stupid me, instead of printing the result I was returning it (therefor making Avocado to fail with output in stderr). It should work now, tested by `make link` and `make install` and reviewed the built `rpm` packages, which looked good. To be checked is `virtualenv` and functional check on `rpm`.

**Pull request merged**
