### PR TITLE
utils.asset: Getting FileLock before downloading

### LINKED ISSUE #4640: utils/vmimage: get() when in parallel, sometimes returns a "Permission denied" error
When using `avocado.utils.vmimage.get` method and passing a wrong checksum, test state is ERROR but debug.log message doesn't help to figure out why. For instance:

```python
class TransientDomain(Test):
    def setUp(self):
        super().setUp()
        self.image = vmimage.get(name='fedora',
                                 version='33',
                                 cache_dir='/tmp/libvirt-scratch',
                                 checksum='67daa956d8c82ef799f8b0a191c1753c9bda3bca2')
```

(I have added a "2" at the end of checksum to force this error)

debug.log (for one specific test):
```
 13:55:34 INFO | INIT 1-TransientDomain.test_convert_transient_to_persistent
13:55:34 DEBUG| PARAMS (key=timeout, path=*, default=None) => None
13:55:34 DEBUG| Test metadata:
13:55:34 DEBUG|   filename: /home/local/src/beraldo/libvirt/tests/beraldo/tests/domain/test_transient.py
13:55:34 DEBUG|   teststmpdir: /var/tmp/avocado_bvytpc03
13:55:34 DEBUG|   workdir: /var/tmp/tmpre6s_9_h/test-results/tmp_dir1k5zauxr/1-TransientDomain.test_convert_transient_to_persistent
13:55:34 INFO | START 1-TransientDomain.test_convert_transient_to_persistent
13:55:34 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
13:55:35 INFO | Asset not in cache, fetching it.
13:55:35 INFO | Fetching https://dl.fedoraproject.org/pub/fedora/linux/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-33-1.2.x86_64.qcow2 -> /tmp/libvirt-scratch/by_location/67e23165d25d7f9934a909a12bc14277c9fb0b0d/Fedora-Cloud-Base-33-1.2.x86_64.qcow2.6dlgj4_s
13:56:45 ERROR| PermissionError: [Errno 13] Permission denied: '/tmp/libvirt-scratch/by_location/67e23165d25d7f9934a909a12bc14277c9fb0b0d/Fedora-Cloud-Base-33-1.2.x86_64.qcow2'
13:56:45 ERROR| 
13:56:45 ERROR| Reproduced traceback from: /home/local/src/beraldo/avocado/avocado/core/test.py:770
13:56:45 ERROR| Traceback (most recent call last):
13:56:45 ERROR|   File "/home/local/src/beraldo/libvirt/tests/beraldo/tests/domain/test_transient.py", line 70, in test_convert_transient_to_persistent
13:56:45 ERROR|     domain = self.create_domain(arguments={'image': self.image.path},
13:56:45 ERROR|   File "/home/local/src/beraldo/avocado/avocado/utils/vmimage.py", line 446, in path
13:56:45 ERROR|     return self._path or self.get()
13:56:45 ERROR|   File "/home/local/src/beraldo/avocado/avocado/utils/vmimage.py", line 481, in get
13:56:45 ERROR|     self.download()
13:56:45 ERROR|   File "/home/local/src/beraldo/avocado/avocado/utils/vmimage.py", line 472, in download
13:56:45 ERROR|     metadata=metadata).fetch()
13:56:45 ERROR|   File "/home/local/src/beraldo/avocado/avocado/utils/asset.py", line 381, in fetch
13:56:45 ERROR|     raise OSError("Failed to fetch %s (%s)." % (self.asset_name, error))
13:56:45 ERROR| OSError: Failed to fetch Fedora-Cloud-Base-33-1.2.x86_64.qcow2 ([Errno 13] Permission denied: '/tmp/libvirt-scratch/by_location/67e23165d25d7f9934a909a12bc14277c9fb0b0d/Fedora-Cloud-Base-33-1.2.x86_64.qcow2').
13:56:45 ERROR| 
13:56:45 DEBUG| Local variables:
13:56:45 DEBUG|  -> self <class 'test_transient.TransientDomain'>: 1-TransientDomain.test_convert_transient_to_persistent
13:56:45 ERROR| Traceback (most recent call last):

13:56:45 ERROR|   File "/home/local/src/beraldo/avocado/avocado/core/test.py", line 858, in _run_avocado
    raise test_exception

13:56:45 ERROR|   File "/home/local/src/beraldo/avocado/avocado/core/test.py", line 765, in _run_avocado
    testMethod()

13:56:45 ERROR|   File "/home/local/src/beraldo/libvirt/tests/beraldo/tests/domain/test_transient.py", line 70, in test_convert_transient_to_persistent
    domain = self.create_domain(arguments={'image': self.image.path},

13:56:45 ERROR|   File "/home/local/src/beraldo/avocado/avocado/utils/vmimage.py", line 446, in path
    return self._path or self.get()

13:56:45 ERROR|   File "/home/local/src/beraldo/avocado/avocado/utils/vmimage.py", line 481, in get
    self.download()

13:56:45 ERROR|   File "/home/local/src/beraldo/avocado/avocado/utils/vmimage.py", line 472, in download
    metadata=metadata).fetch()

13:56:45 ERROR|   File "/home/local/src/beraldo/avocado/avocado/utils/asset.py", line 381, in fetch
    raise OSError("Failed to fetch %s (%s)." % (self.asset_name, error))

13:56:45 ERROR| OSError: Failed to fetch Fedora-Cloud-Base-33-1.2.x86_64.qcow2 ([Errno 13] Permission denied: '/tmp/libvirt-scratch/by_location/67e23165d25d7f9934a909a12bc14277c9fb0b0d/Fedora-Cloud-Base-33-1.2.x86_64.qcow2').

13:56:45 ERROR| ERROR 1-TransientDomain.test_convert_transient_to_persistent -> OSError: Failed to fetch Fedora-Cloud-Base-33-1.2.x86_64.qcow2 ([Errno 13] Permission denied: '/tmp/libvirt-scratch/by_location/67e23165d25d7f9934a909a12bc14277c9fb0b0d/Fedora-Cloud-Base-33-1.2.x86_64.qcow2').
```

IMO, this makes harder to find the issue, since PermissionDenied could be replaced by a proper avocado exception saying that CHECKSUM is not matching.

### LINKED ISSUE #4645: vmimage.get(): Multiple downloads in parallel of the same image are unecessary
If we have multiple tests in parallel that are using the same image, with `vmimage.get()`, this utility will try to download multiple files as shown bellow:

```
# ls -lh 
total 501M
-rw-r--r--. 1 root root 224M Jun  2 15:13 Fedora-Cloud-Base-33-1.2.x86_64.qcow2.6jfyohm4
-rw-r--r--. 1 root root 142M Jun  2 15:13 Fedora-Cloud-Base-33-1.2.x86_64.qcow2.j8e8j5vd
-rw-r--r--. 1 root root 136M Jun  2 15:13 Fedora-Cloud-Base-33-1.2.x86_64.qcow2.zcmg2zc9
```

After the downloads has finished we end up with only one image, but there is no need to download from all threads when they are the same image.

### PR DESCRIPTION
**Pull request by beraldoleal**
When multiple process are downloading the same asset in parallel we have
unnecessary downloads that could be avoided. This attempts to fix that.
Also since that we are getting the lock earlier lets remove the private
call to tempfile._get_candidate_names() and make things simple here.
Fixes #4645, Fixes #4640

Signed-off-by: Beraldo Leal <bleal@redhat.com>

### CODE REVIEW

**Review by ana — APPROVED** [review]
I didn't test it, but it looks good to me.
There is a small typo in the first commit "standandard".

**Review by clebergnu — CHANGES_REQUESTED** [review]
Hi @beraldoleal,

I've tested the overall change, and it works.  But, it's not necessary, nor advisable to change the temporary name of the file, from a random one to a predictable one.  It's not necessary because the lock will be acquired for a resource that does *not* include the temporary suffix.  And it's not advisable because non random temporary files and security issues go hand in hand.

**Comment by beraldoleal** [comment]
> advisable

@clebergnu, before I change this, I was trying to think about possible implications and I failed, can you think of a specific case where this will be a problem? Also, should we download >=2 files on the same directory, with the same name at same time, that justifies a random suffix?

The only think that I can think of is a download being interrupted and started again. This could be fixed by removing the temp file before downloading. 

IMO, using a private method of a library is a different problem, but also not advisable.

About the need, I thought about running the `url_download()` directly with  the `asset_path`, however, I remember seeing some methods that when getting an asset, only checks if the file is there (when the hash is not informed), so to avoid returning a partial file, I choose to keep the `temp` to avoid that.

**Comment by clebergnu** [comment]
> > advisable
> 
> @clebergnu, before I change this, I was trying to think about possible implications and I failed, can you think of a specific case where this will be a problem? Also, should we download >=2 files on the same directory, with the same name at same time, that justifies a random suffix?
> 

I could spend some more time and *try* to write a "proof" that this would cause a problem... up to this point I'm only operating on "known good practices".  About your question to download more than one file at once, that was probably very common case before the breakdown of "by_name" and "by_location" directory.  Another thing that I observed is that the "base url" is used for the location directory (which doesn't take into account, for instance the "GET" parameters), example: 

```
from avocado.utils import asset

print(asset.Asset('http://foo.bar/baz?some=option')._get_relative_dir())
by_location/0d6fb577802e8a8f023ab678bca108c29b3982c6

print(asset.Asset('http://foo.bar/baz?other=option')._get_relative_dir())
by_location/0d6fb577802e8a8f023ab678bca108c29b3982c6
```

That may be a problem in itself, but it hints at the possibility of two "different" assets sharing the same directory.  Again, take these with a grain of salt, because I'm operating in a  "best practices mode" and "possibly worse case scenarios".

> The only think that I can think of is a download being interrupted and started again. This could be fixed by removing the temp file before downloading.
> 
> IMO, using a private method of a library is a different problem, but also not advisable.
> 

There's no deny to that, and should be improved indeed.

> About the need, I thought about running the `url_download()` directly with the `asset_path`, however, I remember seeing some methods that when getting an asset, only checks if the file is there (when the hash is not informed), so to avoid returning a partial file, I choose to keep the `temp` to avoid that.

In my experience, a move/rename is a powerful tool to avoid corrupt, outdated or stale files, because they are atomic.  If you decide to write to the final file, it's very easy to have *"things"* happening to them because of their long presence in that writing state.

**Comment by beraldoleal** [comment]
@clebergnu I just force-pushed replacing the fixed string with a uuid4() call. Let me know if that is fine.

**Comment by willianrampazzo** [comment]
> @clebergnu I just force-pushed replacing the fixed string with a uuid4() call. Let me know if that is fine.

I was playing with some code here and was going to suggest this:

`os.path.basename(tempfile.mktemp(suffix='.downloading', prefix='avocado_'))`

The good side of `mktemp` is that it does not create the file (https://github.com/python/cpython/blob/cafaf0447b950fd4f59edd8cbde040c61ae528f8/Lib/tempfile.py#L382).

I'm fine with any random name function we use.

**Comment by beraldoleal** [comment]
> > @clebergnu I just force-pushed replacing the fixed string with a uuid4() call. Let me know if that is fine.
> 
> I was playing with some code here and was going to suggest this:
> 
> `os.path.basename(tempfile.mktemp(suffix='.downloading', prefix='avocado_'))`
> 
> The good side of `mktemp` is that it does not create the file (https://github.com/python/cpython/blob/cafaf0447b950fd4f59edd8cbde040c61ae528f8/Lib/tempfile.py#L382).
> 
> I'm fine with any random name function we use.

From the docs:

> A historical way to create temporary files was to first generate a file name with the mktemp() function and then create a file using this name. Unfortunately this is not secure, because a different process may create a file with this name in the time between the call to mktemp() and the subsequent attempt to create the file by the first process. The solution is to combine the two steps and create the file immediately.

**Comment by willianrampazzo** [comment]
> > > @clebergnu I just force-pushed replacing the fixed string with a uuid4() call. Let me know if that is fine.
> > 
> > 
> > I was playing with some code here and was going to suggest this:
> > `os.path.basename(tempfile.mktemp(suffix='.downloading', prefix='avocado_'))`
> > The good side of `mktemp` is that it does not create the file (https://github.com/python/cpython/blob/cafaf0447b950fd4f59edd8cbde040c61ae528f8/Lib/tempfile.py#L382).
> > I'm fine with any random name function we use.
> 
> From the docs:
> 
> > A historical way to create temporary files was to first generate a file name with the mktemp() function and then create a file using this name. Unfortunately this is not secure, because a different process may create a file with this name in the time between the call to mktemp() and the subsequent attempt to create the file by the first process. The solution is to combine the two steps and create the file immediately.

I saw that, but we won´t create the file, we will use the random name and a different path. At least, we will be using the `tempfile._get_candidate_names()` call indirectly.

**Comment by beraldoleal** [comment]
> > > > @clebergnu I just force-pushed replacing the fixed string with a uuid4() call. Let me know if that is fine.
> > > 
> > > 
> > > I was playing with some code here and was going to suggest this:
> > > `os.path.basename(tempfile.mktemp(suffix='.downloading', prefix='avocado_'))`
> > > The good side of `mktemp` is that it does not create the file (https://github.com/python/cpython/blob/cafaf0447b950fd4f59edd8cbde040c61ae528f8/Lib/tempfile.py#L382).
> > > I'm fine with any random name function we use.
> > 
> > 
> > From the docs:
> > > A historical way to create temporary files was to first generate a file name with the mktemp() function and then create a file using this name. Unfortunately this is not secure, because a different process may create a file with this name in the time between the call to mktemp() and the subsequent attempt to create the file by the first process. The solution is to combine the two steps and create the file immediately.
> 
> I saw that, but we won´t create the file, we will use the random name and a different path. At least, we will be using the `tempfile._get_candidate_names()` call indirectly.

Deprecated since version 2.3, so I will prefer to not use it.

**Comment by willianrampazzo** [comment]
> > > > > @clebergnu I just force-pushed replacing the fixed string with a uuid4() call. Let me know if that is fine.
> > > > 
> > > > 
> > > > I was playing with some code here and was going to suggest this:
> > > > `os.path.basename(tempfile.mktemp(suffix='.downloading', prefix='avocado_'))`
> > > > The good side of `mktemp` is that it does not create the file (https://github.com/python/cpython/blob/cafaf0447b950fd4f59edd8cbde040c61ae528f8/Lib/tempfile.py#L382).
> > > > I'm fine with any random name function we use.
> > > 
> > > 
> > > From the docs:
> > > > A historical way to create temporary files was to first generate a file name with the mktemp() function and then create a file using this name. Unfortunately this is not secure, because a different process may create a file with this name in the time between the call to mktemp() and the subsequent attempt to create the file by the first process. The solution is to combine the two steps and create the file immediately.
> > 
> > 
> > I saw that, but we won´t create the file, we will use the random name and a different path. At least, we will be using the `tempfile._get_candidate_names()` call indirectly.
> 
> Deprecated since version 2.3, so I will prefer to not use it.

Okay, I did not see the deprecation message.

**Review by clebergnu — APPROVED** [review]
LGTMN! Thanks! :)

**Pull request merged**
