### PR TITLE
avocado.plugins.remote: Unify test locations and use absolute path [v0]

### PR DESCRIPTION
**Pull request by ldoktor**
Hi guys, especially @jscotka, @lmr and @ruda,

this pull request unifies test locations for remote plugin. It might be one of possible solutions to the https://github.com/avocado-framework/avocado/issues/352 . There are couple of changes from before.

#. set fabric to copy file mode (tests have to be executable)
#. remote plugin turns each url into aboslute path
#. parent dirs are copied recursively into `$remote_test_dir` + `$absolute_path`
#. remote execution uses `$remote_test_dir` + `$absolute_path` to avoid clashes
#. remote paths are logged in results

I tested various executions and it seems to be more consistent. But I might missed something so please think about it for a while.

### CODE REVIEW

**Comment by ldoktor** [comment]
Btw there is still one think which needs to be solved. The `$remote_test_dir` is still hardcoded in source code. We should use `config` instead... I just haven't yet look at INI config ...

**Comment by ldoktor** [comment]
Oh I won :trophy:, this was the 1024th Travis CI run :smiley:

**Comment by ruda** [comment]
Congratulations for you 1024th Travies CI run! :clap: :clap: :clap: 

The changes in remote plugin are symmetrical to vm plugin. Would you please update both plugins?

**Comment by ldoktor** [comment]
Oh I thought `vm` plugin uses `remote` as parent and only extends it. I need to investigate that...

**Comment by ldoktor** [comment]
OK, I see. So please play a bit with this remote and comment if you have any ideas. I'll merge `vm` and `remote` common code before proceeding with this patch.

**Comment by jscotka** [comment]
Perfect, it sounds good. 
your possibility to add some option to INI for remote machine is possible, but I prefer also some default parh, like in case not types, it uses same path like localhost.
     Thanks
     Honza

**Comment by ldoktor** [comment]
Hi guys, I changed the aim of this pull request and as it's still in v0 I overwritten the changes. It's incomplete because I guess there will be discussion. I'll fix the unittests afterwards.

@lmr, @ruda, please take a look at it and let me know what do you think of my very very nasty `remote_unittest`. It's the only way I could think of which lets me test the remote plugin without remote machine. If you have nothing against, I'd probably put the nasty functions into `avocado.utils.debug` or elsewhere for other modules (eg. `vm_unittest`).

**Pull request closed without merging**
