### PR TITLE
examples.tests.simplewarning: Use -e to exit on failure

### PR DESCRIPTION
**Pull request by ldoktor**
Use -e to exit on first failure.

Signed-off-by: Lukáš Doktor <ldoktor@redhat.com>

### CODE REVIEW

**Comment by ldoktor** [comment]
@lmr would you please review this one? (if Travis passes, I waited 20 minutes so far...)

**Comment by ldoktor** [comment]
Typos fixed

**Comment by ldoktor** [comment]
Fixed the issue found by @clebergnu https://github.com/ldoktor/avocado/commit/08c624eccb9640a03ef5ae4be07c7d72ffd109fe

(sorry for not rebasing)

**Comment by lmr** [comment]
Looks good, thanks @ldoktor !

**Pull request merged**
