### PR TITLE
Dropping Python3.5 and bumping some dependencies (isort and pylint)

### PR DESCRIPTION
**Pull request by beraldoleal**
Python 3.5 has reached end-of-life. Pip and other projects are not using anymore. Also isort 5.0.0 is the first major release of isort in 5 years, and as such it does introduce some breaking changes. And it was released last year. Seems that our main issue with Github actions was fixed on isort5. Let's give a try.

Signed-off-by: Beraldo Leal <bleal@redhat.com>

### CODE REVIEW

**Comment by willianrampazzo** [comment]
It just reminds me this: https://github.com/avocado-framework/avocado/pull/4371 :)

**Comment by beraldoleal** [comment]
@willianrampazzo :man_facepalming: 

I completly forgot about your PR. but as I said there:

> If we can install easily isort 5 on major distros, we can also upgrade our requirements to install isort 5.

This PR is also upgrading pylint to avoid breakes. 

I can also add your email as signed-off here.

**Comment by willianrampazzo** [comment]
> @willianrampazzo 
> 
> I completly forgot about your PR. but as I said there:
> 
> > If we can install easily isort 5 on major distros, we can also upgrade our requirements to install isort 5.
> 
> This PR is also upgrading pylint to avoid breakes.
> 
> I can also add your email as signed-off here.

No need to do that. I just remembered we tried that once some time ago but did not merge the changes. I was looking what made us keep the things the way it is now and what changed now that allow us to move to the new package's versions.

**Review by willianrampazzo — APPROVED** [review]
Thanks for all the fixes!

**Review by clebergnu — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
