### PR TITLE
Revert Avocado Instrumented Tests Log Message Format to 92LTS Version

### PR DESCRIPTION
**Pull request by richtja**
This commit addresses compatibility concerns by reverting the log message format of Avocado instrumented tests back to the 92LTS (Long-Term Support) version. By doing so, we ensure compatibility with the upcoming LTS version.

Reference: #5721
Signed-off-by: Jan Richter <jarichte@redhat.com>

### CODE REVIEW

**Comment by richtja** [comment]
Hi @dzhengfy can you please check if this fixes https://github.com/avocado-framework/avocado/issues/5721. Thank you.

**Review by clebergnu — APPROVED** [review]
Looks right to me:

```
[stdlog] 2023-07-17 20:35:22,585 test             L0209 INFO | Avocado-VT '100.1-201-ge20d6', Branch 'master', SHA1 'e20d6f47c2198f423bbc8f420b2775e404322416'
[stdlog] 2023-07-17 20:35:22,585 utils            L0161 DEBUG| Test parameters:
[stdlog] 2023-07-17 20:35:22,585 utils            L0165 DEBUG|     auto_cpu_model = yes
...
```

**Comment by dzhengfy** [comment]
Hello @richtja ,

in debug.log, now it is fixed:
```

[stdlog] 2023-07-24 06:25:27,995 **memory_binding_s L0240** DEBUG| After vm is started, vm xml:
[stdlog] <domain xmlns:ns0="http://libosinfo.org/xmlns/libvirt/domain/1.0" type="kvm" id="1">
```

But in full.log, now it is still as before:
```
2023-07-24 06:25:25,494 **avocado.test** DEBUG| 1-type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.memory_binding_setting.hugepage.mem_mode_preferred.single_host_node: Step: vm xml before defining:
<domain xmlns:ns0="http://libosinfo.org/xmlns/libvirt/domain/1.0" type="kvm">
```

Could we make full.log fixed too?

**Comment by richtja** [comment]
> Hello @richtja ,
> 
> in debug.log, now it is fixed:
> 
> ```
> 
> [stdlog] 2023-07-24 06:25:27,995 **memory_binding_s L0240** DEBUG| After vm is started, vm xml:
> [stdlog] <domain xmlns:ns0="http://libosinfo.org/xmlns/libvirt/domain/1.0" type="kvm" id="1">
> ```
> 
> But in full.log, now it is still as before:
> 
> ```
> 2023-07-24 06:25:25,494 **avocado.test** DEBUG| 1-type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.memory_binding_setting.hugepage.mem_mode_preferred.single_host_node: Step: vm xml before defining:
> <domain xmlns:ns0="http://libosinfo.org/xmlns/libvirt/domain/1.0" type="kvm">
> ```
> 
> Could we make full.log fixed too?

Sure, I will do that. Thank you for your review.

**Comment by richtja** [comment]
Hi @dzhengfy and @clebergnu I updated the PR based on your reviews. I had to the change to how we propagate messages from runners to full.log. Please take a look. Thank you.

**Comment by dzhengfy** [comment]
@richtja ,  Test with master branch, and it looks fine to me. Thanks.

```
# vi /var/lib/avocado/job-results/job-2023-07-27T00.44-75014e8/full.log 
 **invalid_nodeset_ L0039 INFO** | TEST_STEP1: Start vm and check result
```
```
# vi /var/lib/avocado/job-results/job-2023-07-27T00.44-75014e8/test-results/1-type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.invalid_nodeset.guest.totally_inexistent.restrictive/debug.log
[stdlog] 2023-07-27 00:44:25,414 **invalid_nodeset_ L0033 DEBUG**| The init xml is:
```

**Review by dzhengfy — APPROVED** [review]
Tested and results LGTM

**Comment by dzhengfy** [comment]
@clebergnu Could you help double review it?

**Review by clebergnu — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
