### PR TITLE
Cirrus CI: run selftests on Fedora

### PR DESCRIPTION
**Pull request by clebergnu**
The tasks introduce here make use of the build requirements (most for running the selftests) that are already coded in the Fedora upstream packages.
    
Then, it installs those dependencies and sets up a development environment and runs the tests. This should be very similar to the steps that a new Avocado developer on a Fedora distro would go through.

In my observation, the overall jobs finish ~40% quicker than the Travis CI counterparts.

### CODE REVIEW

**Comment by willianrampazzo** [comment]
> /packit copr-build

Copr is timing out really early in the self-tests. I wonder if something changed on their side.

**Comment by willianrampazzo** [comment]
> Copr is timing out really early in the self-tests. I wonder if something changed on their side.

And, my quote reply triggered a copr execution... not my intention.

**Comment by clebergnu** [comment]
> It looks like `make check` is getting stuck during the package build.

@willianrampazzo indeed, I found an issue *only* on Fedora 33 and later.  Converting this to draft for now. Thanks for looking into it.

**Comment by clebergnu** [comment]
> > Copr is timing out really early in the self-tests. I wonder if something changed on their side.
> 
> And, my quote reply triggered a copr execution... not my intention.



> > Copr is timing out really early in the self-tests. I wonder if something changed on their side.
> 
> And, my quote reply triggered a copr execution... not my intention.

Opened an issue about it: https://github.com/packit/packit-service/issues/1025

**Review by beraldoleal — APPROVED** [review]
LGTM

**Review by willianrampazzo — APPROVED** [review]

**Pull request merged**
