### PR TITLE
avocado.core.plugins.multiplexer: Support for --tree-view [v1]

### PR DESCRIPTION
**Pull request by ldoktor**
This patchset adds the support for `--tree-view` and additionally tweaks the multiplexer plugin to allow enable/disable system-wide tree modifications (eg. branches added by avocado-virt).

### CODE REVIEW

**Comment by lmr** [comment]
I'm on it

**Comment by ldoktor** [comment]
Hello @adereis, I'm not sure what fonts do you have, but I used the standard utf-8 set and only execute it when you have utf-8 enabled. Thus I don't understand why it fails on your computer. I'm also using `xterm` and I can see booth version fine:

```
./scripts/avocado multiplex -c -T examples/tests/multiplextest.py.data/multiplextest.yaml
 ┗━━ run
      ┣━━ env
      ┃    ╠══ production  →gcc_flags: -O3
      ┃    ║               →malloc_perturb: False
      ┃    ╚══ debug  →gcc_flags: -g
      ┃               →malloc_perturb: True
      ┣━━ host
      ┃    ┗━━ kernel_config
      ┃         ┣━━ page_size
      ┃         ┃    ╠══ default
      ┃         ┃    ╚══ huge_pages  →huge_pages: True
      ┃         ┗━━ numa
      ┃              ╠══ default
      ┃              ╠══ numa_ballance_aggressive  →numa_balancing_migrate_deferred: 32
      ┃              ║                             →numa_balancing_scan_size_mb: 512
      ┃              ║                             →numa_balancing: 1
      ┃              ╚══ numa_ballance_light  →numa_balancing_migrate_deferred: 8
      ┃                                       →numa_balancing_scan_size_mb: 32
      ┃                                       →numa_balancing: 1
      ┣━━ guest
      ┃    ┗━━ os
      ┃         ╠══ windows  →os_type: windows
      ┃         ║    ╠══ xp  →win: xp
      ┃         ║    ╠══ 2k12  →win: 2k12
      ┃         ║    ╚══ 7  →win: 7
      ┃         ╚══ linux  →os_type: linux
      ┃              ╠══ fedora  →distro: fedora
      ┃              ╚══ ubuntu  →distro: ubuntu
      ┣━━ hardware
      ┃    ┣━━ disks
      ┃    ┃    ╠══ ide  →drive_format: ide
      ┃    ┃    ╚══ scsi  →drive_format: scsi
      ┃    ┗━━ network
      ┃         ╠══ rtl_8139  →nic_model: rtl8139
      ┃         ╠══ e1000  →nic_model: e1000
      ┃         ╚══ virtio_net  →nic_model: virtio
      ┃                         →enable_msix_vectors: True
      ┗━━ tests
           ╠══ sync_test
           ║    ╠══ standard  →sync_timeout: 30
           ║    ║             →sync_tries: 10
           ║    ╚══ aggressive  →sync_timeout: 10
           ║                    →sync_tries: 20
           ╚══ ping_test
                ╠══ standard  →ping_tries: 10
                ║             →ping_timeout: 20
                ╚══ aggressive  →ping_tries: 100
                                →ping_timeout: 5
                                →ping_flags: -f
```
```
LANG=C ./scripts/avocado multiplex -c -T examples/tests/multiplextest.py.data/multiplextest.yaml
 \-- run
      |-- env
      |    #== production  -> gcc_flags: -O3
      |    #               -> malloc_perturb: False
      |    #== debug  -> gcc_flags: -g
      |               -> malloc_perturb: True
      |-- host
      |    \-- kernel_config
      |         |-- page_size
      |         |    #== default
      |         |    #== huge_pages  -> huge_pages: True
      |         \-- numa
      |              #== default
      |              #== numa_ballance_aggressive  -> numa_balancing_migrate_deferred: 32
      |              #                             -> numa_balancing_scan_size_mb: 512
      |              #                             -> numa_balancing: 1
      |              #== numa_ballance_light  -> numa_balancing_migrate_deferred: 8
      |                                       -> numa_balancing_scan_size_mb: 32
      |                                       -> numa_balancing: 1
      |-- guest
      |    \-- os
      |         #== windows  -> os_type: windows
      |         #    #== xp  -> win: xp
      |         #    #== 2k12  -> win: 2k12
      |         #    #== 7  -> win: 7
      |         #== linux  -> os_type: linux
      |              #== fedora  -> distro: fedora
      |              #== ubuntu  -> distro: ubuntu
      |-- hardware
      |    |-- disks
      |    |    #== ide  -> drive_format: ide
      |    |    #== scsi  -> drive_format: scsi
      |    \-- network
      |         #== rtl_8139  -> nic_model: rtl8139
      |         #== e1000  -> nic_model: e1000
      |         #== virtio_net  -> nic_model: virtio
      |                         -> enable_msix_vectors: True
      \-- tests
           #== sync_test
           #    #== standard  -> sync_timeout: 30
           #    #             -> sync_tries: 10
           #    #== aggressive  -> sync_timeout: 10
           #                    -> sync_tries: 20
           #== ping_test
                #== standard  -> ping_tries: 10
                #             -> ping_timeout: 20
                #== aggressive  -> ping_tries: 100
                                -> ping_timeout: 5
                                -> ping_flags: -f
```

The reason why I invested the effort in utf-8 version is that we don't live in 2000 anymore. Utf-8 is pretty much standard and it contains set for drawing boxes. It's used eg. by "mc" and "systemd".

About the in/behind values alignment, I played with booth and this looked better to me. I can rework it and put the output here so we can vote, though...

**Comment by adereis** [comment]
The ascii version looks quite good. I'm fine with the utf8 version as long as it's not the default (enabled via config file, for example).

As a side note... I wonder what's wrong with my setup. Missing font maybe?

**Comment by ldoktor** [comment]
```
 \-- run
      \-- virt
           |-- hw  -> corruptlist: ['upper_node_list']
           |    |-- cpu  -> joinlist: ['first_item']
           |    |    #== intel  -> cpu_CFLAGS: -march=core2
           |    |    #== amd  -> joinlist: ['second', 'third']
           |    |    #        -> cpu_CFLAGS: -march=athlon64
           |    |    #== arm  -> cpu_CFLAGS: -mabi=apcs-gnu -march=armv8-a -mtune=arm8
           |    \-- disk  -> corruptlist: nonlist
           |         #    -> disk_type: virtio
           |         #== scsi  -> corruptlist: ['againlist']
           |         #         -> disk_type: scsi
           |         #== virtio
           |-- distro
           |    #== fedora  -> new_init: systemd
           |    #== RHEL  -> enterprise: True
           |    #    #== 6  -> init: systemv
           |    #    #== 7  -> init: systemd
           |    #== gentoo  -> is_cool: True
           |    #== mint  -> new_mint: True
           |-- env  -> opt_CFLAGS: -Os
           |    #== prod  -> opt_CFLAGS: -O2
           \-- absolutely
                \-- fresh
                     \-- new_node  -> new_value: something


 \-- run
      \-- virt
           |-- hw
           |    |     -> corruptlist: ['upper_node_list']
           |    |-- cpu
           |    |    #     -> joinlist: ['first_item']
           |    |    #== intel
           |    |    #     -> cpu_CFLAGS: -march=core2
           |    |    #== amd
           |    |    #     -> joinlist: ['second', 'third']
           |    |    #     -> cpu_CFLAGS: -march=athlon64
           |    |    #== arm
           |    |          -> cpu_CFLAGS: -mabi=apcs-gnu -march=armv8-a -mtune=arm8
           |    \-- disk
           |         #     -> corruptlist: nonlist
           |         #     -> disk_type: virtio
           |         #== scsi
           |         #     -> corruptlist: ['againlist']
           |         #     -> disk_type: scsi
           |         #== virtio
           |-- distro
           |    #== fedora
           |    #     -> new_init: systemd
           |    #== RHEL
           |    #    #     -> enterprise: True
           |    #    #== 6
           |    #    #     -> init: systemv
           |    #    #== 7
           |    #          -> init: systemd
           |    #== gentoo
           |    #     -> is_cool: True
           |    #== mint
           |          -> new_mint: True
           |-- env
           |    #     -> opt_CFLAGS: -Os
           |    #== prod
           |          -> opt_CFLAGS: -O2
           \-- absolutely
                \-- fresh
                     \-- new_node
                           -> new_value: something


 ┗━━ run
      ┗━━ virt
           ┣━━ hw  →corruptlist: ['upper_node_list']
           ┃    ┣━━ cpu  →joinlist: ['first_item']
           ┃    ┃    ╠══ intel  →cpu_CFLAGS: -march=core2
           ┃    ┃    ╠══ amd  →joinlist: ['second', 'third']
           ┃    ┃    ║        →cpu_CFLAGS: -march=athlon64
           ┃    ┃    ╚══ arm  →cpu_CFLAGS: -mabi=apcs-gnu -march=armv8-a -mtune=arm8
           ┃    ┗━━ disk  →corruptlist: nonlist
           ┃         ║    →disk_type: virtio
           ┃         ╠══ scsi  →corruptlist: ['againlist']
           ┃         ║         →disk_type: scsi
           ┃         ╚══ virtio
           ┣━━ distro
           ┃    ╠══ fedora  →new_init: systemd
           ┃    ╠══ RHEL  →enterprise: True
           ┃    ║    ╠══ 6  →init: systemv
           ┃    ║    ╚══ 7  →init: systemd
           ┃    ╠══ gentoo  →is_cool: True
           ┃    ╚══ mint  →new_mint: True
           ┣━━ env  →opt_CFLAGS: -Os
           ┃    ╚══ prod  →opt_CFLAGS: -O2
           ┗━━ absolutely
                ┗━━ fresh
                     ┗━━ new_node  →new_value: something

 ┗━━ run
      ┗━━ virt
           ┣━━ hw
           ┃    ┃     →corruptlist: ['upper_node_list']
           ┃    ┣━━ cpu
           ┃    ┃    ║     →joinlist: ['first_item']
           ┃    ┃    ╠══ intel
           ┃    ┃    ║     →cpu_CFLAGS: -march=core2
           ┃    ┃    ╠══ amd
           ┃    ┃    ║     →joinlist: ['second', 'third']
           ┃    ┃    ║     →cpu_CFLAGS: -march=athlon64
           ┃    ┃    ╚══ arm
           ┃    ┃          →cpu_CFLAGS: -mabi=apcs-gnu -march=armv8-a -mtune=arm8
           ┃    ┗━━ disk
           ┃         ║     →corruptlist: nonlist
           ┃         ║     →disk_type: virtio
           ┃         ╠══ scsi
           ┃         ║     →corruptlist: ['againlist']
           ┃         ║     →disk_type: scsi
           ┃         ╚══ virtio
           ┣━━ distro
           ┃    ╠══ fedora
           ┃    ║     →new_init: systemd
           ┃    ╠══ RHEL
           ┃    ║    ║     →enterprise: True
           ┃    ║    ╠══ 6
           ┃    ║    ║     →init: systemv
           ┃    ║    ╚══ 7
           ┃    ║          →init: systemd
           ┃    ╠══ gentoo
           ┃    ║     →is_cool: True
           ┃    ╚══ mint
           ┃          →new_mint: True
           ┣━━ env
           ┃    ║     →opt_CFLAGS: -Os
           ┃    ╚══ prod
           ┃          →opt_CFLAGS: -O2
           ┗━━ absolutely
                ┗━━ fresh
                     ┗━━ new_node
                           →new_value: something

```

```
-> multipine: asdf
              fdsa
-> global2: foo
-> global: bar
 |-- aaa
 |    \-- bbb  -> ccc: fdsa
 |             -> ddd: fdsa
 \-- qqqq  -> other: with_another_value
      #    -> something: with_value
      #== node  -> key3: line1
      #                  line2
      #                  line3
      #         -> key2: line1
      #                  line2
      #                  line3
      #         -> key1: gagg
      #== huh
           \-- grrrr
                \-- bzzzzz

-> multipine: asdf
->            fdsa
-> global2: foo
-> global: bar
 |-- aaa
 |    \-- bbb
 |          -> ccc: fdsa
 |          -> ddd: fdsa
 \-- qqqq
      #     -> other: with_another_value
      #     -> something: with_value
      #== node
      #     -> key3: line1
      #              line2
      #              line3
      #     -> key2: line1
      #              line2
      #              line3
      #     -> key1: gagg
      #== huh
           \-- grrrr
                \-- bzzzzz

→multipine: asdf
            fdsa
→global2: foo
→global: bar
 ┣━━ aaa
 ┃    ┗━━ bbb  →ccc: fdsa
 ┃             →ddd: fdsa
 ┗━━ qqqq  →other: with_another_value
      ║    →something: with_value
      ╠══ node  →key3: line1
      ║                line2
      ║                line3
      ║         →key2: line1
      ║                line2
      ║                line3
      ║         →key1: gagg
      ╚══ huh
           ┗━━ grrrr
                ┗━━ bzzzzz

→multipine: asdf
→           fdsa
→global2: foo
→global: bar
 ┣━━ aaa
 ┃    ┗━━ bbb
 ┃          →ccc: fdsa
 ┃          →ddd: fdsa
 ┗━━ qqqq
      ║     →other: with_another_value
      ║     →something: with_value
      ╠══ node
      ║     →key3: line1
      ║            line2
      ║            line3
      ║     →key2: line1
      ║            line2
      ║            line3
      ║     →key1: gagg
      ╚══ huh
           ┗━━ grrrr
                ┗━━ bzzzzz
```

**Comment by adereis** [comment]
Regarding the alignment:

```
      ┣━━ env
      ┃    ╠══ production  →gcc_flags: -O3
      ┃    ║               →malloc_perturb: False
      ┃    ╚══ debug  →gcc_flags: -g
      ┃               →malloc_perturb: True
```
vs

```
      ┣━━ env
      ┃    ╠══ production  
      ┃    ║      →gcc_flags: -O3
      ┃    ║      →malloc_perturb: False
      ┃    ╚══ debug  
      ┃           →gcc_flags: -g
      ┃           →malloc_perturb: True
```

I prefer the latter, it's much easier to me to compare the variables of the two sibling branches.

**Comment by ldoktor** [comment]
Btw in xterm the lines are continuous and everything looks much smother than here... I'm really curious why it doesn't work on your setup. As I said I'm using standard utf-8 characters and I'm checking in python that you have utf-8 enabled (that's why when I run the same with `LANG=C` it produces `ASCII` version.

**Comment by adereis** [comment]
OK, so I found the issue. Several xterm fixed fonts miss (some) utf8 characters. I was starting my xterm with -font -*-fixed-*-*-*-*-18-*-*-*-*-*-*-*. Using the default xterm font, or using fonts from FreeType via -fa works fine.

I wonder if there's a more robust way to detect this than trusting locale env variables, but I'm OK with the current approach of using utf8 by default (until we see more users reporting issues, at least).

**Comment by adereis** [comment]
What about my other point from a previous message:

> What's the motivation for keeping both --tree and --tree-view? I think we should keep things simple: one output should be enough for everybody. I'm sure everybody will get used to the new format.

**Comment by lmr** [comment]
@ldoktor mentioned that he likes the 'old' view better for certain situations. That said, I agree that we should keep a single representation of the tree, so dropping `--tree` is fine by me.

**Comment by ldoktor** [comment]
I can remove the `--tree`. I wanted to leave at this point to have simple comparison.

Anyway if I understand the situation:

1. remove the --tree
2. keep the utf8 by default and trust LOCALES
3. value nodes:
    * keep as here: @ldoktor
    * put inside node: @adereis

@lmr, @clebergnu, @ruda which do you prefer?

**Comment by adereis** [comment]
Instead of removing --tree and introducing --tree-view, just replace the implementation of --tree.

**Comment by ldoktor** [comment]
no worry, that was my intention :smile: (--tree)

**Comment by lmr** [comment]
@ldoktor my choices:

1) Replace --tree
2) Keep utf8 by default and trust locales
3) Value nodes inside node if possible (I don't find it terribly important, but it's a nice to have)

**Comment by adereis** [comment]
Another issue with the unaligned variables is when you have long variant names. See this example:

```
      ┣━━ env
      ┃    ╠══ production_legacy_winxp →gcc_flags: -O0
      ┃    ║                           →malloc_perturb: False
      ┃    ╠══ production  →gcc_flags: -O3
      ┃    ║               →malloc_perturb: False
      ┃    ╚══ debug  →gcc_flags: -g
      ┃               →malloc_perturb: True
```
vs

```
      ┣━━ env
      ┃    ╠══ production_legacy_winxp 
      ┃    ║      →gcc_flags: -O0
      ┃    ║      →malloc_perturb: False
      ┃    ╠══ production  
      ┃    ║      →gcc_flags: -O3
      ┃    ║      →malloc_perturb: False
      ┃    ╚══ debug  
      ┃           →gcc_flags: -g
      ┃           →malloc_perturb: True
```

**Comment by clebergnu** [comment]
@ldoktor, replacing `--tree` definitely. I also think the variables can look better if they're inside the nodes.

**Comment by ldoktor** [comment]
@adereis your example is quite simple, take a look at the outputs above. They are more complex and the difference is greater. (the smaller but wider is what I prefer, the longer and narrower prefers Ademar)

**Comment by adereis** [comment]
Looks like we have consensus about the other items, but we haven't discussed these two minor points:

 * Can you make the output of -c to be a result of the processed tree? That means the leaves would include the variables that were inherited from their parents and no variables would be in a non-leave branch.
 * Some options are incompatible with --tree. Avocado should return an error if they're used together (for example, --debug).

And a new one, also minor: when redirecting the output to a file or a pipe, utf8 is disabled. It's not a big deal, it's just a little odd, so I want to confirm this is intended.

**Comment by ldoktor** [comment]
About the environment vs. variables, yes. I can show the result there, but for bigger setups it'd be unreadable, therefor I chose to show variables instead. This view is identical to how yaml files are written and people should be able to combine the values themselves. Although they can see the result in non-tree mode.Anyway if you insist, let's support different flag for values only or full environment, what do you think?

Yes, I'm aware of incompatible options and actually noted that to my TODO list. But since they were there before I haven't spend time on it right now... It should be simple by argparse collision domains, I only never used them so I have to take a look on how they work first... I can add this to the next version if you like.

About the pipe yes. Pipe is not utf-8. So if you want an output in utf8 format you have to support writing to file as an argument. (btw this is independent of the results directory, we can write in utf-8 (controled by settings) form when user asks for it there and not support it in "avocado multiplex", that was again my intention)

**Comment by adereis** [comment]
My motivation for requesting the output of variables in the leaf nodes (resolving all inheritance) is to aid the debug. Once one starts merging and injecting trees, the structure becomes quite complex, so having a final tree visualized should be helpful. Having an additional, different switch for that would work.

Regarding the options, it's fine if you leave it for a future task, it was there before indeed. I'm assuming it's a low hanging fruit. If you don't fix it now, we should create a card for it.

Finally, regarding utf8, what do you think of a config entry:

```
[runner.output]
utf8 = {on, off, auto}
```
(there's `colored = {on/off}` in `[runner.output]` already)

**Pull request closed without merging**
