### PR TITLE
Backport PR 4239 to 82lts

### PR DESCRIPTION
**Pull request by mcondotta**
This fix is needed to run Avocado-VT tests, specially on s390x systems.

### CODE REVIEW

**Review by willianrampazzo — APPROVED** [review]

**Comment by clebergnu** [comment]
@beraldoleal we should try our very hard to fix bugs without changing the API. In this case, it's raising a new exception. Do you see a way to fix this bug in a more compatible way?

**Comment by willianrampazzo** [comment]
> @beraldoleal we should try our very hard to fix bugs without changing the API. In this case, it's raising a new exception. Do you see a way to fix this bug in a more compatible way?

Maybe, backport lines 216 and 217 only. I think that is the missing part to run on s390x.

**Comment by beraldoleal** [comment]
> @beraldoleal we should try our very hard to fix bugs without changing the API. In this case, it's raising a new exception. Do you see a way to fix this bug in a more compatible way?

I understand your point and yes, we could make it simpler here and go just straight to the point. But at the same time I'm trying to figure out how we could evolve the code without break the API. When changing methods signatures significantly I can see the need for a warning deprecation in favor of a new method. But in this case, I don't think that deprecating a method in favor of another just because of a new exception is the best option.

> Maybe, backport lines 216 and 217 only. I think that is the missing part to run on s390x.

IMO, this method has more than one bug. And this is just one of them. Currently we are getting different behaviors depending on the architecture/family. And this is what I'm trying to fix here. We should try to avoid returning None, this will give upper layers no reasons why this not worked. Specially here where None is returned only in a few cases and in others a proper exception is generated.

**Comment by beraldoleal** [comment]
I just notice the LTS branch here. So I guess we can go with @willianrampazzo suggestion here.

@mcondotta do you need some help? Or can you change this PR as @willianrampazzo suggested?

But I'm still wondering what about new exceptions on our master.

**Comment by clebergnu** [comment]
> I just notice the LTS branch. So I guess we can go with @willianrampazzo suggestion here.
> 

Yep, the context of the question was the LTS branch.

> @mcondotta do you need some help? Or could you change this PR as @willianrampazzo suggested?
> 
> But I'm still wondering what about new exceptions on our master.

Master is the place where all such a change is clearly OK.  So much that it *was* merged into master, right? ;)

**Comment by clebergnu** [comment]
@mcondotta let us know if you need any help here.

**Comment by beraldoleal** [comment]
@clebergnu @mcondotta, closing this in favor of #4276.

**Pull request closed without merging**
