### PR TITLE
Testing of scripts inside documentation

### PR DESCRIPTION
**Pull request by richtja**
This is a draft for documentation scripts testing.
It is about testing every script inside avocado documentation and keep documentation updated and also create runnable examples for users which will correspond with documentation #4246.  This is an example of how it could look like. I will be glad for any comments before I will start with creating scripts from the documentation.

### CODE REVIEW

**Comment by willianrampazzo** [comment]
Humm, I was thinking about something much simpler, but, maybe, what I was thinking is not possible, or there is a better way of doing that.

My idea was to have the tests under `examples/docs` as avocado python tests and a script under `selftests` to run and test them. Those tests would be imported into the documentation as examples.

I know there are tools to test code into the documentation, but I don't know if we need all those features.

Anyway, let me know if what I'm proposing here makes no sense :)

**Comment by beraldoleal** [comment]
Having scripts that will run the current avocado output and replacing the documentation could be nice but at same time I'm asking if we are not putting the issues "under the carpet".

I was thinking similar to @willianrampazzo . Did you tried that before? Found some issues?

Also, I would try to convert the bash scripts to python too.

**Comment by richtja** [comment]
> My idea was to have the tests under `examples/docs` as avocado python tests and a script under `selftests` to run and test them. Those tests would be imported into the documentation as examples.

Thanks, @willianrampazzo, actually I can't see how to use the tests under `examples/docs` as avocado python tests, because most of the examples inside documentation are examples of Avocado command-line and I want to create examples scripts which users can run and will be same as Avocado command-line. But you are right that we can test these scripts under `selftests` by avocado and remove the files with exit statuses.

**Comment by richtja** [comment]
@beraldoleal Thanks for your comments.

> Having scripts that will run the current avocado output and replacing the documentation could be nice but at same time I'm asking if we are not putting the issues "under the carpet".

think that this is not putting the issues "under the carpet" because we would test every script inside the documentation if it's not broken. 

> I was thinking similar to @willianrampazzo . Did you tried that before? Found some issues?

Do you mean use tools to test code into the documentation? I did some research and look for possibilities and didn't find anything without problems. We had a discussion about it here # 4246

> Also, I would try to convert the bash scripts to python too.

Yes I agree and I will do it.

**Review by beraldoleal — CHANGES_REQUESTED** [review]
Hi @richtja ,

My only suggestion by now is to replace the bash script with a python script.

**Comment by beraldoleal** [comment]
@richtja let me know what do you think about having the python script. If you think that is not possible to add before the next version, no worries.

**Comment by richtja** [comment]
@beraldoleal sorry that I didn't answer. I was focusing on the other tasks and leave this behind. I already replace the bash script with a python script, but when I started cover the documentation I ran into a lot of problems which have to be solved for different types of examples in documentation. Because of that I didn't push the solution yet.

**Pull request closed without merging**
