### PR TITLE
avocado.pugins.replay record/replay loader options

### PR DESCRIPTION
**Pull request by apahim**
Record the loader options and reload them on job replay.
Reference: https://trello.com/c/N3UCnR05

### CODE REVIEW

**Comment by apahim** [comment]
Rebased to take advantage of #1051.

**Comment by apahim** [comment]
> how about creating the `whitelist = ["loaders", "external_runner", ...] and do this in a loop as the notifications can be generic?

+1 as well

> save those arguments in text format, as it's done with urls and config

Yes, as @ldoktor said, args are already processed. We could save only the whitelisted and handle one by one the processed args to transform them in plain text, but yes it would be expensive.

> I'd be nice to create a yaml file out of the tree.

This is a good rfe indeed.

**Comment by clebergnu** [comment]
Agreed with all the points given!

**Comment by apahim** [comment]
Closed in favor of #1056

**Pull request closed without merging**
