### PR TITLE
check config in running kernel and return status[v2]

### PR DESCRIPTION
**Pull request by PraveenPenguin**
Signed-off-by: Praveen K Pandey <praveen@linux.vnet.ibm.com>
v1 #1392 
```

v2: modify method documentation
v2: added python enum
```

### CODE REVIEW

**Comment by apahim** [comment]
@PraveenPenguin I canceled the travis job because it was running for 46+ minutes already. Please rebase it so travis can check only the difference between your commit(s) and current master HEAD.

**Comment by apahim** [comment]
(you can force update after the rebase)

**Comment by PraveenPenguin** [comment]
@apahim sure will do , need one help i go though travis run and figure  it failed here 

```
ERROR: test_build_docs (selftests.doc.test_doc_build.DocBuildTest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/avocado-framework/avocado/selftests/doc/test_doc_build.py", line 77, in test_build_docs

    raise DocBuildError(e_msg)

DocBuildError: 1 ERRORS and/or WARNINGS detected while building the html docs:

1) /home/travis/build/avocado-framework/avocado/avocado/utils/linux_modules.py:docstring of avocado.utils.linux_modules:5: WARNING: Definition list ends without a blank line; unexpected unindent.

Full output: make: Entering directory `/home/travis/build/avocado-framework/avocado/docs'

sphinx-build -b html -d build/doctrees   source build/html
```

and i check through  pep8 as well as pylint in my  system and both are passed

**Comment by apahim** [comment]
@PraveenPenguin it's sphinx doc build tricking you. This is about the docstring you added in lines 21-25. You could fix the error, but still the text is quite bad to understand and also out of context. You better just keep the docstring as it was before.

**Comment by apahim** [comment]
Or, better, change to:
```
"""
Linux kernel modules APIs
"""
```

**Comment by apahim** [comment]
Then let each API's docstring speaks by its own :)

**Comment by PraveenPenguin** [comment]
raised new PR #1411

**Comment by PraveenPenguin** [comment]
raised new PR #1411

**Pull request closed without merging**
