### PR TITLE
avocado.core.test: Remove the obsoleted "runTest" [v2]

### PR DESCRIPTION
**Pull request by ldoktor**
This patchset removes the support for obsoleted "runTest" and replaces it with "test" instead. Additionally it splits the "gendata" test into two subtests and adds unittest which verifies it creates 2 tests and that files are created correct locations.

v1: https://github.com/avocado-framework/avocado/pull/687

Changes:

    v2: Check if user defined exception is valid

_Note: This patchset is built on top of the https://github.com/avocado-framework/avocado/pull/686 pull request in order to fix the test which is added there._

### CODE REVIEW

**Comment by ldoktor** [comment]
Hello @lmr, I think we shouldn't prevent users to define whatever status they like as far as it's a valid status and that's what this patch does.

Btw I'd prefer if the user can use "BEACON" and we map all unknown statuses to ERROR, although that's probably a subject to wider discussion so let's stick to valid mapping instead :smile:

**Comment by lmr** [comment]
@ldoktor:

        $ inspekt style
        /home/travis/build/avocado-framework/avocado/avocado/core/test.py:450:38: E128 continuation line under-indented for visual indent
        /home/travis/build/avocado-framework/avocado/avocado/core/test.py:451:38: E128 continuation line under-indented for visual indent
        PEP8 check fail: /home/travis/build/avocado-framework/avocado/avocado/core/test.py
        PEP8 compliance FAIL

**Comment by adereis** [comment]
A few extra things to consider:

 1. We should document all test statuses somewhere. To keep things simple, I suggest we document it in the ReferenceGuide.rst file, Test Types -> Instrumented.
 2. Notice that there's no notion of test error in case of simple tests. Simple tests either pass or fail. Unless Avocado itself raises an exception (but I can't think of any way this would happen during the execution of a simple test, as there's no interaction between avocado and a simple test). Anyway, can you please make sure this is consistent with your current patch?
 3. In Output Record/Compare mode, it should still work. I just want to make sure we're dealing with this case: different output raises exception, which should be handled as test FAILure. Other exceptions would be ERRORs.

**Comment by ldoktor** [comment]
Yes, simple tests should only finish as PASS/FAIL, but error can happen during during simple test handling, thus ERROR might be possible too in some cases.

The record/compare raises known exception, so it's FAIL in case of failure.

**Pull request closed without merging**
