### PR TITLE
avocado.job: Refactor how multiplexation happens

### PR DESCRIPTION
**Pull request by ldoktor**
Hello guys,

apart from one bugfix this patch makes no real changes (therefor no unittests needs to be adjusted), it only refactors how we generate multiplexed variants. It prepares the code for the "real" multiplexer with namespaces support. I'd like to do these little steps rather then preparing a big patch set with all the changes.

Regards,
Lukáš

### CODE REVIEW

**Comment by ldoktor** [comment]
The bug is described here:

https://trello.com/c/SNgN1F33/356-bug-corrupted-results-when-running-multiple-tests-with-the-same-name-and-using-multiplexer

**Comment by lmr** [comment]
I've caught a little problem here:

    $ scripts/avocado run multiplextest --multiplex examples/tests/multiplextest.py.data/multiplextest.yaml 
    JOB ID     : 24c4321b3a7d41f4253c4070c0682b3f3d76ff9c
    JOB LOG    : /home/lmr/avocado/job-results/job-2015-03-24T15.35-24c4321/job.log
    JOB HTML   : /home/lmr/avocado/job-results/job-2015-03-24T15.35-24c4321/html/results.html
    TESTS      : 1
    (1/1) multiplextest.py.0: PASS (0.00 s)
    (2/1) multiplextest.py.1: PASS (0.00 s)
    (3/1) multiplextest.py.2: PASS (0.00 s)
    ...
    (864/1) multiplextest.py.863: PASS (0.00 s)
    PASS       : 864
    ERROR      : 0
    FAIL       : 0
    SKIP       : 0
    WARN       : 0
    TIME       : 1.85 s

So the numbers are not being updated here. I guess we need an extra test at the multiplexer test to ensure our indexes are being correctly updated.

**Comment by ldoktor** [comment]
@lmr what's wrong with the index? I don't see any problems.

**Comment by lmr** [comment]
@ldoktor, The correct final line should be:

    (864/864) multiplextest.py.863: PASS (0.00 s)

and not

    (864/1) multiplextest.py.863: PASS (0.00 s)

As we're getting now.

**Comment by ldoktor** [comment]
Oh this index :smile:. Tomorrow I'll take care of it.

**Pull request closed without merging**
