### PR TITLE
Adding Multipath Module [v4]

### PR DESCRIPTION
**Pull request by narasimhan-v**
avocado.utils.multipath: Adds multipath related modules.

Changelog from v1 #1547 :
*) Used utils.service to restart and to check status of multipath service
*) Added a check to see if multipath devices exist, on all required functions, so that IndexError is not encountered.
*) Using logging.debug(open().read()) to display contents of the file, as per comments.
*) Based on comments, changed function name to device_exists
*) Removed raising of Exception, since its codepath is not existing anymore.
*) Mentioned that the module needs to be used only by root user.

Changelog from v2 #1559 :
*) Made use of process.can_sudo() to fail early in case sudo access is not there in test.
*) Used sudo=True in functions of process module, as necessary.
*) Made sure return types are consistent.
*) Added a helper function for finding the multipath service name based on distro.

Changelog from v3 #1646 :
*) Removed the use of process.can_sudo() since Travis CI was failing.

Signed-off-by: Narasimhan V <sim@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by narasimhan-v** [comment]
@apahim Hope this PR works fine.

**Comment by apahim** [comment]
@narasimhan-v yes, I hope so. It looks ok, I just want to run some tests with it.

**Comment by narasimhan-v** [comment]
@apahim You can see one of the test where I used this module https://github.com/avocado-framework-tests/avocado-misc-tests/pull/128

**Comment by apahim** [comment]
Merged after rebase.

**Comment by narasimhan-v** [comment]
@apahim Sure, thanks

**Pull request closed without merging**
