### PR TITLE
Remove class inheriting from object

### PR DESCRIPTION
**Pull request by tiagohonorato**
Unlike in python2, python3 classes inheritance from object is implicit. As
a result, since python2 is no longer supported in Avocado, this can be
safely removed.

Related to #3466

Signed-off-by: Tiago Honorato <tiagohonorato1@gmail.com>

### CODE REVIEW

**Review by richtja — CHANGES_REQUESTED** [review]
Hi @tiagohonorato, I find another occurrences in [dont_crash.py](https://github.com/avocado-framework/avocado/blob/master/selftests/.data/loader_instrumented/dont_crash.py). Can you please add those as well. It looks like lint check doesn't consider such files. I create issue #4437 about this problem.

**Review by beraldoleal — APPROVED** [review]
Besides the @richtja recommendation, this LGTM.

**Comment by tiagohonorato** [comment]
> Hi @tiagohonorato, I find another occurrences in [dont_crash.py](https://github.com/avocado-framework/avocado/blob/master/selftests/.data/loader_instrumented/dont_crash.py). Can you please add those as well. It looks like lint check doesn't consider such files. I create issue #4437 about this problem.

Hi @richtja, thank you for this. I will include it here.

**Review by richtja — APPROVED** [review]
LGTM, thanks

**Pull request merged**
