### PR TITLE
avocado.core.plugins.multiplexer: Support for --tree-view [v2]

### PR DESCRIPTION
**Pull request by ldoktor**
This patchset adds the support for --tree-view and additionally tweaks the multiplexer plugin to allow enable/disable system-wide tree modifications (eg. branches added by avocado-virt).

v1: https://github.com/avocado-framework/avocado/pull/654

Changelog:

    v2: Align values inside the node
    v2: better locale handling
    v2: fix root node path
    v2: fix store origin as path rather than name
    v2: add possibility to show environment instead of values
    v2: reorganize arguments and handle clashes
    v2: add support for path in default/environment view

_NOTE: I added each new feature as separate commit to be able to remove them when we decide not to use it. The final version will have the patches reorganized and squashed. There is no need to point that something should be part of a different patch._

### CODE REVIEW

**Comment by adereis** [comment]
Looks good, a few comments:

Given the example:

```
      ┃         ╚══ linux
      ┃              ║     →os_type: linux
      ┃              ╠══ fedora
      ┃              ║        →os_type: linux
      ┃              ║        →distro: fedora
      ┃              ╚══ ubuntu
      ┃                       →os_type: linux
      ┃                       →distro: ubuntu
```

 * The identation is duplicated for the variables.
 * My suggestion was to, when resolving inheritance, show only the result of the inheritance, or "only the variables in the leaves", while the current implemention shows both (as is the case with `os_type` above)
 * I see redirection is working fine now, because you're checking the locale. Do you still see value in the suggestion of using a configuration entry like `utf8 = {on,off,auto}`?
 * `--env` is missing documentation
 * We need better documentation for the options, and there is different and confusing usage of the word "environment" to name and/or document the options:

```
 [...]
  -c, --contents        Shows the variant content (variables)
  --env [ENV [ENV ...]]

environment view options:
  -d, --debug           Debug multiplexed files.

tree view options:
  -t, --tree            Shows the multiplex tree structure
  -e, --environment     Show environment rather than value
```

I would rather use something like "resolve inheritance" instead of --environment for the last option. And instead of "environment view options", maybe call it "variant view options" (vs "tree view options").

Maybe --env could be better named as well, but I have no suggestion and I consider it a topic for a different discussion.

**Comment by adereis** [comment]
Noted by Lucas, and I agree: there should be a space between `→` and the variable name.

**Comment by ldoktor** [comment]
Hello:

1. yes, I tweaked that to 8 spaces because otherwise nodes without leaves had values at the same level as parent nodes making it very hard to notify they are not of the same level. Anyway I can change it, if you think it's better. It's just a matter of tweaking it.
2. I didn't got that from the description, anyway I can do that, although I don't think it's that much necessarily, because when you are interested in leaves environments only, you can use the non-tree view. That's actually what you see there. That's why I put env everywhere to make it simpler for users to debug problems when writing the yaml files. It was not intended for checking of the final results as normal view is better for that.
3. no need to mention settings, I'd add it in the final version anyway. This pull request was about the look'n'feel as that's a matter of taste, thus hard to get in one iteration.
4. Sry, I'll add it
5. I'm aware of that and I'm open to suggestions... Actually first I implemented -c -cc -ccc but I'm not sure if people would prefer that... (bad luck -v is taken)
6. tree view and variants view sounds better, thanks
7. `--env` sounds good to me, but if you find a better alternative...
8. Again, matter of taste. To me without space →value looks better. It's more compressed and I doubt anyone would think it's part of the value. But same as others, I have no strong feelings about look'n'feel so I can return it back if he majority asks for it.

ad 1: T

```
      ┣━━ hw
      ┃    ┃    →corruptlist: ['upper_node_list']
      ┃    ┣━━ cpu
      ┃    ┃    ║    →corruptlist: ['upper_node_list']
      ┃    ┃    ║    →joinlist: ['first_item']
      ┃    ┃    ╠══ intel
      ┃    ┃    ║    →corruptlist: ['upper_node_list']
      ┃    ┃    ║    →joinlist: ['first_item']
      ┃    ┃    ║    →cpu_CFLAGS: -march=core2
```
vs.
```
      ┣━━ hw
      ┃    ┃   →corruptlist: ['upper_node_list']
      ┃    ┣━━ cpu
      ┃    ┃    ║   →corruptlist: ['upper_node_list']
      ┃    ┃    ║   →joinlist: ['first_item']
      ┃    ┃    ╠══ intel
      ┃    ┃    ║     →corruptlist: ['upper_node_list']
      ┃    ┃    ║     →joinlist: ['first_item']
      ┃    ┃    ║     →cpu_CFLAGS: -march=core2
```
vs.
```
      ┣━━ hw
      ┃    ┃     →corruptlist: ['upper_node_list']
      ┃    ┣━━ cpu
      ┃    ┃    ║     →corruptlist: ['upper_node_list']
      ┃    ┃    ║     →joinlist: ['first_item']
      ┃    ┃    ╠══ intel
      ┃    ┃    ║        →corruptlist: ['upper_node_list']
      ┃    ┃    ║        →joinlist: ['first_item']
      ┃    ┃    ║        →cpu_CFLAGS: -march=core2
      ┃    ┃    ╠══ amd
```

I like the 2nd as the difference between /hw/cpu and /hw/cpu/intel is bigger.

**Comment by adereis** [comment]
> 
> Hello:

Doing my best to work with the github quoting system:

> 
>     yes, I tweaked that to 8 spaces because otherwise nodes without leaves had values at the same level as parent nodes making it very hard to notify they are not of the same level. Anyway I can change it, if you think it's better. It's just a matter of tweaking it.

Seeing your examples below, 4 spaces, consistent with everything else definitely
looks better to my eyes.

>     I didn't got that from the description, anyway I can do that, although I don't think it's that much necessarily, because when you are interested in leaves environments only, you can use the non-tree view. That's actually what you see there. That's why I put env everywhere to make it simpler for users to debug problems when writing the yaml files. It was not intended for checking of the final results as normal view is better for that.

Well, maybe it's a matter of taste, but what I expect is to debug the tree by
looking at the variants and their variables in the tree. I always think of the
multiplexer as a tree, I avoid looking at the resulting list of variants. When
considering internal filters, thinking about it as a tree is essential for
proper understanding.

So yes, that was my motivation for having a tree output, sorry if it was not
clear in the original requirement. Can you implement --inherit or something
similar and show the variables only in the leaves?

>     no need to mention settings, I'd add it in the final version anyway. This pull request was about the look'n'feel as that's a matter of taste, thus hard to get in one iteration.

No problem, I was just checking. It was just an idea, I don't know how much
merit it has.

>     Sry, I'll add it

OK.

>     I'm aware of that and I'm open to suggestions... Actually first I implemented -c -cc -ccc but I'm not sure if people would prefer that... (bad luck -v is taken)

I guess you're talking about the inheritance option, called --environment? I
would call it --inherit and get done with it. Multiple -c would be OK too:

  -c: show variants contents (variables). Multiple -c mean different behavior
  regarding variable inheritance resolution: 1) in place variables, 2) solved
  inheritance , 3) both
  --contents={variables,inheritance,all}

>     tree view and variants view sounds better, thanks
>     --env sounds good to me, but if you find a better alternative...

Like I said, no suggestion, off topic for this discussion.

>     Again, matter of taste. To me without space →value looks better. It's more compressed and I doubt anyone would think it's part of the value. But same as others, I have no strong feelings about look'n'feel so I can return it back if he majority asks for it.
> 
> ad 1: Choices
> 
>       ┣━━ hw
>       ┃    ┃    →corruptlist: ['upper_node_list']
>       ┃    ┣━━ cpu
>       ┃    ┃    ║    →corruptlist: ['upper_node_list']
>       ┃    ┃    ║    →joinlist: ['first_item']
>       ┃    ┃    ╠══ intel
>       ┃    ┃    ║    →corruptlist: ['upper_node_list']
>       ┃    ┃    ║    →joinlist: ['first_item']
>       ┃    ┃    ║    →cpu_CFLAGS: -march=core2
> 
> vs.
> 
>       ┣━━ hw
>       ┃    ┃   →corruptlist: ['upper_node_list']
>       ┃    ┣━━ cpu
>       ┃    ┃    ║   →corruptlist: ['upper_node_list']
>       ┃    ┃    ║   →joinlist: ['first_item']
>       ┃    ┃    ╠══ intel
>       ┃    ┃    ║     →corruptlist: ['upper_node_list']
>       ┃    ┃    ║     →joinlist: ['first_item']
>       ┃    ┃    ║     →cpu_CFLAGS: -march=core2
> 
> vs.
> 
>       ┣━━ hw
>       ┃    ┃     →corruptlist: ['upper_node_list']
>       ┃    ┣━━ cpu
>       ┃    ┃    ║     →corruptlist: ['upper_node_list']
>       ┃    ┃    ║     →joinlist: ['first_item']
>       ┃    ┃    ╠══ intel
>       ┃    ┃    ║        →corruptlist: ['upper_node_list']
>       ┃    ┃    ║        →joinlist: ['first_item']
>       ┃    ┃    ║        →cpu_CFLAGS: -march=core2
>       ┃    ┃    ╠══ amd
> 
> I like the 2nd as the difference between /hw/cpu and /hw/cpu/intel is bigger.

I don't want to see /hw or /hw/cpu variables there. They're not useful for me.

So what I would like to see is:

```
┣━━ hw
┃    ┣━━ cpu
┃    ┃    ╠══ intel
┃    ┃    ║    → corruptlist: ['upper_node_list']
┃    ┃    ║    → joinlist: ['first_item']
┃    ┃    ║    → cpu_CFLAGS: -march=core2
┃    ┃    ╠══ amd
┃    ┃    ║    → corruptlist: ['upper_node_list']
┃    ┃    ║    → joinlist: ['first_item']
┃    ┃    ║    → cpu_CFLAGS: -march=core2
```

**Pull request closed without merging**
