### PR TITLE
Updating pci and multipath utils to python3

### PR DESCRIPTION
**Pull request by narasimhan-v**
Updating pci and multipath utils to work with the latest
python standards. Also included pylint fixes.

Signed-off-by: Narasimhan V <sim@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by narasimhan-v** [comment]
@clebergnu so `process.run().stdout_text` is preferred to `process.system_output()` ?

**Comment by clebergnu** [comment]
It's preferred because it follows a more consistent approach to turn bytes
into text.

**Comment by clebergnu** [comment]
@narasimhan-v I'm assuming you proceeded with the use of `process.run().stdout_text`. If not, please reopen and let's work towards a suitable solution.  Thanks

**Comment by narasimhan-v** [comment]
@clebergnu Apologies for missing to notice this for a long time. Addressed your comments via https://github.com/avocado-framework/avocado/pull/3378

**Pull request closed without merging**
