### PR TITLE
Limit line-length to 79 characters #5285

### PR DESCRIPTION
**Pull request by al5929**
Issue #5285
Limit line-length to 79 characters

Please note not every line is fixed, but hopefully most of them are now in accordance with C0301

### CODE REVIEW

**Comment by ana** [comment]
Hi @al5929 , thanks for your PR!
After you forked your branch, there were new changes merged in avocado and your PR is conflicting with them. Please, rebase your branch, solve the conflicts and update the PR (a force-push is ok).

**Comment by ana** [comment]
Hi again @al5929 
Updating all files at once is going to create conflicts easily. So what about splitting this PR?
For example, start with `optional_plugins` and/or `examples`.

**Comment by al5929** [comment]
Apologies, @ana
I'm a bit confused as to how to view and fix the merge conflicts

**Comment by ana** [comment]
> Apologies, @ana I'm a bit confused as to how to view and fix the merge conflicts

There are too many for github to show. You can look at them from the cli after rebasing the master branch.
If you are not familiar with this, please see:
https://docs.github.com/en/get-started/using-git/resolving-merge-conflicts-after-a-git-rebase
https://docs.github.com/en/get-started/using-git/about-git-rebase

**Pull request closed without merging**
