### PR TITLE
Fix travis build for python2.6

### PR DESCRIPTION
**Pull request by apahim**
For some reason pycrypto from pip became a critical
dependency for fabric in el6/python26. If not in requirements,
fabric module can not be loaded and remote plugin is
disabled.

This patch adds pycrypto to the travis requirements.

### CODE REVIEW

**Comment by ldoktor** [comment]
Nice, would you please also add it to `requirements.txt`? It's usually installed, but it might not be like that on all machines. While on it please update the `avocado.spec` too.

**Comment by clebergnu** [comment]
@ldoktor `avocado.spec` should not be changed. SPEC files should not "walk" all the way down to dependencies of dependencies.

**Comment by ldoktor** [comment]
Oh yeah, that's true. Fabric should have it in dependencies... (pip should also walk the dependencies, but the reality is...).

Anyway @apahim please add it to `requirements.txt`.

**Comment by apahim** [comment]
@ldoktor, I'm not sure it's needed in `requirements.txt`. In `requirements-travis.txt`, the fabric version is fixed as `1.10.0`. In `requirements.txt`, the fabric version is anything >= `1.7.0`. This can be making difference the for this issue, since the current fabric is `1.11.1`. I could not reproduce it with `pip install -r requirements.txt`, only with `pip install -r requirements-travis.txt`.

**Pull request closed without merging**
