### PR TITLE
[V12] Load/List tests from multiple sources

### PR DESCRIPTION
**Pull request by lmr**
This is a follow up to PR #632

The PR has been renamed because it no longer contains the actual virt test compatibility plugins. However, you definitely want to test this together with the avocado-vt initial pull request (see below).

You can try out this work by following the steps:

1) Check out this branch
2) Set the environment variable 'VIRT_TEST_PATH' to a path containing a copy of virt test
3) The copy of virt-test has to be in my new branch avocado-integration-v4 [1]
4) Check out the avocado-vt repo, then merge PR 1 -> avocado-framework/avocado-vt#3. The code checked out has to be in the same base dir as your copy of avocado
5) Type `make link` in the avocado dir, so that the plugins can be properly linked.
6) Bootstrap your testing in the virt test dir by running `./run -t qemu --bootstrap`
7) Run your tests with the command above
8) Now you can use `scripts/avocado list` to see virt-tests listed there.

That's it. Virt Test at this point has way too many knobs, and it's challenging to look to each of them and make sure they are working well. I hope that at least you guys enjoy trying this out.

Changes from v11:
* Dropped references to muxer in the multiplexer commit, and changed `avocado_mux_merge` to `avocado_inject_params`

Changes from v10:
* First version where the actual plugins are in a separate repo. Please refer to https://github.com/avocado-framework/avocado-vt/pull/1 to review that code. This PR only has the avocado relevant parts. Now this is aiming for inclusion. Let's do this, guys.

Changes from v9:
* Now the plugin honors the old virt test setting of `$AUTOTEST_PATH`, in case you want to use autotest from a git repo instead of from an RPM. In order to get consistency with that option, we changed `$VIRT_TEST_DIR` -> `$VIRT_TEST_PATH`.
* `avocado list --vt-guests`: Filter by guest list `i440fx`, which prevents issues with the `q35` variant not listing tests
* Set priority of test lister to be 0, to prevent issue when the virt test lister is loaded before the test lister: `virt_test_compat_lister': 'Parser' object has no attribute 'lister'`

Changes from v8:
* Finally the `avocado list` functionality is complete. You can list tests by `scripts/avocado list`, use `--vt-type` (different test types generate different test lists) and even list guests com `scripts/avocado --vt-list-guests` (different guests generate different test lists).

Changes from v7:
* Allow avocado list to show tests from all test loader plugins. This way, when enabled, virt-tests are displayed. There's one last thing lacking here, how to add new arguments to the lister plugin. I know how to do that for the runner plugin, I'll need @ruda's help to understand how to do it.

Changes from v6:
* Fixed bug running virt tests with multiplex file specified in the command line
* Added an avocado_params attribute to the virt test class of the plugin, allowing users to use 'frankenstein mode' - access avocado specific muliplexed params from inside virt-tests.
* Removed the aggressive error message when the virt plugin is not configured.

Changes from v5:
* Cleaned up the plugin code and adapted it to the refactorings I made on `virt-test`'s side.

Changes from v4:
 * Finally resolved the problem with loading multiple test sources, while keeping the base filesystem plugin working the way it usually does. With this, unittest hacks could be thrown away. Unfortunately, the overhead with the virt plugin enabled makes a couple of unittests to fail, but since the compat plugin is going to be on a separate project, that isn't a big problem per se. Now, I'm certain that there are ways to make the multiple test loading more efficient. Figuring it all out at once is not easy, though.

Changes from v3:
 * Removed the list and bootstrap plugins. virt-test can already do that functionality for the user.
 * Went to a excruciatingly detailed review of command line options. Many options that don't make sense in avocado were removed, text reviewed, and options grouped logically. Next step is to move unneeded options to the config file.

[1] See https://github.com/autotest/virt-test/pull/2208

### CODE REVIEW

**Comment by clebergnu** [comment]
Some of the instructions on this PR are now outdated:

```
3) The copy of virt-test has to be in my new branch avocado-integration-v4 [1]
4) Check out the avocado-vt repo, then merge PR 1 -> avocado-framework/avocado-vt#3. The code checked out has to be in the same base dir as your copy of avocado
```

But I think that's fine because that is not going to make into the repo anyway. Nevermind!

**Comment by lmr** [comment]
@clebergnu yeah, it turns out that after so many versions I end up forgetting to update things.

**Comment by clebergnu** [comment]
@lmr I understand that! I was just thinking out loud (and bothering you with that noise).

**Comment by clebergnu** [comment]
```
...
VT: 1881
```

That's a bunch of "new" tests! And it's merged!

**Pull request merged**
