### PR TITLE
utils.download: catches timeout errors and small fixes

### LINKED ISSUE #4829: assets fetch: handshake timeout it is not being caught
During investigation of #4824 I found a problem with timeout during handshake.

```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib64/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/usr/lib64/python3.7/http/client.py", line 1447, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/lib64/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/lib64/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1074: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib64/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/local/src/beraldo/avocado/avocado/utils/download.py", line 69, in download
    src_file = url_open(url, data=data)
  File "/home/local/src/beraldo/avocado/avocado/utils/download.py", line 46, in url_open
    result = urlopen(url, data=data, timeout=timeout)
  File "/usr/lib64/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib64/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.7/urllib/request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python3.7/urllib/request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error _ssl.c:1074: The handshake operation timed out>
Failed to fetch download ([Errno 2] No such file or directory: '/home/local/avocado/data/cache/by_location/4135b9170bbc2afc3ec7f79c169bf722b4d2afe7/download.cd7fe814-e6c0-4b10-82cd-e390d92fa099').
(avocado-py3.7) [local@laptop avocado]$ 
```

Probably this is related to 9b75f9d62faf53248fc687bd6e4dde85bb705b56, but I'm still investigating.

### PR DESCRIPTION
**Pull request by beraldoleal**
Even before my previous change on this method, url_open can raise
exceptions and we need to catch as soon as possible. We need to make
sure that errors here are logged. Fixes #4829.

Signed-off-by: Beraldo Leal <bleal@redhat.com>

### CODE REVIEW

**Comment by clebergnu** [comment]
@beraldoleal on the last commit, what do you mean by "handled by the upper layers"?  Will the error message be made available to the user as is? I'm missing that bit.

**Review by richtja — APPROVED** [review]
LGTM

**Comment by beraldoleal** [comment]
> @beraldoleal on the last commit, what do you mean by "handled by the upper layers"? Will the error message be made available to the user as is? I'm missing that bit.

It is an outdated description I will change.

**Comment by beraldoleal** [comment]
> > @beraldoleal on the last commit, what do you mean by "handled by the upper layers"? Will the error message be made available to the user as is? I'm missing that bit.
> 
> It is an outdated description I will change.

Fixed only the commit description.

**Review by willianrampazzo — APPROVED** [review]

**Review by clebergnu — APPROVED** [review]
LGTM, thanks!

**Comment by willianrampazzo** [comment]
> I'm a bit late here... but shouldn't it say "time out was reach**ed**"?

good catch! Looks like we need a new PR :D

**Pull request merged**
