### PR TITLE
Component Isolation: Linux Distribution Support

### PR DESCRIPTION
**Pull request by clebergnu**
Avocado has some planned features that depend on knowing the Linux Distribution being used on the system and knowing its details. Information such as all currently installed packages, the packages that ship with the distribution, packages that were added on top of the system and others are necessary for those planned features.

This PR brings in this kind of support, as another step towards the implementation of the Component Isolation grand feature.

### CODE REVIEW

**Comment by clebergnu** [comment]
@lmr or @ldoktor: This PR should be pretty obvious too, I'd also appreciate your review. Thanks!

**Comment by lmr** [comment]
I'm on it!

**Comment by lmr** [comment]
@clebergnu, that's some beautiful work going on right there. I am a little intrigued as to why the software manager module wasn't used, and also think there are small fixes here and there that can be made. Let me know what you think.

**Comment by lmr** [comment]
Another detail I've noticed playing with the plugin:

    $ git diff
    diff --git a/avocado/plugins/distro.py b/avocado/plugins/distro.py
    index e73cb74..37bba1e 100644
    --- a/avocado/plugins/distro.py
    +++ b/avocado/plugins/distro.py
    @@ -15,8 +15,10 @@
     import os
     import bz2
     import json
    +import sys
     
     from avocado.core import output
    +from avocado.core import exit_codes
     from avocado.plugins import plugin
     from avocado.utils import process
     from avocado.linux import distro as distro_utils
    @@ -349,6 +351,7 @@ class DistroOptions(plugin.Plugin):
                     error_msg = ('Required arguments: name, version, arch, type '
                                  'and path')
                     view.notify(event="error", msg=error_msg)
    +                sys.exit(exit_codes.AVOCADO_CRASH)
     
                 output_file_name = self.get_output_file_name(args)

**Comment by lmr** [comment]
Currently it keeps on working even though we had validation errors. The patch above is a fix for this behavior.

**Comment by clebergnu** [comment]
Closed in favor of #332.

**Pull request closed without merging**
