### PR TITLE
Output tweaks

### PR DESCRIPTION
**Pull request by lmr**
Implements the card

https://trello.com/c/NcxQk6tv/472-show-link-to-html-report-at-end-of-job-not-beginning

See the before/after each commit in the individual commit messages.

### CODE REVIEW

**Comment by adereis** [comment]
Cool! Remember to fix the documentation as well:

$ git grep 'JOB HTML' | wc -l
9

**Comment by ldoktor** [comment]
@adereis well, good point about the docmentation (actually given the fact the html output is a plugin, how about `sed '/JOB HTML/d'` everywhere except HTML plugin description?)

**Comment by adereis** [comment]
@ldoktor: we have this problem with documentation vs plugins *everywhere*. I think there's no point in addressing it exclusively in the case of the HTML plugin.

**Comment by lmr** [comment]
OK, so I did fix the documentation and made all examples look current.

**Comment by ldoktor** [comment]
--- /home/medic/a
+++ /home/medic/b
@@ -1,11 +1,11 @@
-docs/source/RunningTestsRemotely.rst:    (1/2) examples/tests/sleeptest.py: PASS (1.00 s)
-docs/source/RunningTestsRemotely.rst:    (1/2) examples/tests/sleeptest.py: PASS (1.00 s)
-docs/source/ResultFormats.rst:    (1/3) sleeptest.1: PASS (1.01 s)
-docs/source/GetStartedGuide.rst:    (1/1) /bin/true: PASS (0.01 s)
-docs/source/GetStartedGuide.rst:    (1/6) failtest.1: FAIL (0.00 s)
-docs/source/WritingTests.rst:    (1/3) sleeptest: PASS (0.50 s)
-docs/source/WritingTests.rst:    (1/8) sleeptest.py: PASS (1.00 s)
-docs/source/WritingTests.rst:    (1/1) synctest.py: PASS (2.20 s)
+docs/source/RunningTestsRemotely.rst:     (1/2) examples/tests/sleeptest.py: PASS (1.00 s)
+docs/source/RunningTestsRemotely.rst:     (1/2) examples/tests/sleeptest.py: PASS (1.00 s)
+docs/source/ResultFormats.rst:     (1/3) sleeptest.1: PASS (1.01 s)
+docs/source/GetStartedGuide.rst:     (1/1) /bin/true: PASS (0.01 s)
+docs/source/GetStartedGuide.rst:     (1/6) failtest.1: FAIL (0.00 s)
+docs/source/WritingTests.rst:     (1/3) sleeptest: PASS (0.50 s)
+docs/source/WritingTests.rst:     (1/8) sleeptest.py: PASS (1.00 s)
+docs/source/WritingTests.rst:     (1/1) synctest.py: PASS (2.20 s)
 docs/source/WritingTests.rst:    (1/1) home/$USER/Code/avocado/output_record.sh: PASS (0.01 s)
 docs/source/WritingTests.rst:    (1/1) home/$USER/Code/avocado/output_record.sh: FAIL (0.02 s)
 docs/source/WritingTests.rst:    (1/1) sleeptest.1: ERROR (2.97 s)

Still couple of them are missing...

**Comment by lmr** [comment]
Closing in favor of #770

**Pull request closed without merging**
