### PR TITLE
Allow multiple statuses on application exit code

### PR DESCRIPTION
**Pull request by clebergnu**
This implements the card described at:

https://trello.com/c/SU5fixgH/510-improve-job-statuses

### CODE REVIEW

**Comment by ldoktor** [comment]
OK, so this is just the ground work to define the statuses. I'm wondering whether it wont be better to merge this together with the patch which actually implements this, because this might be a bit confusing. People might expect the result to be eg. `\x5`, which is not yet supported.

**Comment by clebergnu** [comment]
This first PR doesn't intend to change the meaning or names of the exit codes.

I'm aware (should be right) that those names and meanings deserve some work. Even including words such as **JOB** doesn't make sense when we run, say, `$ avocado multiplex`, but those are currently used.

This is just foundation work that should bring no breakage, unless we have people wrapping the avocado command line app and depending on those results.

**Comment by ldoktor** [comment]
Then I agree with the cc6f939 and ab83081 (I love that one), but the d865c51 should be sent together with the PR which utilize it.

**Comment by clebergnu** [comment]
@ldoktor agreed!

**Comment by clebergnu** [comment]
Closing in favor of #861

**Pull request closed without merging**
