### PR TITLE
selftests tmp dir cleanup fix

### PR DESCRIPTION
**Pull request by richtja**
Some avocado selftests leave results in tmp directory. This is caused by wrong inheritance order when test class inherits from Test and TestCaseTmpDir classes. This PR fixes it.

Signed-off-by: Jan Richter <jarichte@redhat.com>

### CODE REVIEW

**Comment by clebergnu** [comment]
Looks good (simple and effective).  I'm just running a job [here](https://github.com/clebergnu/avocado/actions/runs/5312864164) to double-check it.

**Comment by richtja** [comment]
Hi @clebergnu, thanks for quick review. I added a small change which will enable the tmp dir check in our check.py script. With this change, we will have this check enabled in PR CI. Please take a look.

**Comment by clebergnu** [comment]
LGTM, and [pre-release tests](https://github.com/clebergnu/avocado/actions/runs/5350165076/jobs/9702400174) are happy!

**Review by clebergnu — APPROVED** [review]
LGTM, and [pre-release tests](https://github.com/clebergnu/avocado/actions/runs/5350165076/jobs/9702400174) are happy!

**Pull request merged**
