### PR TITLE
Revert pep420 changes

### PR DESCRIPTION
**Pull request by beraldoleal**
Those are the plugins that are not building properly with COPR builds. Because they are missing the __init__.py.
They are not breaking tests, but I decided to send this as "precaution" PR for discussion.

### CODE REVIEW

**Comment by ana** [comment]
when you say "COPR builds" you mean centos / rhel 8 right?

**Comment by beraldoleal** [comment]
> when you say "COPR builds" you mean centos / rhel 8 right?

Yes, they are CentOS / RHEL builds, but triggered by the "COPR build system" at `https://copr.fedorainfracloud.org/coprs/g/avocado/avocado-latest/package/python-avocado/`

**Comment by ana** [comment]
> > when you say "COPR builds" you mean centos / rhel 8 right?
> 
> Yes, they are CentOS / RHEL builds, but triggered by the "COPR build system" at `https://copr.fedorainfracloud.org/coprs/g/avocado/avocado-latest/package/python-avocado/`

My question was if this is only a problem in centos/rhel 8. From your link, I see this is the case. 
The problem here comes from RHEL8 having an old version from setuptools (< 40.6.3) that doesn't support PEP 420 properly, I tried bumping it here https://github.com/avocado-framework/avocado/pull/5186 but given we want avocado to work out of the box I tried the workaround you see in the `setup.py ` from the `optional_plugins`.
This was enought to fix the problem in eggs_task and version_task but not when building packages. We should add building the packages for rhel8 in the tests from packit to avoid this kid problem happening again.

**Comment by beraldoleal** [comment]
> > > when you say "COPR builds" you mean centos / rhel 8 right?
> > 
> > 
> > Yes, they are CentOS / RHEL builds, but triggered by the "COPR build system" at `https://copr.fedorainfracloud.org/coprs/g/avocado/avocado-latest/package/python-avocado/`
> 
> My question was if this is only a problem in centos/rhel 8. From your link, I see this is the case. The problem here comes from RHEL8 having an old version from setuptools (< 40.6.3) that doesn't support PEP 420 properly, I tried bumping it here #5186 but given we want avocado to work out of the box I tried the workaround you see in the `setup.py ` from the `optional_plugins`. This was enought to fix the problem in eggs_task and version_task but not when building packages. We should add building the packages for rhel8 in the tests from packit to avoid this kid problem happening again.

Yes, agreed that we should add the tests. In meanwhile, because of the release date and to avoid last minute fixes, maybe it is safer to revert them so we won time to properly fix this.

**Comment by clebergnu** [comment]
COPR packages on CentOS8 seem fine:

```
 dnf install python3-avocado{-plugins-varianter-cit,-plugins-varianter-yaml-to-mux.noarch} 
Last metadata expiration check: 0:11:26 ago on Wed Feb  9 15:27:36 2022.
Dependencies resolved.
=============================================================================================================================================================================================
 Package                                                Architecture    Version                                   Repository                                                            Size
=============================================================================================================================================================================================
Installing:
 python3-avocado-plugins-varianter-cit                  noarch          94.0-1.20220208git9ed852da5.el8           copr:copr.fedorainfracloud.org:group_avocado:avocado-latest           35 k
 python3-avocado-plugins-varianter-yaml-to-mux          noarch          94.0-1.20220208git9ed852da5.el8           copr:copr.fedorainfracloud.org:group_avocado:avocado-latest           32 k
Installing dependencies:
 binutils                                               x86_64          2.30-113.el8                              baseos                                                               5.8 M
 cpp                                                    x86_64          8.5.0-3.el8                               appstream                                                             10 M
 gc                                                     x86_64          7.6.4-3.el8                               appstream                                                            109 k
 gcc                                                    x86_64          8.5.0-3.el8                               appstream                                                             23 M
 gdb                                                    x86_64          8.2-18.el8                                appstream                                                            299 k
 gdb-headless                                           x86_64          8.2-18.el8                                appstream                                                            3.7 M
 glibc-devel                                            x86_64          2.28-167.el8                              baseos                                                               1.0 M
 glibc-headers                                          x86_64          2.28-167.el8                              baseos                                                               480 k
 guile                                                  x86_64          5:2.0.14-7.el8                            appstream                                                            3.5 M
 isl                                                    x86_64          0.16.1-6.el8                              appstream                                                            841 k
 kernel-headers                                         x86_64          4.18.0-358.el8                            baseos                                                               8.8 M
 libatomic_ops                                          x86_64          7.6.2-3.el8                               appstream                                                             38 k
 libbabeltrace                                          x86_64          1.5.4-3.el8                               baseos                                                               200 k
 libgomp                                                x86_64          8.5.0-3.el8                               baseos                                                               206 k
 libipt                                                 x86_64          1.6.1-8.el8                               appstream                                                             50 k
 libmpc                                                 x86_64          1.1.0-9.1.el8                             appstream                                                             61 k
 libpkgconf                                             x86_64          1.4.2-1.el8                               baseos                                                                35 k
 libtool-ltdl                                           x86_64          2.4.6-25.el8                              baseos                                                                58 k
 libxcrypt-devel                                        x86_64          4.1.1-6.el8                               baseos                                                                25 k
 pkgconf                                                x86_64          1.4.2-1.el8                               baseos                                                                38 k
 pkgconf-m4                                             noarch          1.4.2-1.el8                               baseos                                                                17 k
 pkgconf-pkg-config                                     x86_64          1.4.2-1.el8                               baseos                                                                15 k
 procps-ng                                              x86_64          3.3.15-6.el8                              baseos                                                               329 k
 python3-avocado                                        noarch          94.0-1.20220208git9ed852da5.el8           copr:copr.fedorainfracloud.org:group_avocado:avocado-latest          654 k
 python3-avocado-common                                 noarch          94.0-1.20220208git9ed852da5.el8           copr:copr.fedorainfracloud.org:group_avocado:avocado-latest           32 k
 python3-pyyaml                                         x86_64          3.12-12.el8                               baseos                                                               193 k
Installing weak dependencies:
 dnf-plugins-core                                       noarch          4.0.21-3.el8                              baseos                                                                70 k
 gcc-gdb-plugin                                         x86_64          8.5.0-3.el8                               appstream                                                            118 k

Transaction Summary
=============================================================================================================================================================================================
Install  30 Packages

...

# avocado plugins | grep varianter
dict_variants Python Dictionary based varianter
json_variants JSON serialized based varianter initialization
varianter_cit CIT Varianter options for the 'run' subcommand
Plugins that generate test variants (varianter): 
dict_variants Python Dictionary based varianter
varianter_cit CIT Varianter

...

# avocado run --cit-parameter-file=params.cit /bin/true 
JOB ID     : eb3ed1591735a13ab90d251361c6c41ff09a866c
JOB LOG    : /root/avocado/job-results/job-2022-02-09T15.40-eb3ed15/job.log
 (02/28) /bin/true;red-triangle-liquid-plastic-cathodic-7-1-1-4: STARTED
 (01/28) /bin/true;black-circle-solid-leather-anodic-1-1-5-1: STARTED
 (04/28) /bin/true;green-square-liquid-aluminum-cathodic-5-1-2-5: STARTED
 (02/28) /bin/true;red-triangle-liquid-plastic-cathodic-7-1-1-4: PASS (0.01 s)
 (01/28) /bin/true;black-circle-solid-leather-anodic-1-1-5-1: PASS (0.01 s)
 (03/28) /bin/true;green-square-solid-aluminum-cathodic-1-3-1-3: STARTED
 (04/28) /bin/true;green-square-liquid-aluminum-cathodic-5-1-2-5: PASS (0.01 s)
 (03/28) /bin/true;green-square-solid-aluminum-cathodic-1-3-1-3: PASS (0.01 s)
 (08/28) /bin/true;gold-triangle-gas-plastic-anodic-1-2-4-4: STARTED
 (05/28) /bin/true;black-circle-gas-plastic-cathodic-7-2-2-3: STARTED
 (08/28) /bin/true;gold-triangle-gas-plastic-anodic-1-2-4-4: PASS (0.01 s)
 (06/28) /bin/true;green-circle-gas-aluminum-cathodic-7-4-4-1: STARTED
 (05/28) /bin/true;black-circle-gas-plastic-cathodic-7-2-2-3: PASS (0.01 s)
 (06/28) /bin/true;green-circle-gas-aluminum-cathodic-7-4-4-1: PASS (0.01 s)
 (07/28) /bin/true;black-circle-liquid-aluminum-cathodic-6-5-4-3: STARTED
 (07/28) /bin/true;black-circle-liquid-aluminum-cathodic-6-5-4-3: PASS (0.01 s)
 (09/28) /bin/true;black-circle-liquid-aluminum-cathodic-3-4-1-2: STARTED
 (10/28) /bin/true;red-triangle-liquid-leather-cathodic-5-4-5-3: STARTED
 (09/28) /bin/true;black-circle-liquid-aluminum-cathodic-3-4-1-2: PASS (0.01 s)
 (10/28) /bin/true;red-triangle-liquid-leather-cathodic-5-4-5-3: PASS (0.01 s)
 (12/28) /bin/true;gold-triangle-solid-plastic-anodic-6-3-5-2: STARTED
 (13/28) /bin/true;green-square-solid-leather-cathodic-5-2-4-2: STARTED
 (12/28) /bin/true;gold-triangle-solid-plastic-anodic-6-3-5-2: PASS (0.01 s)
 (14/28) /bin/true;gold-square-liquid-plastic-anodic-5-5-1-1: STARTED
 (11/28) /bin/true;red-circle-gas-leather-cathodic-3-3-4-5: STARTED
 (13/28) /bin/true;green-square-solid-leather-cathodic-5-2-4-2: PASS (0.01 s)
 (14/28) /bin/true;gold-square-liquid-plastic-anodic-5-5-1-1: PASS (0.01 s)
 (11/28) /bin/true;red-circle-gas-leather-cathodic-3-3-4-5: PASS (0.01 s)
 (15/28) /bin/true;gold-triangle-solid-leather-anodic-7-5-5-5: STARTED
 (15/28) /bin/true;gold-triangle-solid-leather-anodic-7-5-5-5: PASS (0.01 s)
 (16/28) /bin/true;gold-square-solid-plastic-anodic-3-1-3-3: STARTED
 (16/28) /bin/true;gold-square-solid-plastic-anodic-3-1-3-3: PASS (0.01 s)
 (17/28) /bin/true;green-triangle-gas-leather-cathodic-3-5-3-4: STARTED
 (17/28) /bin/true;green-triangle-gas-leather-cathodic-3-5-3-4: PASS (0.01 s)
 (18/28) /bin/true;red-triangle-gas-leather-anodic-1-5-2-2: STARTED
 (18/28) /bin/true;red-triangle-gas-leather-anodic-1-5-2-2: PASS (0.01 s)
 (20/28) /bin/true;black-circle-liquid-leather-cathodic-5-3-3-4: STARTED
 (22/28) /bin/true;green-square-solid-aluminum-anodic-3-3-2-1: STARTED
 (19/28) /bin/true;gold-circle-liquid-plastic-anodic-1-4-3-5: STARTED
 (20/28) /bin/true;black-circle-liquid-leather-cathodic-5-3-3-4: PASS (0.01 s)
 (22/28) /bin/true;green-square-solid-aluminum-anodic-3-3-2-1: PASS (0.01 s)
 (19/28) /bin/true;gold-circle-liquid-plastic-anodic-1-4-3-5: PASS (0.01 s)
 (21/28) /bin/true;red-triangle-liquid-aluminum-anodic-6-2-3-1: STARTED
 (21/28) /bin/true;red-triangle-liquid-aluminum-anodic-6-2-3-1: PASS (0.01 s)
 (23/28) /bin/true;green-square-gas-aluminum-cathodic-3-2-5-4: STARTED
 (24/28) /bin/true;black-circle-gas-leather-cathodic-6-1-1-5: STARTED
 (23/28) /bin/true;green-square-gas-aluminum-cathodic-3-2-5-4: PASS (0.01 s)
 (24/28) /bin/true;black-circle-gas-leather-cathodic-6-1-1-5: PASS (0.01 s)
 (26/28) /bin/true;red-square-solid-leather-cathodic-7-3-3-2: STARTED
 (25/28) /bin/true;green-square-gas-plastic-cathodic-5-1-4-2: STARTED
 (26/28) /bin/true;red-square-solid-leather-cathodic-7-3-3-2: PASS (0.01 s)
 (25/28) /bin/true;green-square-gas-plastic-cathodic-5-1-4-2: PASS (0.01 s)
 (27/28) /bin/true;gold-square-solid-plastic-anodic-6-4-2-4: STARTED
 (27/28) /bin/true;gold-square-solid-plastic-anodic-6-4-2-4: PASS (0.01 s)
 (28/28) /bin/true;green-square-gas-leather-cathodic-6-2-1-5: STARTED
 (28/28) /bin/true;green-square-gas-leather-cathodic-6-2-1-5: PASS (0.01 s)
RESULTS    : PASS 28 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 15.26 s
```

So I don't thinks is **needed** for the release.

**Comment by beraldoleal** [comment]
Thanks @clebergnu for double checking this.

**Pull request closed without merging**
