### PR TITLE
selftests/deployment: Using Ansible' roles features

### PR DESCRIPTION
**Pull request by beraldoleal**
The current playbook layout was not following the Ansible best practices
for playbooks. This small refactoring uses roles to improve the
organization of playbooks and facilitate future reuse. It was introduced
two variables: `method` and `avocado_vt` to control the execution flow.

This is just a suggestion. Let me know if you guys aren't ok with this new
layout and execution model.

### CODE REVIEW

**Comment by clebergnu** [comment]
On Fedora 31, when running `ansible-playbook -i inventory -c local deployment.yml -e "avocado_vt=true method=copr"`, I'd expect the following task to be skipped:

```
TASK [common : Avocado EPEL Copr repo] ***********************************************************************************************************
changed: [localhost]
```

And there's a duplicate task name here... are they different?

```
TASK [common : Avocado-VT Copr repo] *************************************************************************************************************
skipping: [localhost]

TASK [common : Avocado-VT Copr repo] *************************************************************************************************************
changed: [localhost]
```

And then this one fails:

```
TASK [avocado : Install Avocado plugins available on Fedora only] ********************************************************************************
failed: [localhost] (item=python3-avocado-plugins-runner-remote) => {"ansible_loop_var": "item", "changed": false, "failures": [], "item": "python3-avocado-plugins-runner-remote", "msg": "Depsolve Error occured: \n Problem: conflicting requests\n  - nothing provides python3-fabric3 needed by python3-avocado-plugins-runner-remote-67.0-1.20190211gitcd4fdd51.fc30.noarch\n  - nothing provides python3-avocado = 67.0 needed by python3-avocado-plugins-runner-remote-67.0-1.20190211gitcd4fdd51.fc30.noarch\n  - nothing provides python3.7dist(fabric3) >= 1.1.4 needed by python3-avocado-plugins-runner-remote-67.0-1.20190211gitcd4fdd51.fc30.noarch\n  - nothing provides python3.7dist(fabric3) < 2.0.0 needed by python3-avocado-plugins-runner-remote-67.0-1.20190211gitcd4fdd51.fc30.noarch", "rc": 1, "results": []}
failed: [localhost] (item=python3-avocado-plugins-runner-vm) => {"ansible_loop_var": "item", "changed": false, "failures": [], "item": "python3-avocado-plugins-runner-vm", "msg": "Depsolve Error occured: \n Problem: conflicting requests\n  - nothing provides python3-avocado = 67.0 needed by python3-avocado-plugins-runner-vm-67.0-1.20190211gitcd4fdd51.fc30.noarch", "rc": 1, "results": []}
```

Which makes me believe that we should not try to install `python3-avocado-plugins-runner-remote` and `python3-avocado-plugins-runner-vm` on Fedora 31.

**Comment by beraldoleal** [comment]
> On Fedora 31, when running `ansible-playbook -i inventory -c local deployment.yml -e "avocado_vt=true method=copr"`, I'd expect the following task to be skipped:
> 
> ```
> TASK [common : Avocado EPEL Copr repo] ***********************************************************************************************************
> changed: [localhost]
> ```

Yes, fixed on v2.

> And there's a duplicate task name here... are they different?
> 
> ```
> TASK [common : Avocado-VT Copr repo] *************************************************************************************************************
> skipping: [localhost]
> 
> TASK [common : Avocado-VT Copr repo] *************************************************************************************************************
> changed: [localhost]
> ```

Yes, they are different, just renamed the task name on v2.

> And then this one fails:
> 
> ```
> TASK [avocado : Install Avocado plugins available on Fedora only] ********************************************************************************
> failed: [localhost] (item=python3-avocado-plugins-runner-remote) => {"ansible_loop_var": "item", "changed": false, "failures": [], "item": "python3-avocado-plugins-runner-remote", "msg": "Depsolve Error occured: \n Problem: conflicting requests\n  - nothing provides python3-fabric3 needed by python3-avocado-plugins-runner-remote-67.0-1.20190211gitcd4fdd51.fc30.noarch\n  - nothing provides python3-avocado = 67.0 needed by python3-avocado-plugins-runner-remote-67.0-1.20190211gitcd4fdd51.fc30.noarch\n  - nothing provides python3.7dist(fabric3) >= 1.1.4 needed by python3-avocado-plugins-runner-remote-67.0-1.20190211gitcd4fdd51.fc30.noarch\n  - nothing provides python3.7dist(fabric3) < 2.0.0 needed by python3-avocado-plugins-runner-remote-67.0-1.20190211gitcd4fdd51.fc30.noarch", "rc": 1, "results": []}
> failed: [localhost] (item=python3-avocado-plugins-runner-vm) => {"ansible_loop_var": "item", "changed": false, "failures": [], "item": "python3-avocado-plugins-runner-vm", "msg": "Depsolve Error occured: \n Problem: conflicting requests\n  - nothing provides python3-avocado = 67.0 needed by python3-avocado-plugins-runner-vm-67.0-1.20190211gitcd4fdd51.fc30.noarch", "rc": 1, "results": []}
> ```
> 
> Which makes me believe that we should not try to install `python3-avocado-plugins-runner-remote` and `python3-avocado-plugins-runner-vm` on Fedora 31.

I'm thinking out loud... Ideally, this should be working on all distros, right? So maybe have it there and just leave failing could be helpful for us to fix something. We can have the task as FAILED and a note saying why is failing with some comment like "safe to ignore because of blabababl.".  What do you think?

**Comment by clebergnu** [comment]
> @clebergnu my comments bellow:
> 
> > On Fedora 31, when running `ansible-playbook -i inventory -c local deployment.yml -e "avocado_vt=true method=copr"`, I'd expect the following task to be skipped:
> > ```
> > TASK [common : Avocado EPEL Copr repo] ***********************************************************************************************************
> > changed: [localhost]
> > ```
> 
> Yes, fixed on v2.
> 
> > And there's a duplicate task name here... are they different?
> > ```
> > TASK [common : Avocado-VT Copr repo] *************************************************************************************************************
> > skipping: [localhost]
> > 
> > TASK [common : Avocado-VT Copr repo] *************************************************************************************************************
> > changed: [localhost]
> > ```
> 
> Yes, they are different, just renamed the task name on v2.
> 
> > And then this one fails:
> > ```
> > TASK [avocado : Install Avocado plugins available on Fedora only] ********************************************************************************
> > failed: [localhost] (item=python3-avocado-plugins-runner-remote) => {"ansible_loop_var": "item", "changed": false, "failures": [], "item": "python3-avocado-plugins-runner-remote", "msg": "Depsolve Error occured: \n Problem: conflicting requests\n  - nothing provides python3-fabric3 needed by python3-avocado-plugins-runner-remote-67.0-1.20190211gitcd4fdd51.fc30.noarch\n  - nothing provides python3-avocado = 67.0 needed by python3-avocado-plugins-runner-remote-67.0-1.20190211gitcd4fdd51.fc30.noarch\n  - nothing provides python3.7dist(fabric3) >= 1.1.4 needed by python3-avocado-plugins-runner-remote-67.0-1.20190211gitcd4fdd51.fc30.noarch\n  - nothing provides python3.7dist(fabric3) < 2.0.0 needed by python3-avocado-plugins-runner-remote-67.0-1.20190211gitcd4fdd51.fc30.noarch", "rc": 1, "results": []}
> > failed: [localhost] (item=python3-avocado-plugins-runner-vm) => {"ansible_loop_var": "item", "changed": false, "failures": [], "item": "python3-avocado-plugins-runner-vm", "msg": "Depsolve Error occured: \n Problem: conflicting requests\n  - nothing provides python3-avocado = 67.0 needed by python3-avocado-plugins-runner-vm-67.0-1.20190211gitcd4fdd51.fc30.noarch", "rc": 1, "results": []}
> > ```
> > 
> > 
> > Which makes me believe that we should not try to install `python3-avocado-plugins-runner-remote` and `python3-avocado-plugins-runner-vm` on Fedora 31.
> 
> I'm thinking out loud... Ideally, this should be working on all distros, right? So maybe have it there and just leave failing could be helpful for us to fix something. We can have the task as FAILED and a note saying why is failing with some comment like "safe to ignore because of blabababl.". What do you think?

I'm happy with a "KNOWN FAILURE" kind of approach in this case.

**Comment by clebergnu** [comment]
About the dependencies:

```
TASK [common : Install Basic Depedencies on Red Hat (like) systems] ******************************************************************************
changed: [localhost] => (item=python3-pip)
ok: [localhost] => (item=git)
```

`python3-pip` is not a dependency that we should install manually in a `method=official` or `method=copr`.  `git` is a different thing, because it's not an Avocado-VT explicit RPM requirement (but should probably be). Still, `git` should only be needed when `avocado_vt=true`.

**Comment by beraldoleal** [comment]
Just sent a v2.

**Pull request closed without merging**
