### PR TITLE
 Method modification for obtaining container information

### PR DESCRIPTION
**Pull request by ut003460**
1.Exception message improvement
Change the f "Failed getting information about container:" f "{container_id}." that concatenates two strings together to a single string to avoid unnecessary string concatenation 
2.Replace container ["Id"] with container. get ("Id") to avoid throwing KeyError when the "Id" key is missing in the dictionary

### CODE REVIEW

**Review by clebergnu — COMMENTED** [review]
Hi @ut003460 ,

Thanks for this.  The changes look good, but even though they're close together in the code, they are unrelated.  Could you please break this down into 2 separate commits?

Thanks.

**Comment by ut003460** [comment]
> 嗨，
> 
> 谢谢你。这些更改看起来不错，但即使它们在代码中很接近，它们也是不相关的。你能把它分解成两个单独的提交吗？
> 
> 谢谢。

Okay, thank you for your suggestion. I have resubmitted it

**Comment by richtja** [comment]
> Okay, thank you for your suggestion. I have resubmitted it

Hi @ut003460, is there any reason for removing your changes instead of splitting them into two commits as @clebergnu proposed?

**Comment by ut003460** [comment]
> > Okay, thank you for your suggestion. I have resubmitted it
> 
> Hi @ut003460, is there any reason for removing your changes instead of splitting them into two commits as @clebergnu proposed?

Okay, I don't quite understand what you mean. Can you explain it more specifically

**Comment by ut003460** [comment]
> > Okay, thank you for your suggestion. I have resubmitted it
> 
> Hi @ut003460, is there any reason for removing your changes instead of splitting them into two commits as @clebergnu proposed?

Okay, maybe I misunderstood. Could you please check if this submission is correct?

**Review by richtja — APPROVED** [review]
Hi @ut003460, it LGTM, thank you. Unfortunately, we are in feature-free state now. Therefore, your PR will be merged after the release planed on June 28

**Pull request merged**
