### PR TITLE
Run: allow references from config

### PR DESCRIPTION
**Pull request by clebergnu**
When integrating Avocado into existing test suites, it can make sense to provide the list of test references in a configuration file.
This allows users to simply do:

```    
$ avocado --config=.avocado.config run
```

This is a first step towards enabling Avocado to also read configuration on de-facto project files, such as `setup.cfg` and/or `pyproject.toml`, so that users could simply do `avocado run`.
    
If the project contains the valid configuration files. This is from a QEMU use case that can be seen here: https://gitlab.com/cleber.gnu/qemu/-/commit/a23cd906b8f4a916427d81c4f1eea46be4e24717#note_573824472

### CODE REVIEW

**Review by willianrampazzo — APPROVED** [review]
Tested! Works as expected.

**Review by beraldoleal — APPROVED** [review]
LGTM

**Comment by pevogam** [comment]
Hi @clebergnu, I guess this feature would be documented at a later stage when there is toml and other support?

**Comment by clebergnu** [comment]
> Hi @clebergnu, I guess this feature would be documented at a later stage when there is toml and other support? Just making sure when new switches are introduced there are at least Kanban cards about documenting them for the wider public, nothing necessarily now.

Yes, absolutely.  The current use case for this is simply allowing what should not have been prevented in the first place (it was a bit of a bug/technical debt).  We tried to use a configuration file and everything else but the test references worked.

Now the `pyproject.toml` idea is indeed a brand new feature and should be treated as such.

**Pull request merged**
