### PR TITLE
future.settings: remove config templates

### PR DESCRIPTION
**Pull request by beraldoleal**
Since that we are using the new register option API and default values are
defined inside the source code at registration time, config files can be empty.
avocado config reference will print a list of all supported options. This will
reduce the number of places to update the documentation strings.

Reference: https://github.com/avocado-framework/avocado/issues/3654
Signed-off-by: Beraldo Leal <bleal@redhat.com>

### CODE REVIEW

**Comment by beraldoleal** [comment]
@clebergnu This seems to be related to the `core/enabled_extension_manager.py` that @willianrampazzo it is still working. So maybe after his PR this will pass.

**Comment by willianrampazzo** [comment]
> @clebergnu This seems to be related to the `core/enabled_extension_manager.py` that @willianrampazzo it is still working. So maybe after his PR this will pass.

You can't imagine the headache `core/enabled_extension_manager.py` is giving me ;)

**Comment by clebergnu** [comment]
@beraldoleal maybe rebase this now?

**Comment by beraldoleal** [comment]
@clebergnu @willianrampazzo I'm closing this and moving the commit to #3931 . It looks like that settings.py needs the template files.

**Pull request closed without merging**
