### PR TITLE
Method _update_zip_extra_attrs optimization

### PR DESCRIPTION
**Pull request by faker-king**
Method _update_zip_extra_attrs optimization:
1. Remove excess assignments from dst
2. handle exceptions in adding files

### CODE REVIEW

**Review by richtja — CHANGES_REQUESTED** [review]
Hi @faker-king your changes LGTM, thank you for your contribution. Can you please update your commit message to not have your signature in the title. Something like this:

```
Method _update_zip_extra_attrs optimization

Signed-off-by: mataotao <mataotao@uniontech.com>
```

It will be better for future search through commit history. Thank you.

**Comment by faker-king** [comment]
> Thank

**Comment by faker-king** [comment]
Hi @richtja, If there are no issues, can this modification be incorporated

**Review by richtja — APPROVED** [review]
Hi @faker-king, it LGTM now. Thank you.

**Pull request merged**
