### PR TITLE
utils.cpu: fixed cpu family when 2964 - z13

### PR DESCRIPTION
**Pull request by beraldoleal**
Also raising NotImplemented when other families, not only arm.

Signed-off-by: Beraldo Leal <bleal@redhat.com>

### CODE REVIEW

**Review by willianrampazzo — APPROVED** [review]

**Comment by PaulYuuu** [comment]
Hello @beraldoleal, in view of the introduction of `FamilyException`, can you help update https://github.com/avocado-framework/avocado/blob/e97540793998c4f24a16000465dd7fdd213bf2b9/avocado/utils/cpu.py#L195-L196 and https://github.com/avocado-framework/avocado/blob/e97540793998c4f24a16000465dd7fdd213bf2b9/avocado/utils/cpu.py#L205-L206 as well?

**Comment by yanan-fu** [comment]
@beraldoleal  I agree with @PaulYuuu , we can apply it with all `logging.warning`.

**Comment by beraldoleal** [comment]
@PaulYuuu, @yanan-fu, sure no problem. Yes, makes sense. Just force-pushed here. Please review.

**Review by PaulYuuu — APPROVED** [review]

**Comment by PaulYuuu** [comment]
Thank you @beraldoleal

**Review by yanan-fu — APPROVED** [review]
Ack

**Pull request merged**
