### PR TITLE
nrunner: introduces the FancyDots() UI output matrix

### PR DESCRIPTION
**Pull request by beraldoleal**
This is an experiment with an alternative "task progress" by using a matrix of dots. Because of the nrunner distributed architecture and the current output list of tests, it is difficult to have an overview of how much of the tasks are completed. This matrix attempts to give us this visibility.

If you would like to view how is the output, visit: https://imgur.com/a/gTCuRAh

### CODE REVIEW

**Comment by willianrampazzo** [comment]
`FancyDots` WONDERFUL!

**Comment by clebergnu** [comment]
This is super cool @beraldoleal !!!

**Comment by pevogam** [comment]
Makes the parallel test runner even more attractive :)

**Comment by clebergnu** [comment]
@beraldoleal we all LOVED this experiment.  Now, we have to decide where it fits.  With `avocado nrun` getting removed *very soon* (fingers crossed), this may need a few extra cycles to fit in well into `avocado run` or a command of its own.

Do you think this should be pushed to post-LTS?

**Comment by beraldoleal** [comment]
yes, lets move this to post-lts.

**Comment by clebergnu** [comment]
@beraldoleal given that `avocado/plugins/nrun.py` is no more, I'm closing this PR, but let's not close the page on this idea.  We can/should discuss how to integrate this into the `avocado run --test-runner=nrunner` use case.

**Pull request closed without merging**
