### PR TITLE
contrib: Add avocado-check-pr script to do incremental check

### PR DESCRIPTION
**Pull request by ldoktor**
This script can be used after one merges a PR to verify __all__ the
commits pass `make check` and publishes the results to github.

Demonstration can be tested on https://github.com/avocado-framework/avocado/pull/2242 (please, do so, I'm wondering how second review from different user will look like)

### CODE REVIEW

**Comment by apahim** [comment]
You mean "before one merges a PR", right? Before the upstream merge...

**Comment by ldoktor** [comment]
Depends on the point of view. The workflow is you merge PR into your local branch, then you run this check and after that you push it to remote upstream... So in my view it's after merge.

**Comment by clebergnu** [comment]
Looks like my (current) workflow is similar to Amador's.  I think we can tweak it so that it compares the current branch (not merged, but rebased on top of origin/master) to origin/master, and run the checks *before* the local merge.

**Comment by ldoktor** [comment]
that would require specifying the target branch all the time (we might want to push to 36lts, ...) and it'd only check the current version, not the actual merge that will be pushed (which can be outdated in both versions, but having it just before push should be closer to the actual merged version)

**Comment by clebergnu** [comment]
About the target branch, we can always assume `master` as the default and override it.  The commit ids should not change before/after the merge (as long as they're kept with the same base on the tree), so the test of the *merge* commit itself, IMO, doesn't mean anything (unless it solves conflicts, etc).

Anyway, I feel weird when my local master branch has content that I'm not sure I want to push to origin/master... and a single `git push` may mistakenly do so.  So, I'll probably need the tweak.  If you feel like doing it, great, if not, I can try it out!

Thanks anyway, this script is going to be really helpful!

**Comment by ldoktor** [comment]
Sure, if changes are necessary (likely) I'll include it in v2...

**Comment by ldoktor** [comment]
[Deal with Travis-CI limitation of maximum job run time](https://trello.com/c/XYCSVroc/1071-deal-with-travis-ci-limitation-of-maximum-job-run-time)

**Comment by apahim** [comment]
Yes, agreed with @clebergnu . And this script fails for my workflow. My worflow (automated by scripts) is:

Example with PR: https://github.com/avocado-framework/avocado/pull/2242
```bash
$ git fetch https://github.com/ldoktor/avocado.git incremental-check
$ git checkout FETCH_HEAD
$ git checkout -b ldoktor-incremental-check # branch will be used to merge the PR
$ git checkout -b ldoktor-incremental-check-test # branch used to rebase/test the PR
$ git fetch upstream
$ git rebase upstream/master
$ make check-full

<review, test, hack, verify, ...>

$ git checkout master
$ git pull upstream master # upstream is the official repository
$ git merge -S --no-ff ldoktor-incremental-check -m "Merge branch 'ldoktor-incremental-check'" -m "Signed-off-by: $(git config --get user.name) <$(git config --get user.email)>"
$ git push upstream master
```

I will use this script for sure to replace my `make check-full` step, but I will not merge the PR on local `master` before I'm 100% sure it's ready for that.

**Comment by apahim** [comment]
For reference:
Review: https://gist.github.com/apahim/6e33ddd6257c7628e084f3b04cab9d6a
Merge: https://gist.github.com/apahim/80487e951c71f3acb3632a375b30b69b

**Pull request closed without merging**
