### PR TITLE
Test API: Isolate avocado.linux from being used by test developers.

### PR DESCRIPTION
**Pull request by ruda**
Move avocado.linux.distro to avocado.core.distro,
avocado.linux.software_manager to avocado.core.software_manager,
avocado.linux.kernel_build to avocado.utils.kernel_build,
in conformance to our purpose of keeping things not related
to test developers, inside avocado.core, isolated from users.

### CODE REVIEW

**Comment by clebergnu** [comment]
@ruda I have the feeling that both `distro` and `software_manager` at least in part are APIs that we want to give users.

Examples:

```
from avocado.linux import distro
...
   def test_distro_specific(self):
      mydistro = distro.detect()
      if distro.name == 'fedora':
         <do_something>
```

Also

```
from avocado.linux.software_manager import install_distro_packages

packages = {
   'fedora': 'kernel',
   'debian': 'linux-image'
}
...
   def test_install_kernel(self):
      ...
      install_distro_packages(packages)
      ...
```

These examples seem to make a lot of sense for tests. I mean, it's easier to move most stuff to `avocado.core`, but, by doing that we weaken our API and provide less value.

Let me know what you think.

**Comment by lmr** [comment]
OK guys, I'm on vacation, but I happened to see this.

I agree with @clebergnu. This part of the API should be available for users.

**Comment by ruda** [comment]
I'm going to check if it makes sense to split these modules (core API and test api) or just leave it the way it were.

**Comment by ruda** [comment]
OK, let's leave the way it are now.

**Pull request closed without merging**
