### PR TITLE
Update the CmdError output

### PR DESCRIPTION
**Pull request by hsmj1412**
The CmdError could not print the right error message now

Signed-off-by: Junxiang Li <junli@redhat.com>

### CODE REVIEW

**Comment by clebergnu** [comment]
@hsmj1412 thanks for sending this PR.  It made me think about a few issues described here:

https://trello.com/c/O4UNuhAP/1352-check-if-cmderror-exception-needs-command-and-additionaltext

About doing `__str__()` on `CmdError`, and consequently on `CmdResult..std{out,err}_text`, I have mixed feelings about it because:
 * I can see the usefulness of printing the `CmdError` and having the command output/error
 * While handling the `CmdError` exception, printing it, `CmdResult.std{out,err}_text`, *can* raise `TypeError` making things more confusing

IMO, while handling exceptions, we should try to be on the safest side possible.  What do you think about being "more honest" about the command output and using the raw `stdout` and `stderr` instead? It should give the same (or depending on how you see it, better with no decoding) level of information for debugging purposes.

**Comment by hsmj1412** [comment]
@clebergnu 
Hi Cleber,
I sent this PR because it is not work now.
In Python 3:
The output is : "CmdError: ('gluster volume start gluster-vol1', avocado.utils.process.CmdResult object at 0x7f41e8898ba8)"
And in Python 2:
The output is worse : "CmdError: "
We could not get any useful info from these output now.

**Comment by ldoktor** [comment]
Well I like this idea and I myself proposed similar representation to `CmdResult` in https://github.com/avocado-framework/avocado/pull/2690/commits/5935d5e94637586512901b78deb2f6b844ddd7a0 anyway I also agree with Cleber that decoding might be dangerous. How about the same approach as I made with CmdResult and simply report raw `stdout` and `stderr`, which should work well and one can simply copy&paste it into python interpreter and decode it using the stored encoding (or modify it in case it's incorrect).

Actually even simpler would be to wait for that PR to be merged and then simply report `Command %s failed:\n%s" % (self.command, self.result)`.

**Comment by ldoktor** [comment]
Would you please update the PR to use `"Command %s failed:\n%s" % (self.command, self.result)"`? It should work even now but reporting useless information, but once that other PR is merged it should actually provide very nice details.

**Comment by clebergnu** [comment]
@hsmj1412  given that there's been no update to this PR, I'm closing this one, and waiting for a new version with the changes requested. Thanks!

**Pull request closed without merging**
