### PR TITLE
BUG/documentation: setting wrappers for specific binaries do not work [V2]

### PR DESCRIPTION
**Pull request by ruda**
Changes from PR #679 

* Fix typo (specify/specifies)
* Don't escape * , since we're bash-centric.
* Adjustments in commit messages.

### CODE REVIEW

**Comment by clebergnu** [comment]
I'm on this one.

**Comment by clebergnu** [comment]
@ruda there's just one or two very simple things about this PR. If you feel they are OK, let me know and I can merge a v+=1 of this one. Thanks!

**Comment by clebergnu** [comment]
LGTM. Merged. Thanks @ruda !

**Comment by ruda** [comment]
Thanks @clebergnu !

**Pull request merged**
