### PR TITLE
Added exception handling for OSError that may be thrown by os.read

### PR DESCRIPTION
**Pull request by faker-king**
Added exception handling for OSError that may be thrown by os.read

### CODE REVIEW

**Comment by faker-king** [comment]
hi @richtja, Can you help me see if I can merge the code

**Review by richtja — COMMENTED** [review]
Hi @faker-king, thanks for your contribution. Even though your change is correct, I am not sure about it. IMO, it decreases readability of the code without any additional benefits, but maybe I am missing something here. Can you please help me to understand how your change is avoiding triggering errors? Thank you.

**Comment by faker-king** [comment]
Hi @richtja, Thank you for your feedback. I have carefully considered it and there is indeed no problem with what you said. It has reduced the readability of the code. I have now made a new modification and would appreciate it if you could double check it.

**Review by richtja — APPROVED** [review]
Hi @faker-king this change LGTM. We are right now in feature freeze state and we are doing pre-release testing, therefore this PR will be merged after the release planed on Friday June 28.

**Comment by faker-king** [comment]
Hi @richtja, I have found that the error in the codeclimate was not caused by my modifications. Could you please help me identify the reason for this

**Comment by richtja** [comment]
> Hi @richtja, I have found that the error in the codeclimate was not caused by my modifications. Could you please help me identify the reason for this

Hi @faker-king, don't worry about the codeclimate error. We are facing some issues with codeclimate these days.

**Pull request merged**
