### PR TITLE
avocado.test: Add support for params with paths [v2]

### PR DESCRIPTION
**Pull request by ldoktor**
Hi guys,

this pull request finally adds tech-preview for params with namespaces/paths. By default it acts like the old Params and is 97% compatible with the old code (read exception in the last commit). Anyway you can utilize the new API by special get calls, ex:

```python
#!/usr/bin/python

from avocado import job
from avocado import test


class PassTest(test.Test):

    """
    Example test that passes.
    """

    def runTest(self):
        """
        A test simply doesn't have to fail in order to pass
        """
        self.log.info(str(self.params))
        self.params.get('test', 'type/leaf1/')
        self.params.get('aaa', path='type/', default='my_default')
        self.params.get('test', path='*')
        try:
            self.params.get('test', path='/test/*')
        except Exception, details:
            self.log.info("Unable to obtain 'test' from /test/*: %s", details)
        self.params.get('test', path='/')
        try:
            self.params.get('test', path='/*')
        except Exception, details:
            self.log.info("Unable to obtain 'test' from '/*': %s", details)


if __name__ == "__main__":
    job.main()
```

v1: https://github.com/avocado-framework/avocado/pull/508

Changes:

    v2: removed threading.Lock
    v2: removed object_params & object_counts
    v2: pep8 fixups (names, line length)

Kind regards,
Lukáš

PS: Test "sleeptest" already uses the new params API.

### CODE REVIEW

**Comment by ldoktor** [comment]
@lmr, @ruda I fixed the issues I believe this can be applied as it's backward compatible.

**Comment by lmr** [comment]
Sure, I'll be taking a look and applying this.

**Comment by ldoktor** [comment]
Good catch, sorry about that...

**Comment by lmr** [comment]
Closing in favor of #531

**Pull request closed without merging**
