### PR TITLE
typo fix: hello_option -> hello for hello/setup.py

### PR DESCRIPTION
**Pull request by zenglg**
Revert hello/setup.py in commit 66514efe50cadea8b6d4e35539110920e825cb8e

Signed-off-by: Linggang Zeng <linggang.zeng@easystack.cn>

### CODE REVIEW

**Review by ana — APPROVED** [review]
Thanks

**Comment by zenglg** [comment]
@beraldoleal 
Hi, could you help to review?

**Review by clebergnu — APPROVED** [review]
LGTM, thanks!

**Comment by clebergnu** [comment]
As this is a trivial change, and has two reviews, I'm saving @beraldoleal a review and will merge it.

**Comment by zenglg** [comment]
> As this is a trivial change, and has two reviews, I'm saving @beraldoleal a review and will merge it.

Thanks.

**Pull request merged**
