### PR TITLE
varianter: Make it properly pluggable

### PR DESCRIPTION
**Pull request by ldoktor**
This PR is inspired by https://github.com/avocado-framework/avocado/pull/1591 and is the next stage of https://github.com/avocado-framework/avocado/pull/1685 . First it adds necessary interfaces to the old `varianter`, then it makes the `varianter` pluggable in a dirty way and then it turns it into a proper plugin defined in `avocado.core.plugin_interfaces`. Along the way there are several fixes and enhancements and at the end there is the promised rewrite of the multiplexer documentation, which took me several days to put together and I hope it's understandable and clear enough.

### CODE REVIEW

**Comment by ldoktor** [comment]
I have no idea why the Travis fails on python 2.7. It passes on my machine and in Travis on python 2.6 so I think it's false-negative.

**Comment by lmr** [comment]
From what I've seen, it may be a false negative indeed.

**Comment by ldoktor** [comment]
It's quite persistent, I also restarted the travis, but it does not breaks bisect on my machine and it's not failing in the last commit, therefor merging this should not destabilize master, nor it should break the bisect for developers.

**Comment by apahim** [comment]
@ldoktor could you please update commit ` varianter: Fix the return value in skip_new_data_check ` with:
```diff
diff --git a/selftests/functional/test_teststmpdir.py b/selftests/functional/test_teststmpdir.py
index 9f5bc55..1836df1 100644
--- a/selftests/functional/test_teststmpdir.py
+++ b/selftests/functional/test_teststmpdir.py
@@ -70,7 +70,7 @@ class TestsTmpDirTests(unittest.TestCase):
         Tests whether automatically created teststmpdir is shared across
         all tests.
         """
-        cmd_line = ("./scripts/avocado run --sysinfo=off "
+        cmd_line = ("./scripts/avocado --show test run --sysinfo=off "
                     "--job-results-dir %s %s %s" %
                     (self.tmpdir, self.simple_test, self.instrumented_test))
         self.run_and_check(cmd_line, exit_codes.AVOCADO_ALL_OK)
```

So we can take a look in the error travis is facing.

**Comment by clebergnu** [comment]
@ldoktor as suggested by @apahim please send a version that can be used to debug the Travis failures.  Travis is our gating mechanism, so we should really check what may be causing false positives (if that's really the case).

**Pull request closed without merging**
