### PR TITLE
Surface the release RTD link to GHA workflow summary page

### PR DESCRIPTION
**Pull request by webknjaz**
This will additionally display the updated text on pages like https://github.com/avocado-framework/avocado/actions/runs/11215982471.

Here's an example of how job summaries are displayed: https://github.com/ansible/awx-plugins/actions/runs/10793404435#summary-29935289633.

### CODE REVIEW

**Review by richtja — CHANGES_REQUESTED** [review]
Hi @webknjaz, thank you for your updates, the changes LGTM. The only issue is that our `Signed-off` check is failing, because your commit signature slightly differs from your git author's name. Can you please update that, thank you?

Signed-off-by: Sviatoslav Sydorenko (Святослав Сидоренко) <webknjaz@redhat.com>/Signed-Off-By: Sviatoslav Sydorenko <webknjaz@redhat.com>

**Comment by webknjaz** [comment]
Ah, right.. That's a limitation of PRs made throught web interface, which I go for in case of drive-bys as it's much faster.

**Comment by webknjaz** [comment]
done

**Review by richtja — APPROVED** [review]
Hi @webknjaz, thanks for the update, it LGTM.

**Pull request merged**
