### PR TITLE
selftests/check_tmp fixes

### PR DESCRIPTION
**Pull request by clebergnu**
A collection of fixes to the `selftests/check_tmp` script.

### CODE REVIEW

**Review by willianrampazzo — APPROVED** [review]

**Comment by willianrampazzo** [comment]
ops: 

selftests/check_tmp_dirs
There are temporary avocado dirs lying around after test: /tmp/avocado_kv4m_52g

**Comment by clebergnu** [comment]
> ops:
> 
> selftests/check_tmp_dirs
> There are temporary avocado dirs lying around after test: /tmp/avocado_kv4m_52g

Yep, that's like I documented [here](https://github.com/avocado-framework/avocado/issues/4392#issuecomment-928014259),  but it seems there's another case I missed.

**Comment by willianrampazzo** [comment]
> > ops:
> > selftests/check_tmp_dirs
> > There are temporary avocado dirs lying around after test: /tmp/avocado_kv4m_52g
> 
> Yep, that's like I documented [here](https://github.com/avocado-framework/avocado/issues/4392#issuecomment-928014259), but it seems there's another case I missed.

Oh, okay, so it is "expected" because of bug #4392, right?

**Comment by clebergnu** [comment]
> > > ops:
> > > selftests/check_tmp_dirs
> > > There are temporary avocado dirs lying around after test: /tmp/avocado_kv4m_52g
> > 
> > 
> > Yep, that's like I documented [here](https://github.com/avocado-framework/avocado/issues/4392#issuecomment-928014259), but it seems there's another case I missed.
> 
> Oh, okay, so it is "expected" because of bug #4392, right?

Exactly.  But, I assumed all the tests had the `keep_tmp` workaround, but it looks like CI is running some test that doesn't run by default in my `make check`.

Best course of action is to fix #4392 first, and then merge these fixes (or both at the same time).

**Review by beraldoleal — APPROVED** [review]

**Review by ana — APPROVED** [review]

**Comment by clebergnu** [comment]
Closing as it's part of https://github.com/avocado-framework/avocado/pull/4991

**Pull request closed without merging**
