### PR TITLE
Add failure reason to human UI on failed tests

### PR DESCRIPTION
**Pull request by rcgoodfellow**
Currently when a test fails I have to go dig through a very verbose log file with a fairly cumbersome path to see what went sideways. This slows down interactive development with avocado significantly. If the human UI also reports the test failure reason, it would streamline things significantly. This PR attempts to do that in a minimally invasive way.

### CODE REVIEW

**Comment by clebergnu** [comment]
Hi @rcgoodfellow thanks for proposing this, it does look handy.  I think we can expand this further and show `fail_reason` on other circumstances too, canceled tests also populate that field.  I'm thinking of something like:

```diff
diff --git a/avocado/plugins/human.py b/avocado/plugins/human.py
index 9302ba24..c35be6fb 100644
--- a/avocado/plugins/human.py
+++ b/avocado/plugins/human.py
@@ -75,6 +75,14 @@ class Human(ResultEvents):
         LOG_UI.debug(color + self.__throbber.render() +
                      output.TERM_SUPPORT.ENDC, extra={"skip_newline": True})
 
+    def get_colored_status(self, status, extra=None):
+        out = (output.TERM_SUPPORT.MOVE_BACK + self.output_mapping[status] +
+               status)
+        if extra:
+            out += ": " + extra
+        out += output.TERM_SUPPORT.ENDC
+        return out
+
     def end_test(self, result, state):
         if not self.owns_stdout:
             return
@@ -84,14 +92,8 @@ class Human(ResultEvents):
         duration = (" (%.2f s)" % state.get('time_elapsed', -1)
                     if status != "SKIP"
                     else "")
-        LOG_UI.debug(output.TERM_SUPPORT.MOVE_BACK +
-                     self.output_mapping[status] +
-                     status + output.TERM_SUPPORT.ENDC +
-                     duration)
-
-        if status == 'FAIL':
-            fail_reason = state.get("fail_reason", "")
-            LOG_UI.debug('    '+fail_reason)
+        msg = self.get_colored_status(status, state.get("fail_reason", None))
+        LOG_UI.debug(msg + duration)
 
     def post_tests(self, job):
         if not self.owns_stdout:
```

Now, the hardest part is coming up with smart defaults, and I'm not sure if this behavior should be default, or something part of a `-v|--verbose` option of Avocado. What do you think about it?

**Comment by rcgoodfellow** [comment]
@clebergnu LGTM. Having the `fail_reason` show up in the human UI any time it's present is a win.

**Comment by rcgoodfellow** [comment]
@clebergnu applied your patch directly in efbd31d and everything looks good for my tests.

**Comment by clebergnu** [comment]
@rcgoodfellow would you please send another PR with the combined work?

**Comment by rcgoodfellow** [comment]
sure thing

**Comment by rcgoodfellow** [comment]
Combined PR in #2802

**Pull request closed without merging**
