### PR TITLE
Introduce a very basic GH actions pipeline (v4)

### PR DESCRIPTION
**Pull request by beraldoleal**
This will enable GitHub workflows as part of an effort on running our tests in GitHub infrastructure. More details on individual commits.

Since this is not enabled here yet, you can see the output here:

https://github.com/beraldoleal/avocado/actions/runs/680460902

Also is doing some cleanups on pylint.

#### Changes from v3:
 - Small typo fix on commit message;
 - Pinned distro version on gh-workflow;
 - Merged ba062cfd4ed78930c52f60d872ab95b03c781c25
 
#### Changes from v2:
 - using a opt out logic (enable=all, disable=a few);
 - Spliting what is Python 3 port checks;
 - Small organization on ./selftests/lint.sh

#### Changes from v1:

- Installing avocado in develop mode and avoiding pylint hook;
- Exit status is now 128 in case of error during lint command;
- pyenchant==3.2.0
- check_call without shell=True;
- Adding a separation line for each check command;

### CODE REVIEW

**Comment by beraldoleal** [comment]
@clebergnu for some reason, travis is linking to v3 yet. v4 is passing:

https://travis-ci.org/github/avocado-framework/avocado/builds/766472244

**Review by clebergnu — APPROVED** [review]
LGTM, thanks!

**Comment by pevogam** [comment]
@beraldoleal It seems that setting up the GH actions pipeline on the main repo also sets it on all forks. Is this a desired behavior? I am wondering because some forks has some custom patches or other customizations that may fail with it. The workflow with Travis CI was such that tests and validation were run on PR-s about to be merged while here it seems even pushed of one's own branch will trigger the GH actions pipeline. In short: I am just wondering if it is a desired behavior to also have all forks run their own GH actions pipelines.

**Comment by willianrampazzo** [comment]
> @beraldoleal It seems that setting up the GH actions pipeline on the main repo also sets it on all forks. Is this a desired behavior? I am wondering because some forks has some custom patches or other customizations that may fail with it. The workflow with Travis CI was such that tests and validation were run on PR-s about to be merged while here it seems even pushes to one's own branch will trigger the GH actions pipeline. In short: I am just wondering if it is a desired behavior to also have all forks run their own GH actions pipelines.

this was my concern here: https://github.com/avocado-framework/avocado/pull/4471#discussion_r599052126

**Comment by beraldoleal** [comment]
Hi @pevogam, I will try to concentrate your questions here:

> Is this a desired behavior?

Would say that is a nice behavior, to test the pipeline *before* submitting it to review. But we can review that, of course.

> I am wondering because some forks has some custom patches or other customizations that may fail with it. The workflow with Travis CI was such that tests and validation were run on PR-s about to be merged while here it seems even pushes to one's own branch will trigger the GH actions pipeline.

From the upstream perspective, unless I'm missing something, makes sense to run those tests if someone pushes something to the master and is not using the fork-pr workflow. But, I understand the corner cases and I can think about a few options for now:

 1. If a fork has custom code and custom, this might be the case where customizing the pipeline would also be considerable;
 2. Disable completely the actions on the fork side [1];
 3. If we decide that is fine to not force contributors to test before submitting PRs, then we could investigate how to limit this only for our master; 

> Does this really consume GH action hours for everyone? 

AFAICT, if your fork is public, GH actions are free and will not consume your hours. Based on the pricing page of GH actions.

> Is there a way for some of us that would test once they establish a PR (i.e. an explicit candidate for testing for contributors) to disable this?

Does item 2 of my previous comment, help you here?


[1] - https://docs.github.com/en/enterprise-server@2.22/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository

**Comment by pevogam** [comment]
> Hi @pevogam, I will try to concentrate your questions here:
> 
> > Is this a desired behavior?
> 
> Would say that is a nice behavior, to test the pipeline _before_ submitting it to review. But we can review that, of course.

Yes, one could indeed argue that every push to any repo is a subject of proper testing so it still makes some sense.

> > I am wondering because some forks has some custom patches or other customizations that may fail with it. The workflow with Travis CI was such that tests and validation were run on PR-s about to be merged while here it seems even pushes to one's own branch will trigger the GH actions pipeline.
> 
> From the upstream perspective, unless I'm missing something, makes sense to run those tests if someone pushes something to the master and is not using the fork-pr workflow.

Yes, I this seems reasonable and is also what I read in the comments with @willianrampazzo. And it could make sense for any upstream branch and not just master so I guess the difference is that GitHub automatically transfers the same pipeline to every fork in comparison to other approaches.

> But, I understand the corner cases and I can think about a few options for now:
> 
>     1. If a fork has custom code and custom, this might be the case where customizing the pipeline would also be considerable;

You mean customizing the pipeline should be considered? Yes, also a good point.

>     2. Disable completely the actions on the fork side [1];

Good to know this is possible, to confess I haven't investigated the GH actions option yet so forgive my lack of knowledge here.

>     3. If we decide that is fine to not force contributors to test before submitting PRs, then we could investigate how to limit this only for our master;
> 
> 
> > Does this really consume GH action hours for everyone?
> 
> AFAICT, if your fork is public, GH actions are free and will not consume your hours. Based on the pricing page of GH actions.

Alright, then it makes sense to keep it enabled, I guess the only potential issue left then is that some people might be surprised when they find this out about their forks. But on ultimately such workflow makes sense considering all points above.

> > Is there a way for some of us that would test once they establish a PR (i.e. an explicit candidate for testing for contributors) to disable this?
> 
> Does item 2 of my previous comment, help you here?

Yes fully.

Alright, I guess let's see if there are more reactions from other forks in the future :+1:

**Comment by beraldoleal** [comment]
> You mean customizing the pipeline should be considered? 

On the fork side, yes! I mean: if the fork has already custom code and it really needs to disable test (because of that custom code) then, IMO, makes sense to delegate to the fork's maintainer this change on the pipeline as well. But I'm might be missing something. And everything here can be changed.

**Comment by pevogam** [comment]
> > You mean customizing the pipeline should be considered?
> 
> On the fork side, yes! I mean: if the fork has already custom code and it really needs to disable test (because of that custom code) then, IMO, makes sense to delegate to the fork's maintainer this change on the pipeline as well. But I'm might be missing something. And everything here can be changed.

No, it makes complete sense just like the other points. I just wanted to make sure that this is what you mean.

**Comment by pevogam** [comment]
I might have one issue to report but better to comment here first as I might be missing something. I get the following error on our CI:

image

and I made sure to sign all patches so something else must be happening. Has anyone of you seen this before? How is git set up on the GH side?

**Comment by beraldoleal** [comment]
Hi @pevogam yes we did saw this a few weeks ago.

What is the branch/repo? This was happening because gh-actions by default was getting a merge commit, this was (supposed) fixed here 4ebbc639f2e971565c50515cd4032940db74d3d1.

**Comment by pevogam** [comment]
This is happening on a custom branch rebased on top of the 87.0 tag with 5 or so custom patches right [here](https://github.com/intra2net/avocado/actions/runs/785518555). At least from what I can see the fixing commit is supposed to be already merged before the 87.0 tag.

**Comment by beraldoleal** [comment]
Hi @pevogam I cloned your repo and I could not find `.github/workflows/ci.yml` file there, neither the commit 4ebbc639f2e971565c50515cd4032940db74d3d1.

Also, not sure if I have looked to the right branch, but your GitHub repo says: " This branch is 471 commits behind avocado-framework:master. ". Is that expected?

**Comment by pevogam** [comment]
> Hi @pevogam I cloned your repo and I could not find `.github/workflows/ci.yml` file there, neither the commit [4ebbc63](https://github.com/avocado-framework/avocado/commit/4ebbc639f2e971565c50515cd4032940db74d3d1).

Hi @beraldoleal,

> This is happening on a custom branch rebased on top of the 87.0 tag with 5 or so custom patches right [here](https://github.com/intra2net/avocado/actions/runs/785518555). 

in the link I shared with you here there is the branch name and the commit name:
image

It leads to you commit https://github.com/intra2net/avocado/commit/c0020a83219fccc2e303f136773dd419f5367828 and branch https://github.com/intra2net/avocado/tree/tp-i2n.

I hope this helps you reproduce, you can see the web page of the CI status too included above to show that the failure is related to the commits/branch in question.

**Comment by beraldoleal** [comment]
Hi @pevogam, I just saw. I was looking at the wrong branch.

So, it might be an issue not related to this PR or Github actions. Your commit author is "pdimitrov@pevogam.com" but your "signned-off-by" line is "plamen.dimitrov@intra2net.com".

Can you please, double-check if running locally "selftests/signedoff-check.sh" or "make check" it is failing too?

**Comment by pevogam** [comment]
Hi @beraldoleal, I suspected this might turn to be a problem but I thought the "signed-off-by" could have a free value about the person taking (legal) responsibility about the changes proposed in the commit. Even when not I thought it should at least be tied to the committer name rather than the author name. I guess I might have missed details about the Avocado requirements here which explicitly require the commit author. Sorry about that.

Yes, the script fails also locally and I tried this before when I investigated the problem but didn't report it here as I should have. I actually postponed reporting such details here and instead asked "How is git set up on the GH side?" because I was wondering if perhaps the pipeline would use a git-related data like username/email instead one's local settings. It is clear now then, sorry for the noise.

**Pull request merged**
