### PR TITLE
Fix minor spelling problems for next release.

### PR DESCRIPTION
**Pull request by willianrampazzo**
Signed-off-by: Willian Rampazzo <willianr@redhat.com>

### CODE REVIEW

**Comment by csomh** [comment]
Sorry for this Packit failure, seems that one of the changes broke how the archive name is read from the specfile. We are working on reverting that change.

**Comment by willianrampazzo** [comment]
> Sorry for this Packit failure, seems that one of the changes broke how the archive name is read from the specfile. We are working on reverting that change.

Thanks for checking that @csomh!

**Comment by willianrampazzo** [comment]
> Congratulations! One of the builds has completed. 
> 
> You can install the built RPMs by following these steps:
> 
> * `sudo yum install -y dnf-plugins-core` on RHEL 8
> * `sudo dnf install -y dnf-plugins-core` on Fedora
> * `dnf copr enable packit/avocado-framework-avocado-3592`
> * And now you can install the packages.
> 
> Please note that the RPMs should be used only in a testing environment.

Thanks @csomh, @jpopelka!

**Pull request merged**
