### PR TITLE
Run unittests during the build of RPM packages

### PR DESCRIPTION
**Pull request by clebergnu**
Also, this changes the way the man pages are built to a simpler way IMHO.

### CODE REVIEW

**Comment by lmr** [comment]
I found the error on EPEL7: `DEBUG util.py:388:  Error: No Package found for python-flexmock`

We need to figure out what's going on there.

**Comment by lmr** [comment]
Unless we find out some other creative solution, unittesting has to be disabled on EPEL7. We could change

**Comment by lmr** [comment]
Yep, I like the idea of moving to http://farmdev.com/projects/fudge/, although this has to wait until the next sprint. Meanwhile I guess the plan is to tweak your patch to disable testing on EPEL7, do conditional build dependencies and push this, until we migrate unittests in the next sprint.

**Comment by clebergnu** [comment]
@lmr true. I tested on EPEL 6 and assumed it would be on EPEL 7.

It's pretty annoying to not find packages on EPEL 7 when they are on EPEL 6, even more than the other way around.

**Comment by clebergnu** [comment]
@lmr I added another patch that deals with EL7. I'm testing it locally but can you also test it on COPR?

**Comment by lmr** [comment]
@clebergnu sure!

**Comment by clebergnu** [comment]
There still is something wrong, this time on EL6: ( https://copr-be.cloud.fedoraproject.org/results/lmr/Autotest/epel-6-x86_64/avocado-0.21.0-6.fc21/build.log ):

```
+ selftests/run selftests/all/unit
..............................................E.............................................E../usr/lib/python2.6/site-packages/unittest2/case.py:326: DeprecationWarning: Use of a TestResult without an addSkip method is deprecated
  self._addSkip(result, skip_why)
.............
======================================================================
ERROR: Failure: ImportError (No module named fabric.exceptions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/nose/loader.py", line 364, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.6/site-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.6/site-packages/nose/importer.py", line 84, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/builddir/build/BUILD/avocado-0.21.0/selftests/all/unit/avocado/remote_unittest.py", line 8, in <module>
    from avocado import remote
  File "/builddir/build/BUILD/avocado-0.21.0/avocado/remote/__init__.py", line 17, in <module>
    from avocado.remote.runner import RemoteTestRunner
  File "/builddir/build/BUILD/avocado-0.21.0/avocado/remote/runner.py", line 25, in <module>
    from fabric.exceptions import CommandTimeout
ImportError: No module named fabric.exceptions
======================================================================
ERROR: Failure: ImportError (No module named fabric.exceptions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/nose/loader.py", line 364, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.6/site-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.6/site-packages/nose/importer.py", line 84, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/builddir/build/BUILD/avocado-0.21.0/selftests/all/unit/avocado/vm_unittest.py", line 8, in <module>
    from avocado.remote import VMTestResult, RemoteTestResult
  File "/builddir/build/BUILD/avocado-0.21.0/avocado/remote/__init__.py", line 17, in <module>
    from avocado.remote.runner import RemoteTestRunner
  File "/builddir/build/BUILD/avocado-0.21.0/avocado/remote/runner.py", line 25, in <module>
    from fabric.exceptions import CommandTimeout
ImportError: No module named fabric.exceptions
----------------------------------------------------------------------
Ran 106 tests in 0.524s
FAILED (errors=2)
```

Of course that unittest should fail because it tries to import `fabric`, but the strace thing is that, in my mock'ed environment, it runs the unittest just fine:

```
+ selftests/run selftests/all/unit
............................................................................................../usr/lib/python2.6/site-packages/unittest2/case.py:326: DeprecationWarning: Use of a TestResult without an addSkip method is deprecated
  self._addSkip(result, skip_why)
.............
----------------------------------------------------------------------
Ran 107 tests in 0.472s
```

Anyway, I'll continue to investigate this.

**Comment by lmr** [comment]
@clebergnu, this was introduced by @ldoktor's patch that introduces remote timeouts... weird stuff.

**Comment by clebergnu** [comment]
Oh, that certainly explains it. My local branch was not rebased with his patches. So, that is another broken RPM build requirement, fabric on EL 6. Good thing we're working on this one.

So, I suppose we should, for now, just run the unittests during the build of the packages on Fedora, where all the requirements are fulfilled. What do you think?

**Comment by clebergnu** [comment]
I'm closing this one in a favor of a v2 that has commits in better order and only enables unittests on Fedora.

**Comment by lmr** [comment]
@clebergnu, yep, testing only on Fedora seems OK for now.

**Pull request closed without merging**
