### PR TITLE
Reconsider when the `latest` log symlink is created

### PR DESCRIPTION
**Pull request by clebergnu**
Right now the symlink `latest` is created when the job finishes. I'd like to create the symlink when the job starts (after the point where we stop removing the results of incorrect execution like `avocado run`).

The motivation is to be able to use `tail -f $PATH/latest/job.log` to monitor the run of the current job.

This implements the card:

https://trello.com/c/QJ4wCD8x/447-reconsider-when-the-latest-log-symlink-is-created

### CODE REVIEW

**Comment by lmr** [comment]
@clebergnu, I did try the patches out, but apparently they don't work as expected: I did try a sleeptenmin.py and after avocado started run the tests, I tried:

    $ tail -f ~/avocado/job-results/latest/job.log

And it was pointing out to the previous job log. We'll have to investigate, meanwhile I won't be merging this.

**Comment by clebergnu** [comment]
Are you sure? This is what I see running what you're running:

```
./scripts/avocado run sleeptenmin 
JOB ID     : e4ba6f2a78076996dccbc53b64f903eb18beca20
JOB LOG    : /home/cleber/avocado/job-results/job-2015-08-03T22.03-e4ba6f2/job.log
JOB HTML   : /home/cleber/avocado/job-results/job-2015-08-03T22.03-e4ba6f2/html/results.html
TESTS      : 1
(1/1) sleeptenmin.py:SleepTenMin.test:
```

And simultaneously:

```
tail -f ~/avocado/job-results/latest/job.log
22:03:34 job              L0355 INFO | logs     /home/cleber/avocado/job-results
22:03:34 job              L0356 INFO | 
22:03:34 job              L0292 INFO | Job ID: e4ba6f2a78076996dccbc53b64f903eb18beca20
22:03:34 job              L0293 INFO | 
22:03:34 test             L0148 INFO | START sleeptenmin.py:SleepTenMin.test
22:03:34 multiplexer      L0193 DEBUG| PARAMS (key=timeout, path=*, default=None) => None
22:03:34 multiplexer      L0193 DEBUG| PARAMS (key=sleep_cycles, path=*, default=1) => 1
22:03:34 multiplexer      L0193 DEBUG| PARAMS (key=sleep_length, path=*, default=600) => 600
22:03:34 multiplexer      L0193 DEBUG| PARAMS (key=sleep_method, path=*, default=builtin) => 'builtin'
22:03:34 sleeptenmin      L0029 DEBUG| Sleeping for 600.00 seconds
```

See that the job id matches.

**Comment by lmr** [comment]
Weird, right? Maybe I made a mistake and tested while there were rpm packages installed. I'm going to remove all rpms and retry.

**Comment by lmr** [comment]
@clebergnu, yep, that's exactly what happened. I had the rpms installed, and didn't notice it. It's testing just fine. I'm going to merge it, thanks!

**Pull request merged**
