### PR TITLE
Fix Ctrl+C (for realz)

### PR DESCRIPTION
**Pull request by lmr**
Fix Ctrl+C handling. Revert my original patch, fix it properly and add a functional test for it. Good stuff.

### CODE REVIEW

**Comment by lmr** [comment]
To whomever is going to review this PR (@clebergnu or @ldoktor) - I'm not sure why one of my interrupt tests is failing on Travis -> I suspect something to do with Ubuntu using dash instead of bash. To test on your system, please run:

    python selftests/all/functional/avocado/interrupt_tests.py

**Comment by lmr** [comment]
After some debugging, this is what's happening -> For some unfathomable reason, wontquit.py is not being located:

    root: CRITICAL: START /home/travis/build/avocado-framework/avocado/examples/tests/wontquit.py
    root: CRITICAL: PARAMS (key=timeout, path=*, default=None) => None
    root: CRITICAL: Running '/home/travis/build/avocado-framework/avocado/examples/tests/wontquit.py'
    root: CRITICAL: 
    root: CRITICAL: Reproduced traceback from: /home/travis/build/avocado-framework/avocado/avocado/core/test.py:370
    root: CRITICAL: Traceback (most recent call last):
    root: CRITICAL:   File "/home/travis/build/avocado-framework/avocado/avocado/core/test.py", line 582, in test
    root: CRITICAL:     env=test_params)
    root: CRITICAL:   File "/home/travis/build/avocado-framework/avocado/avocado/utils/process.py", line 937, in run
    root: CRITICAL:     cmd_result = sp.run(timeout=timeout)
    root: CRITICAL:   File "/home/travis/build/avocado-framework/avocado/avocado/utils/process.py", line 483, in run
    root: CRITICAL:     self._init_subprocess()
    root: CRITICAL:   File "/home/travis/build/avocado-framework/avocado/avocado/utils/process.py", line 281, in _init_subprocess
    root: CRITICAL:     env=self.env)
    root: CRITICAL:   File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    root: CRITICAL:     errread, errwrite)
    root: CRITICAL:   File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    root: CRITICAL:     raise child_exception
    root: CRITICAL: OSError: [Errno 2] No such file or directory

And I have no idea why

**Comment by ldoktor** [comment]
Hmm, the fix seems to work fine, only the logic is IMO not correct:

```
./scripts/avocado run examples/tests/wontquit examples/tests/wontquit 
JOB ID     : 2360d3c9250a8fe6ffadcf9d163c80af3fec538a
JOB LOG    : /home/medic/avocado/job-results/job-2015-08-13T11.18-2360d3c/job.log
JOB HTML   : /home/medic/avocado/job-results/job-2015-08-13T11.18-2360d3c/html/results.html
TESTS      : 2
(1/2) examples/tests/wontquit: |
```
it's running ..., then I pres "ctrl+c"
```
./scripts/avocado run examples/tests/wontquit examples/tests/wontquit 
JOB ID     : 2360d3c9250a8fe6ffadcf9d163c80af3fec538a
JOB LOG    : /home/medic/avocado/job-results/job-2015-08-13T11.18-2360d3c/job.log
JOB HTML   : /home/medic/avocado/job-results/job-2015-08-13T11.18-2360d3c/html/results.html
TESTS      : 2
(1/2) examples/tests/wontquit: |^C
```
No explanation, nothing, it waits until I pres "ctrl+c" again:
```
./scripts/avocado run examples/tests/wontquit examples/tests/wontquit 
JOB ID     : 2360d3c9250a8fe6ffadcf9d163c80af3fec538a
JOB LOG    : /home/medic/avocado/job-results/job-2015-08-13T11.18-2360d3c/job.log
JOB HTML   : /home/medic/avocado/job-results/job-2015-08-13T11.18-2360d3c/html/results.html
TESTS      : 2
(1/2) examples/tests/wontquit: |^C^C
Interrupt requested. Waiting 2 seconds for test to finish (ignoring new Ctrl+C until then)
```
OK, now I know what happened, so I'm waiting for the test to finish... Hmm, it's a bad test and it won't finish, so I'll try ignoring the message that ctrl+c won't work and try it again:
```
./scripts/avocado run examples/tests/wontquit examples/tests/wontquit 
JOB ID     : 2360d3c9250a8fe6ffadcf9d163c80af3fec538a
JOB LOG    : /home/medic/avocado/job-results/job-2015-08-13T11.18-2360d3c/job.log
JOB HTML   : /home/medic/avocado/job-results/job-2015-08-13T11.18-2360d3c/html/results.html
TESTS      : 2
(1/2) examples/tests/wontquit: |^C^C
Interrupt requested. Waiting 2 seconds for test to finish (ignoring new Ctrl+C until then)
^CKilling test subprocess 23100

ERROR (185.75 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 1 | WARN 0 | INTERRUPT 0
TIME       : 185.75 s
```
And voila, it's not ignored at all. It destroys the test and safely evaluates the rest of the execution and prints out the statistics.

So changes I'd like to propose:

* Print the message about test interruption immediately after first ctrl+c
* First ctrl+c msg: `Test interrupted by "ctrl+c", trying to interrupt test gracefully`
* Second ctrl+C msg: `Killing test subprocess XXXX ungracefully`

**Comment by ldoktor** [comment]
Btw the status of interrupted test by 3xctrl+c is ERROR, while tests that cooperate and are interrupted by 1xctrl+c finish with INTERRUPTED.

**Comment by adereis** [comment]
IIRC, the previous behavior was correct, as described by @ldoktor:  A first Ctrl+C would tell the user the test was being aborted, there would be a window of a couple of secs and after that any other Ctrl+C's would kill the process.

@lmr: I suggest you submit a patch that doesn't change any messages or behavior when fixing the issue introduced by a previous refactoring.

**Comment by lmr** [comment]
Closing in favor of #767.

**Comment by lmr** [comment]
BTW, the original behavior did ignore the first message.

**Pull request closed without merging**
