### PR TITLE
Deprecate python3.6

### PR DESCRIPTION
**Pull request by beraldoleal**
@clebergnu Not sure if this should be included in 93. I remember we discussing this a few weeks ago. In any case added this to 94.

### CODE REVIEW

**Comment by clebergnu** [comment]
I'd love to ACK this, but IMO we should wait until the actual EOL because then I believe QEMU will also bump the minimum requirement to 3.7 (it currently is 3.6).

**Comment by ana** [comment]
I also would like to wait for the actual EOL of python 3.6

**Comment by beraldoleal** [comment]
No problem. I just posted this here, because yesterday while debugging another issue, one possible path it was  blocked by python3.6. And since we discussed this already on avocado-vt/#3241 and avocado-vt/#3256, I just remember the intention to drop it.

So let's keep it here for when is the time.

**Comment by clebergnu** [comment]
Closing in favor of #5113

**Pull request closed without merging**
