### PR TITLE
Nrunner functional tests fix

### PR DESCRIPTION
**Pull request by richtja**
Avocado has a problem with running two jobs which are connected to the
same status server. This problem is reported in #4308. We have two tests
which are affected by this issue because they are running their own
avocado jobs, and it is possible that those tests breaking Travis CI
which is  reported in #4768. This commit fixes those tests by creating
their own status server for their jobs.

Reference: #4308 #4768
Signed-off-by: Jan Richter <jarichte@redhat.com>

### CODE REVIEW

**Comment by willianrampazzo** [comment]
Oh, well, nice try, but it did not fix the problem on Travis :(

https://app.travis-ci.com/github/avocado-framework/avocado/jobs/524447498

**Comment by richtja** [comment]
> Oh, well, nice try, but it did not fix the problem on Travis :(
> 
> https://app.travis-ci.com/github/avocado-framework/avocado/jobs/524447498

Yes, unfortunately not, we have to still searching, but still is a valid fix

**Review by willianrampazzo — APPROVED** [review]

**Review by ana — APPROVED** [review]
Thanks @richtja, I have tested and it indeed fixes the problem I reported in #4768.

**Review by clebergnu — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
