### PR TITLE
avocado.core.remote.runner: Use more robust avocado version check

### PR DESCRIPTION
**Pull request by lmr**
Sometimes remote servers might have MOTD (message of the day)
banners, that will introduce line breaks on the remote output
of the `avocado -v` command. Let's use re.MULTILINE and
re.findall to solve that.

Signed-off-by: Lucas Meneghel Rodrigues <lookkas@gmail.com>

### CODE REVIEW

**Comment by lmr** [comment]
Ok, that's better.

**Comment by clebergnu** [comment]
Works for me! Thanks!

**Comment by lmr** [comment]
@clebergnu I just found out that there's another problem on the regexp. I'm preparing yet another patch.

Catching up with changes on the product under test is incredibly annoying.

**Comment by ldoktor** [comment]
well actually what's the full output, which breaks your testing? If we use the last match then I think it's fine to match without the new-line.. (I know ssh sometimes merges 2 lines together, very hard to reproduce...)

**Pull request merged**
