### PR TITLE
RFC: Introduce command line option to read configuration from a file.

### PR DESCRIPTION
**Pull request by ruda**
This introduce the command line -c or --config to read configuration
from a file. In order to this take effect, the avocado parser
now expose the settings read from the configuration inside the
proper arguments namespace.

How to test it:
* copy etc/avocado.conf to some place and edit what you want. For example, set color output to false.
* run `avocado -c avocado.conf config` or `avocado -c avocado.conf run passtest`.

### CODE REVIEW

**Comment by ldoktor** [comment]
Hello @ruda, how about this:

```diff
diff --git a/avocado/core/parser.py b/avocado/core/parser.py
index df7ff00..015bf60 100644
--- a/avocado/core/parser.py
+++ b/avocado/core/parser.py
@@ -20,6 +20,7 @@ Avocado application command line parsing.
 import sys
 import argparse
 
+from avocado import settings
 from avocado.core import tree
 from avocado.version import VERSION
 
@@ -45,6 +46,8 @@ class Parser(object):
         self.application.add_argument('--plugins', action='store',
                                       help='Load extra plugins from directory',
                                       dest='plugins_dir', default='')
+        self.application.add_argument('-c', '--config',
+                                      help='Use custom config file')
 
     def start(self):
         """
@@ -54,7 +57,9 @@ class Parser(object):
         Side effect: update attribute `args` (the namespace).
         """
         self.args, _ = self.application.parse_known_args()
-
+        # Load setting from file if asked for
+        if hasattr(self.args, 'config'):
+            settings.settings = settings.Settings(self.args.config)
         # Use parent parsing to avoid breaking the output of --help option
         self.application = argparse.ArgumentParser(prog=PROG,
                                                    description=DESCRIPTION,
```

It works fine and is quite simple. Additionally you can still use `from avocado.settings import settings; settings.get_value()` directly without having it as a class variable.

```
./scripts/avocado -c etc/avocado/conf.d/gdb.conf config
Config files read (in order):
    etc/avocado/conf.d/gdb.conf

    Section.Key         Value
    gdb.paths.gdb       /usr/bin/gdb
    gdb.paths.gdbserver /usr/bin/gdbserver

```

**Comment by ldoktor** [comment]
Actually after Ademars clarification, instead of `settings.settings = settings.Settings(self.args.config)`, you can simply do `settings.settings._process_config_path(self.args.config)`. That way you extend the existing config for all imported settings modules.

**Comment by adereis** [comment]
+1 to @ldoktor's patch. That's exactly what I had in mind when I imagined this as a low hanging fruit.

**Comment by lmr** [comment]
Yeah, that makes sense. We can promote `_process_config_path` to a public interface, given this use case.

**Comment by ruda** [comment]
Closing this in favor of #657 .

**Pull request closed without merging**
