### PR TITLE
Functional test fixes

### PR DESCRIPTION
**Pull request by lmr**
Getting to eliminate all places where we were not properly cleaning up temporary test results in both /tmp and ~/avocado/job-results was harder than I thought. But I finally got there.

Changes from v1:
 * Addressed comments from @ldoktor and @clebergnu.

### CODE REVIEW

**Comment by ldoktor** [comment]
OK, it seems to work fine, although empty `~/avocado/job-results/` dir gets created, which is IMO harmless. Please take a look at few style nitpicks.

I remark apart from mentioned, there are many unittests doing the same think. How about creating `avocado.unittest.AvocadoTestCase` which would handle the tmpdir by itself? Additionally it might contain `avocado.unittest.AVOCADO_RUN_FLAGS` to execute avocado with all required flags.

Anyway the pull request as is works fine, so just consider the advises and feel free to ignore them if you disagree.

**Comment by clebergnu** [comment]
OK @lmr great work. Waiting for a v2, I'm eager to merge this and bring order to my `~/avocado/job-results`! :)

**Comment by lmr** [comment]
@ldoktor and @clebergnu, I've updated the PR. The only thing I didn't implement from your comments is the common functional class. I've started to write the functional test class, but I didn't want eventual disagreements on how the class should look like and stay to block this work, given that it's not strictly necessary.

**Comment by lmr** [comment]
@ldoktor and @clebergnu, this is what I have in mind for a common functional test class of avocado - what do you think? Is the location adequate? I don't like the idea of creating `avocado.unittest`, given that creating modules with the same name as stdlib modules is a slippery slope.

	From 9fd57ac3fc7c544a171b36db2eae3d0085367d1e Mon Sep 17 00:00:00 2001
	From: Lucas Meneghel Rodrigues <lmr@redhat.com>
	Date: Mon, 13 Apr 2015 15:02:31 -0300
	Subject: [PATCH] avocado.Test: Add AvocadoFunctionalTest class

	This is a unittest style skeleton for avocado functional
	tests. In setUp(), it'll create a temporary directory
	where the results of each avocado job run will be written
	to, that will be cleaned up later in the tearDown() method.

	Signed-off-by: Lucas Meneghel Rodrigues <lmr@redhat.com>
	---
	 avocado/test.py | 20 ++++++++++++++++++++
	 1 file changed, 20 insertions(+)

	diff --git a/avocado/test.py b/avocado/test.py
	index b465b3b..dc434eb 100644
	--- a/avocado/test.py
	+++ b/avocado/test.py
	@@ -25,6 +25,7 @@ import pipes
	 import shutil
	 import sys
	 import time
	+import tempfile
	 
	 if sys.version_info[:2] == (2, 6):
	     import unittest2 as unittest
	@@ -605,3 +606,22 @@ class NotATest(Test):
		 e_msg = ('File %s is not executable and does not contain an avocado '
		          'test class in it ' % self.name)
		 raise exceptions.NotATestError(e_msg)
	+
	+
	+class AvocadoFunctionalTest(unittest.TestCase):
	+
	+    """
	+    Avocado functional test class, with common flags and setup that most functional tests require.
	+
	+    It is important to notice that you're not supposed to use this for writing your test suites.
	+    This is intended to be a helper for people writing functional tests for avocado itself.
	+    """
	+
	+    def setUp(self):
	+        self.tmpdir = tempfile.mkdtemp(prefix='avocado_functional')
	+
	+    def get_run_flags(self):
	+        self.run_flags = '--disable-sysinfo --job-results-dir %s' % self.tmpdir
	+
	+    def tearDown(self):
	+        shutil.rmtree(self.tmpdir)

**Comment by clebergnu** [comment]
You probably meant `--sysinfo off`. Other than that, it's pretty obvious and sound. ACK!

**Comment by clebergnu** [comment]
Merged, thanks!

**Comment by ldoktor** [comment]
Yep, your proposal seems fine, one could argue that `default_run_flags()` would be more explicit, but I like the idea.

**Pull request merged**
