### PR TITLE
Plugin: introduce generic configuration interface

### PR DESCRIPTION
**Pull request by clebergnu**
This is a follow up to the discussion on https://github.com/avocado-framework/avocado/issues/3795, specially with regards to this comment: https://github.com/avocado-framework/avocado/issues/3795#issuecomment-632189730

```python
MyPlugin(AvocadoPlugin, CLICmd):
   def configure(self):
      register_option here
```

The proposed interface is not exactly that, but it's pretty similar in concept.

This PR actually fixes an issue with `job/vmimage.py`, which is currently not able to use the Yaml to Mux plugin.  Because the Varianter plugin requires all default values to be set (by the option registration), we need to either register the plugin options (as proposed here) or require Job API to create a configuration with empty entries that they do not need, such as (currently) `run.mux_filter_out`, `run.mux_filter_only`, `run.mux_parameter_paths`, etc.

### CODE REVIEW

**Comment by clebergnu** [comment]
Thanks @willianrampazzo . I have further work on top of this, so merging.

**Comment by beraldoleal** [comment]
@clebergnu I marked myself as a review, :(

**Comment by clebergnu** [comment]
> @clebergnu I marked myself as a review, :(

I think I did @beraldoleal , than I realized (or thought) you'd be "off" Today. We can still tweak anything you find!

**Comment by beraldoleal** [comment]
> > @clebergnu I marked myself as a review, :(
> 
> I think I did @beraldoleal , than I realized (or thought) you'd be "off" Today. We can still tweak anything you find!

Yes, I was marking myself then I realized that you marked, so I imagined that you would wait for my review.

I think that it is better to review here during the PR phase.

**Pull request merged**
