### PR TITLE
Revert Test ID change

### PR DESCRIPTION
**Pull request by apahim**
We changed the wrong character. We should have changed the colon (`:`), but we ended up changing the semi-colon (`;`).

### CODE REVIEW

**Comment by ldoktor** [comment]
Oh, my fault. I know we moved from `:` to `;` and back. I should have been more careful on review. The question is, @clebergnu, how far are you in the release? I see you already tagged it, can it be undone? Or can we only release 54.1 otherwise?

**Comment by apahim** [comment]
@ldoktor, v54 packages are already published. Now we have 2 options:
- Revert; release v54.1; reopen the bug.
- Keep it as is; reopen the bug.

**Comment by clebergnu** [comment]
Let's revert and release 54.1.

**Comment by clebergnu** [comment]
@apahim @ldoktor I don't think we should rewrite history, I mean, rewrite the release notes of 54.0.  I'll write a 54.1 release notes doc, and in there it'll be documented that that change was reverted.  Do you guys agree?

**Comment by clebergnu** [comment]
And alternative version has been pushed and tagged as 54.1.

**Pull request closed without merging**
