### PR TITLE
RFC: Plugin interfaces: proposal for a better module name and location

### PR DESCRIPTION
**Pull request by clebergnu**
Avocado currently does not define a set of APIs for plugin writers.
It's well understood that anyone writing plugins is really playing
under the hoods of core Avocado.

Because there's no such module namespace allocated for that purpose
alone (say, `avocado.plugin`) it was decided to put plugin interfaces
together with the "core plugin repository", that is the
"avocado/plugins" directory.  By no means the contents of
"avocado/plugins/", that is, the plugin implementations themselves,
need be the "avocado.plugins" module, it could just as well live in
"avocado-core-plugins" directory or repository.  This is also well
exemplified by the avocado-vt and avocado-virt plugins, which live in
completely separate repositories.

So, the first goal of these changes are, effectively, to make all
plugin implementations equal, always referring to
`avocado.core.plugins_interface`.  Then, the secondary goal is to pave
the way for a specific namespace to contain only the interfaces (which
should be non-core) which plugin writers should rely on.

Signed-off-by: Cleber Rosa <crosa@redhat.com>

### CODE REVIEW

**Comment by ldoktor** [comment]
Well I see your point and I think in the future we might want to mark some API vital for plugins stable, but I don't think it's the case right now. So when I take a look at this from the future perspective, we'd have to make the plugin definition also part of the stable API, which means moving the plugin definition again.

So I could live with this change, but I'd prefer keeping it as is until we decide to create the stable interface intended for plugins and then move the plugin definition there.

**Comment by clebergnu** [comment]
@ldoktor it's a tough call indeed. I guess the best judgement rule we can make is by asking: is coming up with a stable set of APIs for plugin writers anywhere in our short term plan? @adereis since you play a big part in planning, you may want to give your opinion here.

IMHO, we're not planning to provide a stable API for plugin writers in the short term, so that's why I believe it's worth to increases the consistency of the roles of the `avocado.plugins` *directory* and the `avocado.core` *module*.

**Comment by adereis** [comment]
On Thu, Jun 02, 2016 at 06:02:22AM -0700, Cleber Rosa wrote:
> @ldoktor it's a tough call indeed. I guess the best judgement
> rule we can make is by asking: is coming up with a stable set
> of APIs for plugin writers anywhere in our short term plan?
> @adereis since you play a big part in planning, you may want to
> give your opinion here.
> 
> IMHO, we're not planning to provide a stable API for plugin
> writers in the short term, so that's why I believe it's worth
> to increases the consistency of the roles of the
> `avocado.plugins` *directory* and the `avocado.core` *module*.
> 

We don't have plans to provide stable interfaces for plugins
anytime soon (due to lack of resources to implement and support
them).

I think this change from Cleber is welcome, as it better
organizes the layout of the code and makes the module boundaries
more clear. As he says in the changelog, this "makes all plugin
implementations equal".

-- 
Ademar Reis
Red Hat

^[:wq!

**Comment by ldoktor** [comment]
OK, it's a step to the right direction, but we know it's temporary. So how about moving the code to `avocado/core/plugin_interfaces.py` while keeping a symple `avocado/plugins/base.py` which includes the interfaces defined in `core`. That way we (and other users) don't have to modify their plugins. Then ~2 releases before the new LTS we would add a `warning` and then we force users to transit. The LTS would only contain the new location.

My intention is of course selfish, people using master would still be compatible with LTS and if we by any chance implement the stable plugin API (which most certainly means another location change) we can simply do it and adjust the plugins before the LTS release. This means only 1 transition and not 2 (in case we come up with the change before LTS, if not then there is no benefit, nor drawback). I'd also mean that this PR would only become `avocado` PR and the `avocado-vt` and `avocado-virt` would be unaffected.

**Comment by clebergnu** [comment]
The compatibility issues have been dealt with in the avocado-vt and avocado-virt PRs, that is, they would work with either Avocado LTS or any later version (including HEAD from master).  One big point about having the LTS is to *not need* to think about compatibility and warnings and everything else in the master branch.  Avocado-VT would not need *any* change right now if used coupled with the LTS release.  If external projects are tracking the non-LTS releases, then they should keep an eye on the activity on master, as non-LTS releases are allowed to bring incompatibilities.

Then, as you suggested, we should announce the deprecation as a warning on the official release notes, about 2 releases before LTS.

**Comment by adereis** [comment]
> The compatibility issues have been dealt with in the avocado-vt and avocado-virt PRs, that is, they would work with either Avocado LTS or any later version (including HEAD from master). One big point about having the LTS is to not need to think about compatibility and warnings and everything else in the master branch. Avocado-VT would not need any change right now if used coupled with the LTS release. If external projects are tracking the non-LTS releases, then they should keep an eye on the activity on master, as non-LTS releases are allowed to bring incompatibilities.

So the situation here is that plugin interfaces are considered core (not stable, not supported), but the namespace was not clearly defined in the code organization and we have at least two plugins that depend on these core plugins interfaces. So this is what Cleber is proposing:

 - Plugins out there who make use of these interfaces should be using the LTS. That's the case with avocado-vt: OK
 - Adding code to these plugins to work with both versions (at least for this particular change) is simple, and there's a PR for avocado-vt (optional, but a welcome change, I would say)
 - Plugins out there which want to use sprint releases, should follow the development and the release-notes, or add compatibility code: OK
 - This change will make more clear to developers that plugin interfaces are core: GOOD

+1 from me.

**Comment by ldoktor** [comment]
OK, at least I tried... So let me do yet another set of checks and I'll merge it afterwards...

**Comment by ldoktor** [comment]
What a pity, the TAP plugin was introduced after this PR so travis did not check for it and it went unnoticed by me. Reminder to myself, add `selfchecks` to my `merge_pr` script. @clebergnu I pushed the fix https://github.com/avocado-framework/avocado/commit/6bf9e774e66495c06bdbf055698ea035223ab26c as without it the master fails and TAP plugin is not available. Please let me know if the fix is not correct.

**Comment by ldoktor** [comment]
Actually this brings questions to our current workflow. If we keep using `--no-ff` then the commits are injected where the original author left them, which in case of this TAP plugin breaks bisect. So perhaps we should reconsider the signing. For example Milan on `cryptsetup` uses the GPG only for tags. I still see a value in signing the merges, but perhaps we should use `--ff` and sign all the commits by the reviewer's GPG after the rebase. That way we could only review the merge commits to see whether the code was or was not altered and we could sign the `tag` with just brief check as all the commits should be signed by maintainers (we could even verify there are no unsigned commits)

**Pull request merged**
