### PR TITLE
Added a subroutine in avocado:utils:cpu about checking system has hyperthreading

### PR DESCRIPTION
**Pull request by PraveenPenguin**
Added a subroutine in avocado:utils:cpu about checking system has
hyperthreading

Signed-off-by: Praveen K Pandey <praveen@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by PraveenPenguin** [comment]
> @PraveenPenguin given that the same function is supposed to be used for power and other CPU types, would you say that the term `hyperthreading` is more common than `smt`? What I mean is, IMO, most users will quickly identify the purpose of a function called `is_hyperthreading_capable` but few IMO know what `smt` stands for. What do you think?
smt stands for simultaneous Multithreading seeme me good idea function name should be generic, what you suggested seems me good idea, will adopt that 
> 
> Also, it's a good idea to write a test for every new utility API. To make the test writing easier, feel free to break this function into two (private?) functions, such as:
> 
> ```python
> def _is_power_smt_capable():
> ...
> ```
> 
> and:
> 
> ```python
> def _is_generic_hyperthreading_capable():
> ...
> ```
> 
> This way, you can test them individually, mocking `glob.glob` and `os.path.exists` in the first one, and mocking `open('/proc/cpuinfo')` in the second one. Examples in `selftests/unit/test_utils_cpu.py` should be easy to follow.

yes make sense will write a unit test case 
> 
> Of course, a non-private `is_hyperthreading_capable()` function would make use of them both.

@clebergnu thanks for the review

**Comment by clebergnu** [comment]
@PraveenPenguin ping, do you intend to follow up with this PR? Thanks!

**Comment by PraveenPenguin** [comment]
> @PraveenPenguin ping, do you intend to follow up with this PR? Thanks!

@clebergnu ah yes some how i missed this PR , will send updated version soon

**Comment by richtja** [comment]
Since we don't have any updates here for more than 2 years, I am closing this PR. @PraveenPenguin feel free to reopen it if you need to.

**Pull request closed without merging**
