### PR TITLE
Test Loader: support for enable/disable docstring tags [v0]

### PR DESCRIPTION
**Pull request by clebergnu**
Since the test loader now attempts to find Avocado instrumented tests by using a parser and doesn't really load/execute test files, it can't tell if a given class inherits from avocado.Test.

For those cases, a developer may signal, using a docstring tag, that either:

* A test class that doesn't look like an Avocado test class is indeed one (":avocado: enable")
* A test class that looks like an Avocado test class should not be treated as such (":avocado: disable")

Also included is a a simple optimization by breaking earlier from the parser loop.

Please test these, and for v1 I'll update the diagrams and documentations.

### CODE REVIEW

**Comment by clebergnu** [comment]
Ouch, failed on Python 2.6 because of the `unittest` functionality I used. Let's see how to work around those.

**Comment by lmr** [comment]
@clebergnu I was thinking, the skip unittest tag can be replaced by in test code that turns the test into a no op if the network resource is unavailable. It's more hack-ish, but it gets the job done.

Another option is not fix the problem at all and live with the fact that the test is going to fail under the appropriate circumstances (not great).

**Comment by ldoktor** [comment]
This patch allows users to use multiple classes inside one patch, but currently it's not handled properly by the `loader.load_test`. Would you please add this:

```diff
diff --git a/avocado/core/loader.py b/avocado/core/loader.py
index 72dab54..b05a41f 100644
--- a/avocado/core/loader.py
+++ b/avocado/core/loader.py
@@ -256,7 +256,7 @@ class TestLoaderProxy(object):
             f, p, d = imp.find_module(module_name, [test_module_dir])
             test_module = imp.load_module(module_name, f, p, d)
             for _, obj in inspect.getmembers(test_module):
-                if (inspect.isclass(obj) and
+                if (inspect.isclass(obj) and obj.__name__ == test_class and
                         inspect.getmodule(obj) == test_module):
                     if issubclass(obj, test.Test):
                         test_class = obj

```
```python
class First(Test):
    """
    :avocado: disable
    """
    def test(self):
        pass

class Second(First):
    """
    :avocado: enable
    """
    def test_4(self):
        pass
```

Note that this won't run the `Second.test`, but that's not easily solvable (and is described in different comment). The patch above only solves the `Second.test_4` execution, which normally raises a exception.

**Comment by clebergnu** [comment]
@lmr I think this is actually simpler. We're already using `unittest2` for Python 2.6, but we're using it only it a couple of places (`selftests/functional/test_loader.py` has it for example). I'm just updating `selftests/unit/test_loader.py` to also use it.

**Comment by ldoktor** [comment]
@clebergnu v2 of the patch which includes couple of cleanups in `load_test`:

```diff
diff --git a/avocado/core/loader.py b/avocado/core/loader.py
index 72dab54..3705348 100644
--- a/avocado/core/loader.py
+++ b/avocado/core/loader.py
@@ -246,17 +246,14 @@ class TestLoaderProxy(object):
         :return: an instance of :class:`avocado.core.test.Test`.
         """
         test_class, test_parameters = test_factory
-        if 'modulePath' in test_parameters:
-            test_path = test_parameters.pop('modulePath')
-        else:
-            test_path = None
+        test_path = test_parameters.pop('modulePath', None)
         if isinstance(test_class, str):
-            module_name = os.path.basename(test_path).split('.')[0]
+            module_name = os.path.basename(test_path).split('.', 1)[0]
             test_module_dir = os.path.dirname(test_path)
             f, p, d = imp.find_module(module_name, [test_module_dir])
             test_module = imp.load_module(module_name, f, p, d)
             for _, obj in inspect.getmembers(test_module):
-                if (inspect.isclass(obj) and
+                if (inspect.isclass(obj) and obj.__name__ == test_class and
                         inspect.getmodule(obj) == test_module):
                     if issubclass(obj, test.Test):
                         test_class = obj
```

**Comment by clebergnu** [comment]
@ldoktor your fix was spot on! Thanks!

**Comment by clebergnu** [comment]
Closing in favor of #827.

**Pull request closed without merging**
