### PR TITLE
avocado config: Add --paginator to command

### PR DESCRIPTION
**Pull request by lmr**
Add the --paginator (on|off) option to 'avocado config'.
This option has been missing from that command, which
is inconsistent with the other listing options we have.

Signed-off-by: Lucas Meneghel Rodrigues <lmr@redhat.com>

### CODE REVIEW

**Comment by ldoktor** [comment]
Yep, seems to work fine. I'm wondering how about adding `--paginator` to the root parser the same as `-v` and `-h`?

**Comment by lmr** [comment]
@ldoktor well, that seems doable as well.

**Comment by lmr** [comment]
I'll take a look and re-send if possible.

**Comment by lmr** [comment]
@ldoktor, yep, that doesn't work as we thought it would (the parser accessed by the subcommand is different from the top level parser. I'm afraid we'll have to use it like this.

**Comment by ldoktor** [comment]
Well it works on the top level, so you can run `avocado --paginator off run ...` or `avocado --paginator on list`. It's a global option shared all over the avocado, so it make sense to put it there. Anyway I have nothing against this solution either, it's a matter of taste :smile:

**Pull request merged**
