### PR TITLE
avocado.core.job: Print variants after the tree representation

### PR DESCRIPTION
**Pull request by lmr**
Implements the card:

https://trello.com/c/NWsedWVd/483-print-out-the-multiplex-variants-right-after-the-tree

### CODE REVIEW

**Comment by ldoktor** [comment]
Well the output will be quite long (imagine avocado-vt's number of paths). But if majority of people believes it should be there... (I'd rather dump the result yaml file so people can load it in avocado list) and skipped the tree+variants.

**Comment by adereis** [comment]
Yes @ldoktor, I agree it might take considerable logging space and this solution is not complete. As discussed on IRC yesterday with @lmr, I think the real solution will be a consequence of the implementation of "job replay" (https://trello.com/c/ZRWynoDP/395-avocado-job-replay-allows-running-a-new-job-based-on-the-results-of-a-previous-job). That's because once we implement that, we'll be able to get all the information about a job from the job results directory.

With that said, give the multiplexer is a current work in progress and most if not all of its usage will be quite simplistic, I think this is a nice addition to the job log. @clebergnu probably added this request because he missed it during some debugging session.

**Comment by clebergnu** [comment]
@adereis agree completely and you spotted my pain^H^H^H^H use case. :smile:

**Comment by lmr** [comment]
OK, I'm closing this and moving the card back to the sprint backlog.

**Comment by adereis** [comment]
@ldoktor said he was OK with the change if we want it and both me and Cleber are advocating for it (and you implemented it). So maybe this should be merged after all?

**Pull request closed without merging**
