### PR TITLE
Run commands that require admin privileges with 'sudo'

### PR DESCRIPTION
**Pull request by lmr**
Following @ldoktor's suggestion, I took the longer path of adding sudo related options to process APIs, and then using them on the service and software_manager modules.

### CODE REVIEW

**Comment by lmr** [comment]
Sorry, I'm going to fix the Travis problems later.

**Comment by ldoktor** [comment]
Thanks @lmr for working on this. I still haven't had time to work on it...

**Comment by lmr** [comment]
@ldoktor, I've updated the code to have a single `sudo` parameter, `getuid` checking, and even unittests that verify the resulting generated command. Please take a look.

**Comment by ldoktor** [comment]
Hi @lmr, thank you for all the hard work. I like it and everything I tested works transparently and fine. I left few nitpicks so you know I did the review :smile:, please take care of them and we can merge it.

**Comment by lmr** [comment]
Closing this in favor of #987

**Pull request closed without merging**
