### PR TITLE
Enhance the network config to include ipv6.

### PR DESCRIPTION
**Pull request by manvanthar**
Enhance the network config to include ipv6. This is needed for the Infiniband tests.

Signed-off-by: Manvanthara Puttashankar <manvanth@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by manvanthar** [comment]
Here is the sample Infiniband ifcfg needed for the Infiniband tests.  Without ipv6 addresses,  Infiniband test fails.

# cat ifcfg-ib0 
TYPE=Infiniband
BOOTPROTO=none
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
NAME=ib0
DEVICE=ib0
ONBOOT=yes
IPADDR="10.10.10.10"
NETMASK="255.255.255.0"

**Comment by PraveenPenguin** [comment]
@manvanthar I think it same as #3334 can you please confirm, if yes we can pursue this feature in that PR is that ok

**Comment by manvanthar** [comment]
Sure @PraveenPenguin but it should also include the below lines. Needed for the Infiniband tests.

            network_conf.write("IPV6_AUTOCONF=yes \n")
            network_conf.write("IPV6_DEFROUTE=yes \n")

**Comment by manvanthar** [comment]
btw since avocado-misc-tests have already included in the sysfs method of setitng the IP .  The new NIC patch has broken the complete infiniband tests.

ipv6 patch need to go at the earliest. @PraveenPenguin

**Comment by PraveenPenguin** [comment]
> btw since avocado-misc-tests have already included in the sysfs method of setitng the IP . The new NIC patch has broken the complete infiniband tests.
> 
> ipv6 patch need to go at the earliest. @PraveenPenguin

@manvanthar sure i requested to @vaishnavibhat  to incoperatre these also there

**Comment by PraveenPenguin** [comment]
closing this PR as #3334 is already in

**Pull request closed without merging**
