### PR TITLE
Remove documentation on legacy "--loader"

### PR DESCRIPTION
**Pull request by clebergnu**
Since 429ce4620, the "--loader" option to list is no longer accessible
to users.  Let's sync the documentation with that reality.

Signed-off-by: Cleber Rosa <crosa@redhat.com>

### CODE REVIEW

**Review by beraldoleal — APPROVED** [review]
LGTM.536124

**Review by richtja — APPROVED** [review]
LGTM

**Comment by ana** [comment]
The change looks good but it's a bit confusing given that `perf.py` isn't included in  avocado. And when checking, I get the impression `avocado list` doesn't work:

In a fresh fedora 35 system:
```
[ana@fedora ~]$ git clone https://github.com/avocado-framework/avocado.git
Clonando en 'avocado'...
remote: Enumerating objects: 53003, done.
remote: Counting objects: 100% (718/718), done.
remote: Compressing objects: 100% (479/479), done.
remote: Total 53003 (delta 366), reused 428 (delta 234), pack-reused 52285
Recibiendo objetos: 100% (53003/53003), 18.89 MiB | 17.90 MiB/s, listo.
Resolviendo deltas: 100% (37356/37356), listo.

[ana@fedora ~]$ cd avocado/
[ana@fedora avocado]$ pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/ana/avocado
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Requirement already satisfied: setuptools in /usr/lib/python3.10/site-packages (from avocado-framework==94.0) (57.4.0)
Using legacy 'setup.py install' for avocado-framework, since package 'wheel' is not installed.
Installing collected packages: avocado-framework
    Running setup.py install for avocado-framework ... done
Successfully installed avocado-framework-94.0
[ana@fedora avocado]$ avocado
usage: avocado [-h] [-v] [--config [CONFIG_FILE]] [--enable-paginator] [-V] [--show CORE.SHOW]
               {assets,config,diff,distro,exec-path,jobs,list,plugins,replay,run,sysinfo,variants,vmimage} ...

[All good... skiping output ...]

[ana@fedora avocado]$ avocado list
[ana@fedora avocado]$ avocado list perf.py
[ana@fedora avocado]$ avocado -V list examples/gdb-prerun-scripts/
Type Test Tag(s)

Resolver             Reference                                Info
avocado-instrumented examples/gdb-prerun-scripts/README       File "examples/gdb-prerun-scripts/README" does not end with ".py"
exec-test            examples/gdb-prerun-scripts/README       File "examples/gdb-prerun-scripts/README" does not exist or is not executable
python-unittest      examples/gdb-prerun-scripts/README       File "examples/gdb-prerun-scripts/README" does not end with ".py"
tap                  examples/gdb-prerun-scripts/README       File "examples/gdb-prerun-scripts/README" does not exist or is not executable
avocado-instrumented examples/gdb-prerun-scripts/pass-sigusr1 File "examples/gdb-prerun-scripts/pass-sigusr1" does not end with ".py"
exec-test            examples/gdb-prerun-scripts/pass-sigusr1 File "examples/gdb-prerun-scripts/pass-sigusr1" does not exist or is not executable
python-unittest      examples/gdb-prerun-scripts/pass-sigusr1 File "examples/gdb-prerun-scripts/pass-sigusr1" does not end with ".py"
tap                  examples/gdb-prerun-scripts/pass-sigusr1 File "examples/gdb-prerun-scripts/pass-sigusr1" does not exist or is not executable

TEST TYPES SUMMARY
==================
[ana@fedora avocado]$ avocado -V list 
Type Test Tag(s)

TEST TYPES SUMMARY
==================
```

**Comment by clebergnu** [comment]
> The change looks good but it's a bit confusing given that `perf.py` isn't included in avocado. And when checking, I get the impression `avocado list` doesn't work:
> 

Many of those "example tests" are really not in our tree... that approach needs to change indeed, but there are just to many of those situations to tackle here.  I'll open an issue to track that.

`avocado list` works... but works differently than with the `--loader`.  With the `--loader`, it would default to use `datadir.paths.test_dir`.  It would work as you'd expect here (AFAICT) if you had a "discoverer" plugin enabled.

**Comment by ana** [comment]
> > The change looks good but it's a bit confusing given that `perf.py` isn't included in avocado. And when checking, I get the impression `avocado list` doesn't work:
> 
> Many of those "example tests" are really not in our tree... that approach needs to change indeed, but there are just to many of those situations to tackle here. I'll open an issue to track that.

Indeed, not for this PR, but we need to make that more clear in the documentation because when you show the running in the docs `avocado list` without any directory after and it work, it gives you the impression is using some example directory by default and a new user might not understand why they don't get the same output.

> `avocado list` works... but works differently than with the `--loader`. With the `--loader`, it would default to use `datadir.paths.test_dir`. It would work as you'd expect here (AFAICT) if you had a "discoverer" plugin enabled.

Yeah.

**Comment by ana** [comment]
I saw that packit wasn't working properly too late. Service seems to be back but didn't catch up in this PR.

**Pull request merged**
