### PR TITLE
Modify the CHECK_FILE_CONTAINS and CHECK_VERSION_REGEX fields of UnionTechProbe

### PR DESCRIPTION
**Pull request by faker-king**
Change /etc/os-version file information for uniontech OS

### CODE REVIEW

**Comment by clebergnu** [comment]
Hi @faker-king, thanks for this.  Could you please provide pointers to where/how the chance actually occurred in the distro?  Also, if this is a change in the distro itself, how will this cope with the detection of older distros?

It'd be helpful to add tests to the old and new scenario.

**Comment by faker-king** [comment]
>

**Comment by faker-king** [comment]
> Hi @faker-king, thanks for this. Could you please provide pointers to where/how the chance actually occurred in the distro? Also, if this is a change in the distro itself, how will this cope with the detection of older distros?
> 
> It'd be helpful to add tests to the old and new scenario.
Hi @clebergnu, Thank you for your question. I have tested all distributions of UOS and confirmed that the changes I made are correct

**Comment by clebergnu** [comment]
While we can't have functional test (such as in #5669) for all distros, let's manually verify if probes look alright.

From `uniontechos-desktop-21.0.1-home-amd64.iso` I got on `/etc/os-version`:

```
[Version] 
SystemName=UnionTech OS Desktop
SystemName[zh_CN]=统信桌面操作系统
ProductType=Desktop
ProductType[zh_CN]=桌面
EditionName=Home
EditionName[zh_CN]=家庭版
MajorVersion=20
MinorVersion=21.0.1
OsBuild=11078.101
```

And from `uniontechos-desktop-22.0-home-k510-amd64-env.iso` I got:

```
[Version] 
SystemName=UnionTech OS Desktop
SystemName[zh_CN]=统信桌面操作系统
ProductType=Desktop
ProductType[zh_CN]=桌面
EditionName=Home
EditionName[zh_CN]=家庭版
MajorVersion=20
MinorVersion=22.0
OsBuild=11078.110.100
```

**Review by clebergnu — APPROVED** [review]
While it wasn't possible to functionally test this, the changes look OK.  About matching to a version and a release, I can't tell what the distro actually considers them, so I'm trusting the author.

**Review by clebergnu — CHANGES_REQUESTED** [review]
Actually @faker-king I just noticed that this commit is lacking a 'Signed-off-by` line in the commit message.

Please make sure that running this: `./selftests/signedoff-check.sh; echo $?`, results in:

```
** Running signedoff-check...
0
```

Thanks!

**Comment by richtja** [comment]
> Actually @faker-king I just noticed that this commit is lacking a 'Signed-off-by` line in the commit message.
> 
> Please make sure that running this: `./selftests/signedoff-check.sh; echo $?`, results in:
> 
> ```
> ** Running signedoff-check...
> 0
> ```
> 
> Thanks!

Hi @faker-king there is avocado commit style in the [documentation](https://avocado-framework.readthedocs.io/en/latest/guides/contributor/chapters/styleguides.html#style-guides). It might be helpful for you :wink:

**Comment by faker-king** [comment]
@richtja Thank you for your help. I have added 'Signed off by' in the commit message However, it includes a synchronization of the code for avocado. If it has an impact, I can resubmit the pull request

**Review by PraveenPenguin — APPROVED** [review]

**Comment by faker-king** [comment]
@clebergnu Do you have any other questions? If not, can it be merged, We will use this change in our work

**Comment by richtja** [comment]
Hi @faker-king IMO we are safe enough to merge this and we don't have to wait for @clebergnu approval since all his points were addressed and we have already another two approvals.

**Pull request merged**
