### PR TITLE
Makefile: Add requirements-python26 [v2]

### PR DESCRIPTION
**Pull request by clebergnu**
This PR fixes an old issue with make install-requirements and adds Python2.6 requirements. It's based on #881 and on #916.

### CODE REVIEW

**Comment by clebergnu** [comment]
@lmr @ldoktor this is the result of the testing (and some tweaks) of #916. After those, a brand new EL 6 box can run the selftests (finally!) with:

* `make requirements-selftests`
* `python selftests/run`

The full `make check` still fails, mostly because of the `cyclical_deps` which depend on `networkx` which does not support Python 2.6. I'll disable it in another PR.

**Comment by lmr** [comment]
LGTM, merged!

**Comment by ldoktor** [comment]
Oh, too late... I like the work you did, makefile is way more user friendly. Only please reconsider the requirements handling. People can use `pip install -r ...` manually when makefile raises false-negative exceptions, but they ought to be notified.

**Comment by clebergnu** [comment]
@ldoktor the main issue here is that, if we choose to handle the failures, we may need an atomic way of doing so. What I mean is, based on my (quite extensive tests) just running `make install-requirements` would leave my system in different states. The reason is that, by using `xargs`, each requirement installation is run in a separate pip command. When one fails, another pip command is executed. *But* the next line in the Makefile target may not be executed because of such a failure.

It is really unpredictable. And I'd love to see it fixed. I just can't spent more time on that *right now*.

**Comment by ldoktor** [comment]
At least it notifies you that something went wrong. Now it leaves your system in totally unpredictable state and pretends everything went well. That is IMO worse.

Btw what makes you think we must support all or none handling? Even without xargs when installation of default requirements passes and 2.6 fails the system is in a different state but not capable of running avocado.

I think we should keep things simple and report failures which prevents users from running avocado. Then they can make steps to fix the issue. Otherwise they'll report weird bugs with half-stable solution, not mentioning that prerequirements might be not met.

**Comment by ldoktor** [comment]
^^ the multi-step also applies for unittests requirements. When they pass and requirements fails, the system has changed but we do not care. We just report this worked and this did not. The xargs only make pip work with multiple dependencies correctly.

**Pull request merged**
