### PR TITLE
Default log file for nrunner based tests [v2]

### PR DESCRIPTION
**Pull request by richtja**
This will save every nrunner messages from stdout and stderr to the debug.log with the proper tag on the beginning of each line, and it introduces the debug.log file as Default log file for nrunner.

Reference: #4804
Signed-off-by: Jan Richter jarichte@redhat.com

---
Changes form v1 (#4866)
* Docstring fixes
* StderrMessageHandler `_tag` fix
* Separated method for cheking incomplete lines

### CODE REVIEW

**Review by beraldoleal — APPROVED** [review]
LGTM, thanks.

**Comment by ana** [comment]
@richtja Hi, I have tested this and it doesn't work.

In a fresh VM:
```
git clone https://github.com/richtja/avocado 
cd avocado
git checkout default_log_file_v2 
make requirements-dev && make develop
....
[ana@fedora avocado]$ avocado run --test-runner nrunner  examples/tests/sleeptest.py examples/tests/passtest.py 
JOB ID     : 599025fcb17e080b1fb97907f15b7cf3293208e0
JOB LOG    : /home/ana/avocado/job-results/job-2021-08-24T14.40-599025f/job.log
 (1/2) examples/tests/sleeptest.py:SleepTest.test: STARTED
 (2/2) examples/tests/passtest.py:PassTest.test: STARTED
 (2/2) examples/tests/passtest.py:PassTest.test: PASS (0.01 s)
 (1/2) examples/tests/sleeptest.py:SleepTest.test: PASS (1.02 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/ana/avocado/job-results/job-2021-08-24T14.40-599025f/results.html
JOB TIME   : 1.87 s
[ana@fedora avocado]$ cat job-results/
job-2021-08-24T14.40-599025f/ latest/                       
[ana@fedora avocado]$ cat job-results/latest/
id            job.log       jobdata/      results.html  results.json  results.tap   results.xml   sysinfo/      test-results/ 
[ana@fedora avocado]$ cat job-results/latest/test-results/2-examples_tests_passtest.py_PassTest.test/debug.log 
2021-08-24 14:40:48,354 test             L0311 INFO | INIT 1-PassTest.test
2021-08-24 14:40:48,355 parameters       L0142 DEBUG| PARAMS (key=timeout, path=*, default=None) => None
2021-08-24 14:40:48,355 test             L0341 DEBUG| Test metadata:
2021-08-24 14:40:48,355 test             L0343 DEBUG|   filename: /home/ana/avocado/examples/tests/passtest.py
2021-08-24 14:40:48,355 test             L0349 DEBUG|   teststmpdir: /var/tmp/avocado_kiginjbt
2021-08-24 14:40:48,355 test             L0350 DEBUG|   workdir: /var/tmp/.avocado-task6lrobv0n/test-results/tmp_dirnngq9dnq/1-PassTest.test
2021-08-24 14:40:48,356 test             L0528 INFO | START 1-PassTest.test
2021-08-24 14:40:48,356 test             L0207 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
2021-08-24 14:40:48,357 test             L0207 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
2021-08-24 14:40:48,357 test             L0207 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
2021-08-24 14:40:48,357 test             L0207 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
2021-08-24 14:40:48,357 test             L0954 INFO | PASS 1-PassTest.test
2021-08-24 14:40:48,357 test             L0938 INFO | 

```

**Comment by richtja** [comment]
> @richtja Hi, I have tested this and it doesn't work.
> 
> In a fresh VM:
> 
> ```
> git clone https://github.com/richtja/avocado 
> cd avocado
> git checkout default_log_file_v2 
> make requirements-dev && make develop
> ....
> [ana@fedora avocado]$ avocado run --test-runner nrunner  examples/tests/sleeptest.py examples/tests/passtest.py 
> JOB ID     : 599025fcb17e080b1fb97907f15b7cf3293208e0
> JOB LOG    : /home/ana/avocado/job-results/job-2021-08-24T14.40-599025f/job.log
>  (1/2) examples/tests/sleeptest.py:SleepTest.test: STARTED
>  (2/2) examples/tests/passtest.py:PassTest.test: STARTED
>  (2/2) examples/tests/passtest.py:PassTest.test: PASS (0.01 s)
>  (1/2) examples/tests/sleeptest.py:SleepTest.test: PASS (1.02 s)
> RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
> JOB HTML   : /home/ana/avocado/job-results/job-2021-08-24T14.40-599025f/results.html
> JOB TIME   : 1.87 s
> [ana@fedora avocado]$ cat job-results/
> job-2021-08-24T14.40-599025f/ latest/                       
> [ana@fedora avocado]$ cat job-results/latest/
> id            job.log       jobdata/      results.html  results.json  results.tap   results.xml   sysinfo/      test-results/ 
> [ana@fedora avocado]$ cat job-results/latest/test-results/2-examples_tests_passtest.py_PassTest.test/debug.log 
> 2021-08-24 14:40:48,354 test             L0311 INFO | INIT 1-PassTest.test
> 2021-08-24 14:40:48,355 parameters       L0142 DEBUG| PARAMS (key=timeout, path=*, default=None) => None
> 2021-08-24 14:40:48,355 test             L0341 DEBUG| Test metadata:
> 2021-08-24 14:40:48,355 test             L0343 DEBUG|   filename: /home/ana/avocado/examples/tests/passtest.py
> 2021-08-24 14:40:48,355 test             L0349 DEBUG|   teststmpdir: /var/tmp/avocado_kiginjbt
> 2021-08-24 14:40:48,355 test             L0350 DEBUG|   workdir: /var/tmp/.avocado-task6lrobv0n/test-results/tmp_dirnngq9dnq/1-PassTest.test
> 2021-08-24 14:40:48,356 test             L0528 INFO | START 1-PassTest.test
> 2021-08-24 14:40:48,356 test             L0207 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
> 2021-08-24 14:40:48,357 test             L0207 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
> 2021-08-24 14:40:48,357 test             L0207 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
> 2021-08-24 14:40:48,357 test             L0207 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
> 2021-08-24 14:40:48,357 test             L0954 INFO | PASS 1-PassTest.test
> 2021-08-24 14:40:48,357 test             L0938 INFO | 
> ```

Hi @ana, I did the same test, and it's works fine for me, I am not able to reproduce it. Maybe @beraldoleal can you try it as well and give us your results?

```
[root@3f85fa4887f8 avocado]# cat ~/avocado/job-results/latest/test-results/2-examples_tests_passtest.py_PassTest.test/debug.log 
[debug] 2021-08-24 13:30:18,637 test             L0312 INFO | INIT 1-PassTest.test
[debug] 2021-08-24 13:30:18,638 parameters       L0142 DEBUG| PARAMS (key=timeout, path=*, default=None) => None
[debug] 2021-08-24 13:30:18,638 test             L0340 DEBUG| Test metadata:
[debug] 2021-08-24 13:30:18,638 test             L0342 DEBUG|   filename: /avocado/examples/tests/passtest.py
[debug] 2021-08-24 13:30:18,639 test             L0348 DEBUG|   teststmpdir: /var/tmp/avocado_qxqfyw8k
[debug] 2021-08-24 13:30:18,639 test             L0538 INFO | START 1-PassTest.test
[debug] 2021-08-24 13:30:18,639 test             L0207 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
[debug] 2021-08-24 13:30:18,640 test             L0207 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
[debug] 2021-08-24 13:30:18,640 test             L0207 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
[debug] 2021-08-24 13:30:18,640 test             L0207 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
[debug] 2021-08-24 13:30:18,640 test             L0965 INFO | PASS 1-PassTest.test
[debug] 2021-08-24 13:30:18,640 test             L0949 INFO | 
```

**Comment by ana** [comment]
@richtja Also it works here using a GitHub Action:
https://github.com/ana/jan-avocado/actions/runs/1162821822

Ignore my comment, I'll investigate what I'm doing wrong locally 🕵🏻‍♀️

**Review by ana — APPROVED** [review]

**Comment by willianrampazzo** [comment]
I had an ongoing review here, but I did not have time to submit the comments. I will leave them for a future PR.

**Comment by richtja** [comment]
@willianrampazzo sorry, I said to @beraldoleal that we are good to go here. Please send me your comments and I can prepare new PR

**Pull request merged**
