### PR TITLE
Add pydot to selftests requirements

### PR DESCRIPTION
**Pull request by olavphibm**
"make check" needs pydot to run.

### CODE REVIEW

**Comment by ldoktor** [comment]
yep, you're right. Although this would generate problems, because the default dependency is `pyparsing`, which in the latest version does not work well with the `pydot`. I'm wondering if they fix it soon or if we should specify strict versions...

^^ the problem is that `pip install pydot` installs `pyparsing-2.0.6` and `import dot_parser` fails. You have to install eg. `pyparsing==1.5.2` and it'll start working again. Anyway the bug is reported so it should start working with the future releases.

**Comment by clebergnu** [comment]
Tested on a venv without pydot and you're indeed right! Thanks!

**Comment by clebergnu** [comment]
Oh, I did not see @ldoktor comments. Let me check why/how the `pyparsing` dep behaves on my system.

**Comment by ldoktor** [comment]
I tried it, the default is `pyparsing-2.0.6` which fails. Anyway I hope they'll fix it soon...

**Comment by ldoktor** [comment]
and travis should use different requirements with strict versions, so it should be OK.

**Comment by ldoktor** [comment]
Hmm, btw travis does not state pydot and it works. Isn't pydot a dependency of another component?

**Comment by clebergnu** [comment]
Yep, I only checked that pydot was indeed necessary, but did not test the failure of enabling it:

```
Couldn't import dot_parser, loading of dot files will not be possible.
Traceback (most recent call last):
  File "selftests/cyclical_deps", line 76, in <module>
    has_cycles = cyclical_deps(dot)
  File "selftests/cyclical_deps", line 60, in cyclical_deps
    graph = nx.DiGraph(nx.read_dot(path_dot))
  File "<decorator-gen-234>", line 2, in read_dot
  File "/tmp/venv/lib/python2.7/site-packages/networkx/utils/decorators.py", line 220, in _open_file
    result = func(*new_args, **kwargs)
  File "/tmp/venv/lib/python2.7/site-packages/networkx/drawing/nx_pydot.py", line 81, in read_dot
    P = pydot.graph_from_dot_data(data)
  File "/tmp/venv/lib/python2.7/site-packages/pydot.py", line 199, in graph_from_dot_data
    return dot_parser.parse_dot_data(data)
NameError: global name 'dot_parser' is not defined
```

Anyway, since travis is happy and you mention this is a `pyparsing` related issue, let's keep an eye on it.

**Comment by clebergnu** [comment]
@ldoktor it looks like it, yes. On my system it was available from packages, but I did not check were it was actually pulled (as a dependency) from.

**Comment by clebergnu** [comment]
@ldoktor I mean, besides being a `python-networkx` dep.

**Comment by olavphibm** [comment]
I didn't have it in my system, so it probably isn't a dep from any of the avocado required packages.

**Comment by ldoktor** [comment]
yep, it is not. I think it's best to leave it as you did it. It's an pip issue, not ours. I'm wondering, though, why it works in travis... Maybe they have it installed by default.

**Comment by clebergnu** [comment]
Funny stuff! `dot_parser.py` (from `pydot-1.0.28-6.fc21.noarch`) has this:

```
_noncomma = "".join( [ c for c in printables if c != "," ] )
```

While the "latest" version installed from pip attempts to import that from pyparsing. We all know is probably a bad idea to be importing stuff that starts with `_`. I'll check if upstream `pydot` is handling this.

**Comment by clebergnu** [comment]
@ldoktor yes, they most probably have it in by default in their images.

**Comment by clebergnu** [comment]
Just one final info, the fix is actually on the Fedora package (`pydot-1.0.28-pyparsing2fix.patch`):

```
diff -up pydot-1.0.28/dot_parser.py.pyparsing2fix pydot-1.0.28/dot_parser.py
--- pydot-1.0.28/dot_parser.py.pyparsing2fix    2013-12-09 08:59:24.660145534 -0500
+++ pydot-1.0.28/dot_parser.py  2013-12-09 09:00:10.021222397 -0500
@@ -25,8 +25,9 @@ from pyparsing import __version__ as pyp
 from pyparsing import ( nestedExpr, Literal, CaselessLiteral, Word, Upcase, OneOrMore, ZeroOrMore,
     Forward, NotAny, delimitedList, oneOf, Group, Optional, Combine, alphas, nums,
     restOfLine, cStyleComment, nums, alphanums, printables, empty, quotedString,
-    ParseException, ParseResults, CharsNotIn, _noncomma, dblQuotedString, QuotedString, ParserElement )
+    ParseException, ParseResults, CharsNotIn, dblQuotedString, QuotedString, ParserElement )
 
+_noncomma = "".join( [ c for c in printables if c != "," ] )
 
 class P_AttrList:
```

Upstream should catch this.

**Pull request merged**
