### PR TITLE
typo fix: ommit -> omit

### PR DESCRIPTION
**Pull request by ana**
I'm hoping we still can fix this configuration option since it has never been released.
This was caught by a weekly run of codespell I'm running in my fork.

### CODE REVIEW

**Review by beraldoleal — APPROVED** [review]

**Review by willianrampazzo — APPROVED** [review]

**Comment by beraldoleal** [comment]
Merging before the release.

**Comment by beraldoleal** [comment]
Ops @ana I just realized that you explicitly asked for @clebergnu comments. My bad.

**Comment by clebergnu** [comment]
> Ops @ana I just realized that you explicitly asked for @clebergnu comments. My bad.

No worries, this was the right and obvious fix!

**Comment by ana** [comment]
@clebergnu @beraldoleal great, thanks!

**Pull request merged**
