### PR TITLE
Loader make unittests run

### PR DESCRIPTION
**Pull request by lmr**
Proposed solution for the card:

https://trello.com/c/GwjMV3l7/455-bug-avocado-can-t-run-python-unittests-that-have-no-exec-permission

### CODE REVIEW

**Comment by ldoktor** [comment]
Well it does the job, when the unittest contains `if __name__ ...`. If not, it simply `PASS` of `FAIL` (in case of syntax error). IMO it's a bit dangerous as one might rely on the results:

```python
import sys

if sys.version_info[:2] == (2, 6):
    import unittest2 as unittest
else:
    import unittest


class TestCase(unittest.TestCase):
    def test_aaa(self):
        raise Exception("asdf")
```
```
avocado run /tmp/a.py 
JOB ID     : 97d7cc74343d2c5b6f6db3682973fb825ee665e8
JOB LOG    : /home/medic/avocado/job-results/job-2015-10-16T14.20-97d7cc7/job.log
TESTS      : 1
 (1/1) /tmp/a.py: PASS (0.05 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
JOB HTML   : /home/medic/avocado/job-results/job-2015-10-16T14.20-97d7cc7/html/results.html
TIME       : 0.05 s
```

I'm more and more inclined to having `avocado list` with ast detection used to see what is there (eg. verbose mode is sometimes useful) and `run` (with --dry-run) which loads the code and returns proper results including the security hazards.

@clebergnu, @areis, what do you think?

**Comment by clebergnu** [comment]
Experiment is over, and I have bad news. `unittest` based discovery actually loads (imports/executes) the modules. First `unittest_loader.py` was created:

```
#!/usr/bin/env python

import sys
from unittest import loader

if __name__ == '__main__':
    l = loader.TestLoader()
    print l.discover(sys.argv[1], pattern=sys.argv[2])
```

Then the directory to look for tests was created:

```
$ mkdir /tmp/foo
$ touch /tmp/foo/__init__.py
$ echo 'import time; time.sleep(10)' > /tmp/foo/test_t.py
```

Then it was run like this:

```
time python unittest_loader.py /tmp/foo test_t.py
<unittest.suite.TestSuite tests=[<unittest.suite.TestSuite tests=[]>]>

real    0m10.059s
user    0m0.040s
sys     0m0.009s
```

So `time.sleep(10)` was eval'd. The culprit is `_get_module_from_name()` from `unittest.loader.TestLoader` and also another `__import__` call on `unittest.loader.TestLoader.discover()`.

So our `ast` based test discovery is actually safer than standard Python unittest discovery.

**Comment by lmr** [comment]
@clebergnu, yep, that one was a given. It's unpractical to say the least to try to correctly guess the tests within a python file without loading said python file. Our `ast` based file is a safer approximation, which I think people can appreciate.

**Comment by ldoktor** [comment]
Yes, unittest loads the test to discover it, because you're executing the test. But we support `avocado list` to see only the possible variants. That's why I suggest using 2 discovery methods and use `ast`-based in `list` and `import`-based when running it and in `dry-run`.

**Comment by ldoktor** [comment]
I mean we can improve our heuristic, but we won't be able to cover everything. One of the harder-to-find usecases would be dynamic class:

```python
def get_test(name):
    ...

class Dynamic(Test):
    def __init__(self, config):
        for tst in open(config, "r").readlines():
            setattr(self, tst, get_test(tst))
```
which would only contain `test*` methods after `__init__` is executed. (yes, it's ugly, but with some modifications it's sometimes used...)

**Comment by clebergnu** [comment]
@ldoktor Yep, I think we should just keep the same approach of supporting the obvious and letting the real smart users to handle the issue themselves.

WRT list/dry-run, we either need that separation and have the two commands, or have a single one and introduce something like `--no-safe-{discovery/load}` because the `ast` and `import` based results will surely be different sometimes.

**Comment by ldoktor** [comment]
The more I think about it I considering having only the unsafe version. Because when the user is idiot and wants to probe nasty code, than he deserves the screwed-up system. Normal people probe only tests they intend to run and tests they intend to run will eventually be executed.

So ast-based discover is pretty cool and surely can be extended of something similar to `ast.literal_eval` to probe for even more code. But even that would not cover 100% and would be eventually prone to some malicious code.

All in all I'd focus on real users who want to run they tests rather than on avocado-qa who want to find the corner-case which breaks it. We should probably even remove the stdout/stderr hacks to notify users their tests are written badly (or replace them with iostring and raise exception when they were used during discovery) and we might add test-discover-timeout to timeout in case the discovery takes longer than xxx.

**Comment by lmr** [comment]
@ldoktor I wouldn't be so hard on users trying out directory probing test functionality. With that said, no other test running system that I know does probing of tests using indirect methods such as ast detection, since it's not exactly reliable. Having `list` using `ast` based detection and `dry-run` using real import seems like a nice compromise to me.

**Comment by ldoktor** [comment]
Yep, it also struct me that we should probably get rid of list and use only `--dry-run`. But we could implement `discover` which would be the safe ast-based discovery and it would only support basic test discovery, without multiplexation, without remote or inner-runner options. The purpose would be purely to do the basic discovery when you have some doubts.

`discover` would actually be parallel to `multiplex`. I mean `run` supports `--multiplex` and `multiplex` does it a bit different way (with additional features. One is supposed to be used to play with multiplexation, to query for details, to debug it, the other to run multiplexed tests. The same way `discover` would be used to debug test discovery safely and to show additional output and `--dry-run` would be used to load the tests and see the real results.

**Comment by lmr** [comment]
Well guys, since we ended up deciding that the unittest detection should be done elsewhere, I'm closing this PR (I've separated the cleanup commits into a new PR).

**Pull request closed without merging**
