### PR TITLE
add probe for uos systems in general

### PR DESCRIPTION
**Pull request by shilei522**
add probe for uos systems in general
UnionTech is the name of the company ,Uos is the name of the operating system.
UnionTech Software Technology Co., Ltd. is a domestic basic software company, which was jointly established by operating system manufacturers in 2019 [3]. The company focuses on the development and service of operating system and other basic software, and is committed to providing operating system products and solutions for users in different industries.

Signed-off-by: shilei <shileib@uniontech.com>

### CODE REVIEW

**Comment by shilei522** [comment]
@ana

**Comment by shilei522** [comment]
@ana ,Help me fix the build failure, my code should not affect the build

**Comment by ana** [comment]
Hi @shilei522, rebasing this pull request should get the fixes to run the checks. The current problem is indeed unrelated to your change, you have more information at https://github.com/avocado-framework/avocado/issues/5105

**Comment by shilei522** [comment]
@ana ,why? Why did it fail again?before build success ,What should I do ?

**Comment by ana** [comment]
> @ana ,why? Why did it fail again?before build success ,What should I do ?

You didn't fully rebase ( branch is 3 commits ahead, 33 commits behind avocado-framework:master) 
You can browse the error messages looking at the logs of the github actions:
```

2021-11-15T07:28:42.5692503Z RESULTS    : PASS 1042 | ERROR 0 | FAIL 3 | SKIP 45 | WARN 0 | INTERRUPT 0 | CANCEL 0
2021-11-15T07:28:42.8166580Z JOB HTML   : /home/runner/avocado/job-results/job-2021-11-15T07.20-c413417/results.html
2021-11-15T07:28:42.8979009Z JOB TIME   : 499.09 s
2021-11-15T07:28:42.9032913Z Log file "debug.log" content for test "check-924-selftests/lint.sh" (FAIL):
2021-11-15T07:28:42.9033912Z [stdout] ** Running lint...
2021-11-15T07:28:42.9034604Z [stdout] ************* Module avocado.utils.distro
2021-11-15T07:28:42.9035971Z [stdout] avocado/utils/distro.py:450:0: E0102: class already defined line 438 (function-redefined)
2021-11-15T07:28:42.9036778Z [stdout] 
2021-11-15T07:28:42.9037464Z [stdout] ------------------------------------
2021-11-15T07:28:42.9038094Z [stdout] Your code has been rated at 10.00/10
2021-11-15T07:28:42.9038626Z [stdout] 
2021-11-15T07:28:42.9038988Z 
2021-11-15T07:28:42.9039881Z Log file "debug.log" content for test "check-927-selftests/inspekt-style.sh" (FAIL):
2021-11-15T07:28:42.9040856Z [stdout] ** Running inspekt-style...
2021-11-15T07:28:42.9041616Z [stdout] ./avocado/utils/distro.py:438:1: E302 expected 2 blank lines, found 1
2021-11-15T07:28:42.9042330Z [stderr] PEP8 disabled: E501,E402,E722
2021-11-15T07:28:42.9042975Z [stderr] Style: ./avocado/utils/distro.py FAIL 
2021-11-15T07:28:42.9043602Z [stderr] PEP8 compliance FAIL
2021-11-15T07:28:42.9044027Z 
2021-11-15T07:28:42.9044856Z Log file "debug.log" content for test "check-930-selftests/spell.sh" (FAIL):
2021-11-15T07:28:42.9045597Z [stdout] ** Running spell check...
2021-11-15T07:28:42.9046253Z [stdout] ************* Module avocado.utils.distro
2021-11-15T07:28:42.9047234Z [stdout] avocado/utils/distro.py:440:0: C0402: Wrong spelling of a word 'uos' in a docstring:
2021-11-15T07:28:42.9048716Z [stdout]     Simple probe for uos systems in general
2021-11-15T07:28:42.9049308Z [stdout]                      ^^^
2021-11-15T07:28:42.9050230Z [stdout] Did you mean: ''sou' or 'ups' or 'us' or 'duos''? (wrong-spelling-in-docstring)
2021-11-15T07:28:42.9051302Z [stdout] avocado/utils/distro.py:452:0: C0402: Wrong spelling of a word 'uos' in a docstring:
2021-11-15T07:28:42.9052022Z [stdout]     Simple probe for uos systems in general
2021-11-15T07:28:42.9052551Z [stdout]                      ^^^
2021-11-15T07:28:42.9053607Z [stdout] Did you mean: ''sou' or 'ups' or 'us' or 'duos''? (wrong-spelling-in-docstring)
2021-11-15T07:28:42.9054195Z 
2021-11-15T07:28:42.9054617Z Failed tests:
2021-11-15T07:28:42.9055259Z check-924-selftests/lint.sh FAIL
2021-11-15T07:28:42.9056066Z check-927-selftests/inspekt-style.sh FAIL
2021-11-15T07:28:42.9056860Z check-930-selftests/spell.sh FAIL
2021-11-15T07:28:43.0278222Z make: *** [Makefile:93: check] Error 1
2021-11-15T07:28:43.0288774Z ##[error]Process completed with exit code 2.
```

**Pull request closed without merging**
