### PR TITLE
Add requirements install for python 2.6

### PR DESCRIPTION
**Pull request by lmr**
Add handling dependencies install on python 2.6. This is a proposal to resolve issue #880.

Please check this thoroughly, as I had to write it on a rush (I'm having a bit of a hectic week around here).

### CODE REVIEW

**Comment by ldoktor** [comment]
Hmm, nice and complicated. I think when someone is installing it from sources, he should be skilled enough to sort the dependencies. We do support official ways (even boarder than usual), adding the "perfect" script to deploy everywhere tends to be prone to problems in the future.

For me, simple sentence `Don't trick your packaging system, use "make rpm" or "make build-deb-bin" whenever possible.` and only keep one `requirements.txt` for running avocado, `requirements-selftests.txt` for running selftests/development and `requirements-travis.txt` for handling CI. If we really want to be nice, we can add commented lines with explanation `Uncomment this if you run python 2.6`.

Yes, if there is a great need for it, we can even ad `requirements-python26.txt`, but I don't think it's needed to be invoked automatically. Users use packaging system. Developers should use packaging system and if not they should be able to find out what is missing.

**Comment by clebergnu** [comment]
I beg to differ. `requirements.txt` and friends are pretty standard these days, and, supporting Python 2.6 means we do just that, support it.

It's not an easy thing to do, neither it brings much pleasure, and we may end up failing to get everything right all the time. But, let's think of the Python 2.6 version of the requirements files as a aggregate of knowledge developers share about what they "know" they should install. If a developer fails to get Avocado running out of a `pip install -r requirements.txt` than he should really send a minor patch.

Talking to myself: this should actually help to improve my discipline when adding new requirements and properly test them in both Python 2.7 and above, and also add the relevant dependency package names to the package formats we support out of tree.

**Comment by ldoktor** [comment]
well then we should just support `requirements.txt` and `requirements-python26.txt` and either support targets in `Makefile` for booth, or choose them in the `Makefile`. But I don't see a reason for yet another python script to do some magic.

**Comment by lmr** [comment]
OK guys, sorry, things have been hectic here, I'll get back to my Pull Requests (such as this one) now.

**Comment by ldoktor** [comment]
Oh I did commented on this one, sorry for reentering the same complain (I got notification on GH, read it and forgot I already saw it...).

Anyway you booth want to have python-2.6 requirements so how about this:

```
grep -v '^#' requirements.txt | xargs -n 1 pip install --upgrade
[[ "$(python -V 2>&1)" =~ "2.6" ]] && grep -v '^#' requirements-2.6.txt | xargs -n 1 pip install --upgrade
```

and put only the additional packages to `requirements-2.6`, not the full list of dependencies as proposed here (the same way `travis-2.6` is generated. What do you think?

**Comment by lmr** [comment]
@ldoktor sure, I have no problem with that. You can send the patch and then I'll approve it!

**Pull request closed without merging**
