### PR TITLE
drop output-check-record feature

### PR DESCRIPTION
**Pull request by beraldoleal**
This feature is deprecated and also only works with the legacy runner. In order to implement a new version of this with the new runner architecture would be nice to have a nice "fresh start" and avoid having legacy code. If this makes sense, new tests will be introduced when implementing the new version of this feature, described at #3882.

Signed-off-by: Beraldo Leal <bleal@redhat.com>

### CODE REVIEW

**Comment by ana** [comment]
LGTM. There are still some left overs in `selftests/functional/test_output_check.py`  and `man/avocado.rst`

**Comment by beraldoleal** [comment]
> LGTM. There are still some left overs in `selftests/functional/test_output_check.py` and `man/avocado.rst` And `avocado/core/test.py: process.OUTPUT_CHECK_RECORD_MODE = 'combined'`

Maybe those are fixed with the new PR.

**Comment by beraldoleal** [comment]
I found some of the leftovers on man/avocado.rst. Please let me know if you are catching something that I'm missing.

**Comment by clebergnu** [comment]
@beraldoleal FYI, that are some tests still failing on CI.

**Comment by ana** [comment]
> @ana, I just fixed the `avocado/core/test.py` with a force-push. Thanks. Can you point the other left overs? under test_output_check.py and man/avocado.rst?

Thanks. it seems ok now!

**Comment by beraldoleal** [comment]
@clebergnu some issues with cirrus, just restarted and it is working now.

**Review by richtja — CHANGES_REQUESTED** [review]
LGTM

**Review by richtja — APPROVED** [review]

**Pull request merged**
