### PR TITLE
Avocado replay command configuration fix

### PR DESCRIPTION
**Pull request by richtja**
This is and fix for storing job configuration values into the record. This bug was causing problems with replay command reported in #5060. This PR reserve a dict with key `__set__` as a flag for `set` type inside job configuration record. With this change the `sets` can be saved and restored from job configuration records, which wasn't possible before.

### CODE REVIEW

**Comment by clebergnu** [comment]
Apart from what @beraldoleal spotted (`s/$s/%s`), it LGTM.

**Comment by willianrampazzo** [comment]
> Apart from what @beraldoleal spotted (`s/$s/%s`), it LGTM.

Same here, so what if we change that while merging or force pushing the change here? Then we can merge it today.

**Comment by clebergnu** [comment]
> > Apart from what @beraldoleal spotted (`s/$s/%s`), it LGTM.
> 
> Same here, so what if we change that while merging or force pushing the change here? Then we can merge it today.

I don't think @richtja would be against it.  Are you volunteering :wink: ?

**Comment by willianrampazzo** [comment]
> > > Apart from what @beraldoleal spotted (`s/$s/%s`), it LGTM.
> > 
> > 
> > Same here, so what if we change that while merging or force pushing the change here? Then we can merge it today.
> 
> I don't think @richtja would be against it. Are you volunteering wink ?

Done!

@beraldoleal would you approve it?

**Review by willianrampazzo — APPROVED** [review]

**Review by beraldoleal — APPROVED** [review]

**Comment by richtja** [comment]
@willianrampazzo thanks for the force-push :blush:

**Pull request merged**
