### PR TITLE
Silence broken plugins

### PR DESCRIPTION
**Pull request by lmr**
Implement Trello card:

https://trello.com/c/8Yth6z9a/399-allow-broken-plugins-to-be-silenced-by-configuration

Although my solution is a bit more flexible than what's described in the card. Let's discuss.

### CODE REVIEW

**Comment by clebergnu** [comment]
I like the approach, and only miss the "catchall" option.

**Comment by lmr** [comment]
I don't like the idea of catchalls, since treating problems individually helps with reviewing why each plugin has problems, and if new plugins get installed by the sysadmin and they also happen to have problems, the user will see the new errors and review if it's worth it to disable the error notifications for the new plugin.-

But if ultimately you feel like the catchall is A Good Thing (TM), I see no problem in adding one. I wonder what would be best -> `['all']`, `[*]`, or simply `all`/`*`

**Comment by clebergnu** [comment]
OK, I felt that the catchall was kind of necessary to implement what was described in the card. But I do agree it's not super important. Are you going to send a rebased version of this?

**Comment by lmr** [comment]
@clebergnu, yes, I'm working on it

**Comment by lmr** [comment]
Closing in favor of #653

**Pull request closed without merging**
