### PR TITLE
Tests: drop somewhat obvious prefixes

### PR DESCRIPTION
**Pull request by clebergnu**
Python based test filenames all contain a `test_` prefix, which is unnecessary.

These changes free up some space in job reports, test result directories, etc.  Also it aims to sync with a proposal for the autils repo, in which we'd have:

 * module: `autils/category/module.py`
 * test: `tests/autils/category/module.py`
 * metadata: `metadata/autils/category/module.yaml`

### CODE REVIEW

**Review by richtja — CHANGES_REQUESTED** [review]
Hi @clebergnu, thank you for this. It is very useful refactoring.

I haven't gone thought the changes yet, but I ran a script to count number of avocado selftests before and after your changes. On master, we have `1192` tests, but in this PR we have only `976` tests. So it is looks like we are missing some tests here. Can you please check this. Thank you.

**Comment by clebergnu** [comment]
> Hi @clebergnu, thank you for this. It is very useful refactoring.
> 
> I haven't gone thought the changes yet, but I ran a script to count number of avocado selftests before and after your changes. On master, we have `1192` tests, but in this PR we have only `976` tests. So it is looks like we are missing some tests here. Can you please check this. Thank you.

Wow, good catch, I'll check what's going on.

**Comment by clebergnu** [comment]
> > Hi @clebergnu, thank you for this. It is very useful refactoring.
> > I haven't gone thought the changes yet, but I ran a script to count number of avocado selftests before and after your changes. On master, we have `1192` tests, but in this PR we have only `976` tests. So it is looks like we are missing some tests here. Can you please check this. Thank you.
> 
> Wow, good catch, I'll check what's going on.

Found out what the issue was.  Quick fix with:

```diff
diff --git a/selftests/check.py b/selftests/check.py
index b032f284e..93efec484 100755
--- a/selftests/check.py
+++ b/selftests/check.py
@@ -674,7 +674,7 @@ def create_suites(args):  # pylint: disable=W0621
 
     if args.dict_tests["functional"]:
         functional_path = os.path.join("selftests", "functional")
-        references = glob.glob(os.path.join(functional_path, "test*.py"))
+        references = glob.glob(os.path.join(functional_path, "*.py"))
         references.extend(
             [
                 os.path.join(functional_path, "utils"),
```

**Review by richtja — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
