### PR TITLE
Safe(r) test loader

### PR DESCRIPTION
**Pull request by clebergnu**
Currently, the test loader will load/execute the Python test files at discovery time. This is not desirable because, among other things, it's unsafe to execute code that was not explicitly requested to be executed.

The new approach is to use the `ast` module and parse, but not execute, the Python source code files, and attempt to use some heuristics to detect an Avocado INSTRUMENTED test.

Since the current loader is too tightly coupled to the idea of having test classes and parameters (which implies having loaded the code) as the building blocks of tests, this new approach gives the system class names only. Also, since the code is not loaded, the path to the source code file is given inside the test parameters (and later pulled out). A more complete solution would be to redesign the Loader so that it gives test information only at discovery time for *all* test types.

Since there's another major work going on in the loader at this time, I decided to keep things simple(r) and just deal with the string based "classes" when necessary.

Also included (transparently) is the support for multiple classes with multiple tests inside a single Python source code file.

### CODE REVIEW

**Comment by adereis** [comment]
Remember you have to update docs/source/diagram.png (and maybe docs/source/ReferenceGuide.rst, which references it)

**Comment by clebergnu** [comment]
@adereis I'd suggest we update the `diagram.png` file once every release, if not, most PRs will introduce a binary file change, which, IMHO, is undesirable.

**Comment by adereis** [comment]
@clebergnu I think you're confusing `diagram.png` with `modules.png`. The former is part of the documentation about the resolution algorithm used by Avocado's loader, while the latter is the list of python modules in Avocado (personally, I would remove this one from the repository).

**Comment by clebergnu** [comment]
@adereis right! I did mix the two up.

**Comment by lmr** [comment]
Everything is safe and sound here. Once again, the next PR from @ldoktor might be affected here, but this is already in good working condition. Great work @clebergnu !

**Pull request merged**
