### PR TITLE
Fix isort 5 issues [v2]

### PR DESCRIPTION
**Pull request by willianrampazzo**
Travis has moved to `isort` 5. Our `isort` check needs a small change to work correctly.

Also, fixed new failures.

Signed-off-by: Willian Rampazzo <willianr@redhat.com>

Changes from v1:
- Fix new and old failures,

### CODE REVIEW

**Review by richtja — CHANGES_REQUESTED** [review]
IIUIC this solution is compatible with isort>=5 but in `requirements-selftests.txt` we are using isort==4.3.21 and pylint==2.5.0 unfortunately pylint 2.5.0 requires isort<5,>=4.2.5 IMO this solution is incompatible with our self tests requirements.

**Comment by willianrampazzo** [comment]
> IIUIC this solution is compatible with isort>=5 but in `requirements-selftests.txt` we are using isort==4.3.21 and pylint==2.5.0 unfortunately pylint 2.5.0 requires isort<5,>=4.2.5 IMO this solution is incompatible with our self tests requirements.

I did some testing and, indeed, the output from `isort` 4 and `isort` 5 are different. `isort` 5 fixes are incompatible with `isort` 4.

I'm fine if we stick to `isort` 4. I'm wondering why Travis installed `isort` 5.

**Comment by beraldoleal** [comment]
> > IIUIC this solution is compatible with isort>=5 but in `requirements-selftests.txt` we are using isort==4.3.21 and pylint==2.5.0 unfortunately pylint 2.5.0 requires isort<5,>=4.2.5 IMO this solution is incompatible with our self tests requirements.
> 
> I did some testing and, indeed, the output from `isort` 4 and `isort` 5 are different. `isort` 5 fixes are incompatible with `isort` 4.
> 
> I'm fine if we stick to `isort` 4. I'm wondering why Travis installed `isort` 5.

If we can install easily isort 5 on major distros, we can also upgrade our requirements to install isort 5.

**Comment by willianrampazzo** [comment]
> > > IIUIC this solution is compatible with isort>=5 but in `requirements-selftests.txt` we are using isort==4.3.21 and pylint==2.5.0 unfortunately pylint 2.5.0 requires isort<5,>=4.2.5 IMO this solution is incompatible with our self tests requirements.
> > 
> > 
> > I did some testing and, indeed, the output from `isort` 4 and `isort` 5 are different. `isort` 5 fixes are incompatible with `isort` 4.
> > I'm fine if we stick to `isort` 4. I'm wondering why Travis installed `isort` 5.
> 
> If we can install easily isort 5 on major distros, we can also upgrade our requirements to install isort 5.

Right, but @richtja mentioned `pylint` 2.5 depends on `isort` 4. We need to also evaluate if we can bump the `pylint` version, if there is a new version.

**Comment by willianrampazzo** [comment]
Initially, I thought the `isort` problem of #4369 was related to the version of `isort`, as I had version 5 locally, and it was also failing due to command syntax. It turned out that #4369 had a failure on `isort` 4, but not on `isort` 5 from my machine. I fixed the code on #4369, and the checks are passing now. In this case, this PR is not needed at this moment.

The open question is still why this PR passed the `isort` check if it was supposed to run on `isort` 4, which should be incompatible with this PR syntax and fixes.

**Pull request closed without merging**
