### PR TITLE
Avocado Coverage.py updates

### PR DESCRIPTION
**Pull request by richtja**
This PR does some simplification of caverage.py usage with avocado. And fixes avocado issue related to this topic:

1. It simplifies the way how coverage.py is used with avocado-instrumented tests #5919 
2. Adds coverage.py support for python unittests #4957
3. Use ./selftests/check.py entry point for running avocado coverage job in CI #4992

### CODE REVIEW

**Review by harvey0100 — APPROVED** [review]
Looks good to me :)

**Review by clebergnu — APPROVED** [review]
LGTM, thanks!

**Comment by arif-ali** [comment]
How would you feel about back porting this to the LTS? We would appreciate it, and we can go fully avocado

**Comment by richtja** [comment]
> How would you feel about back porting this to the LTS? We would appreciate it, and we can go fully avocado

Hi @arif-ali this was created based on your comments in https://github.com/avocado-framework/avocado/discussions/5610#discussioncomment-9156337, can you please try it out in your environment? If it works, I don't see a problem with the backport to LTS.

**Pull request merged**
