### PR TITLE
Test API: Isolate avocado.restclient from being used by test developers.

### PR DESCRIPTION
**Pull request by ruda**
Move avocado.restclient to avocado.core.restclient, in conformance
to our purpose of keeping things not related to test developers,
inside avocado.core, isolated from users.

Signed-off-by: Rudá Moura <rmoura@redhat.com>

### CODE REVIEW

**Comment by clebergnu** [comment]
Actually, a part of the `avocado.restclient` is intended for end users, not necessarily to write tests, but to interact with the server in a simpler and standard way.

The idea here should be to keep the examples at `examples/api/restclient` working. Later, as the `restclient` API evolves, it may include more examples and documentation, for example, on how to get/put notes or attachments on test results already at the server. These things may not be part of test themselves, but I anticipate they will certainly be useful to Avocado users.

So, I'd move `avocado.restclient.cli` to `avocado.core.restclient.cli`, but keep in `avocado.restclient`:
* `connection.py`
* `response.py`

The only issue here, is that we should keep in mind, and tell users that everything in `avocado.*`, excluding `avocado.core.*` is targeted to users, but not only for writing tests.

Let me know what you think.

**Comment by clebergnu** [comment]
@ruda this is what I meant in the suggestion/discussion:

https://github.com/clebergnu/avocado/commit/aae2bb072cea63c32489bb0a3fda3a4a669bd16a

If you agree with it, feel free to squash that into your commit and send a v2. If you want, I can even do that.

Thanks.

**Comment by clebergnu** [comment]
Actually, I forgot to `git add __init__.py`, so, it would actually be something like this:

https://github.com/clebergnu/avocado/commit/155b962ce6e0b3aca6eab7de725355d675b99773

**Comment by ruda** [comment]
Looks good, let's do it the way you've talked.

**Comment by ruda** [comment]
Closing this, in favor of #594

**Pull request closed without merging**
