### PR TITLE
Lint: enable W0612 and W0622 checks [v2]

### PR DESCRIPTION
**Pull request by clebergnu**
These warnings are described as:
    
* W0612: Used when a variable is defined but not used.
* W0622: Used when a variable or function override a built-in.

---

Changes from v1 (#2517):
 * Document `s/MemoryError/MemError/` change in  next LTS release notes

### CODE REVIEW

**Comment by ldoktor** [comment]
@clebergnu would you please address the:

```
************* Module avocado.core.test
W0612:407,12: Test.__init__: Unused variable 'teststmpdir'
```

in the last commit?

**Comment by clebergnu** [comment]
@ldoktor that is really weird, see, from commit:

```
$ git rev-parse HEAD
12c85fc0613c810fb8f89ae5caa078766999e5eb
```

I run inspekt with all warnings:

```
$ inspekt lint --enable W avocado/core/test.py 
Pylint disabled: W,R,C,E1002,E1101,E1103,E1120,F0401,I0011
Pylint enabled : W
Using config file /dev/null
************* Module avocado.core.test
W1618: 21,0: : import missing `from __future__ import absolute_import`
W0703: 89,15: RawFileHandler.emit: Catching too general exception Exception
W1641: 93,0: TestID: Implementing __eq__ without also implementing __hash__
W0703:649,15: Test.get_state: Catching too general exception Exception
W0702:845,12: Test._run_avocado: No exception type(s) specified
W0702:870,12: Test._run_avocado: No exception type(s) specified
W0703:907,23: Test._run_avocado: Catching too general exception Exception
W0703:918,27: Test._run_avocado: Catching too general exception Exception
W0703:930,27: Test._run_avocado: Catching too general exception Exception
W0703:996,15: Test.run_avocado: Catching too general exception Exception
W0221:1031,4: Test.fail: Parameters differ from overridden 'fail' method
W0201:668,8: Test._start_logging: Attribute 'file_handler' defined outside __init__
Lint: avocado/core/test.py FAIL 
Syntax check FAIL
```

But no W0612 is reported.  Even worse, the line you reported (407):

```python
    @property
    def name(self):
        """
        Returns the Test ID, which includes the test name

        :rtype: TestID
        """
        return self.__name
```

Doesn't contain anything like `teststmpdir`.  And finally, that module contains a single mention of `teststmpdir`, which is a property, and not a variable (line 510):

```python
    @property
    def teststmpdir(self):
        """
        Returns the path of the temporary directory that will stay the
        same for all tests in a given Job.
        """
        env_var = COMMON_TMPDIR_NAME
        path = os.environ.get(env_var)
        if path is None:
            msg = 'Environment Variable %s is not set.' % env_var
            raise EnvironmentError(msg)
        return path
```

So I don't really know what to fix here.

**Comment by ldoktor** [comment]
This is not in your commit, it's in later commits that are already on master. Simple rebase and update of the last commit to address that tmpdir should do.

**Comment by ldoktor** [comment]
(see, this is the reason we run `incremental_check`)

**Comment by clebergnu** [comment]
Yet, found it.  Thanks for the tip.

**Comment by ldoktor** [comment]
The Travis failure is tmpdirs probably from on of the failed selftests:

`selftests.unit.test_utils_service.TestSystemdServiceManager.test_unknown_runlevel selftests.unit.test_utils_output.UtilsOutputTest.test_display_data_size_factor_1024 selftests.unit.test_utils_process.TestProcessRun.test_run_sudo_shell selftests.unit.test_utils_network.PortTrackerTest.test_release_port_does_not_poke_system selftests.unit.test_loader.LoaderTest.test_multiple_methods_same_name selftests.unit.test_test.TestClassTestUnit.test_no_data_dir selftests.unit.test_utils_process.CmdResultTests.test_cmd_result_stdout_stderr_text selftests.unit.test_replay.Replay.test_replay_map_interrupted_json selftests.unit.test_distro.ProbeTest.test_name_for_file selftests.unit.test_safeloader.FindClassAndMethods.test_with_base_class selftests.unit.test_settings.SettingsTest.test_allow_blank_true_list selftests.unit.test_job.JobTest.test_job_no_base_logdir selftests.unit.test_utils_process.MiscProcessTests.test_binary_from_shell selftests.unit.test_test.TestClassTestUnit.test_check_reference_success selftests.unit.test_archive.ArchiveTest.test_tar_dir selftests.unit.test_sysinfo.SysinfoTest.test_logger_job_hooks selftests.unit.test_utils_process.TestProcessRun.test_run_nosudo selftests.unit.test_restclient_response.ResultResponseTest.test_bad_data_count selftests.unit.test_loader.LoaderTest.test_python_unittest selftests.unit.test_loader.LoaderTest.test_load_not_a_test_exec selftests.unit.test_gdb.GDBRemoteTest.test_checksum`

**Comment by clebergnu** [comment]
[Enable `W` in travis/make check.](https://trello.com/c/Ohh7Q6qj/1183-enable-w-in-travis-make-check)

**Pull request merged**
