### PR TITLE
Test API: Isolate avocado.external.gdbmi_parser and avocado.external.spark from being used by test developers.

### PR DESCRIPTION
**Pull request by ruda**
Move avocado.external.gdbmi_parser and avocado.external.spark
to avocado.core.gdmi_parser and avocado.core.spark, in conformance to
our purpose of keeping things not related to test developers,
inside avocado.core, isolated from users.

So that, avocado.external has gone.

Signed-off-by: Rudá Moura <rmoura@redhat.com>

### CODE REVIEW

**Comment by clebergnu** [comment]
How do you feel about also keeping `external`, that is, moving it to `avocado.core.external`?

My original point with external is that it's 3rd party code which was/is impossible to add as a dependency, and if possible, I'd like to keep that reference.

**Comment by ruda** [comment]
@clebergnu my option here is to avoid too much levels (avocado.core.something...), so in the sense that external is not important for the structure (it's a reminder that the code is not ours), I choose to keep with 'core' flatten. I see that both files (in the original external module) declares the ownership and  license, so I think it's OK to remove 'external'.

**Comment by ruda** [comment]
@clebergnu Another point I require your opinion, I was tempted to move avocado.gdb to avocado.core.gdb, but I know the tests use it, so I kept it the same place. What do you think? it could be on avocado.utils too (which process is part).

**Comment by clebergnu** [comment]
@ruda with regards to `externals` I think it's a nice to have, but not a hard requirement.

Then with regards to `avocado.gdb`, you're right that the test uses and even the documentation explains how to use that. So, if any part of `core` also needs it, we must move it to `core`, and then export some (or all?) of it to the users.

**Comment by lmr** [comment]
@clebergnu `core` may use the rest of avocado libraries, but users aren't supposed to used stuff in `core`. I don't think it's a problem at all.

**Comment by lmr** [comment]
@ruda, I'd like you to change the PRs from now on to have the changes `for being used` -> `from being used` in the all of the descriptions/summaries.

**Comment by lmr** [comment]
`keep things` -> `keeping things`.

**Comment by ruda** [comment]
@lmr, OK, I will rebase all open PR I've made to fix the grammar.

**Comment by clebergnu** [comment]
Another ACK. Rebased, change a little bit the commit text and merged! Thanks!

**Pull request closed without merging**
