### PR TITLE
avocado.utils.software_manager: Check if yum module is present

### PR DESCRIPTION
**Pull request by ruda**
When using the software_manager component on a Red Hat like distro,
    if the yum module for Python is not installed, log the information
    as an error message and use the basic support from rpm/yum.
    
    Why this?
    
    If the module yum is not installed (for example, in a virtualenv),
    the software_manager component will not traceback when creating
    an instance of YumBackend and only the method provides() will be disabled.

### CODE REVIEW

**Comment by lmr** [comment]
@ruda, this is a side effect of Fedora 22 shipping with DNF, and yum being deprecated. I suppose this is a serviceable fix for it, and I'm considering doing the same for the autotest copies.

**Comment by ruda** [comment]
I'm not sure, it's something that , at least, in my virtual envs I've found that they are not copying the yum module and , thanks for pointing that, also for dnf.

```
thinkpad:~ rmoura% source .pyenvs/avocado/bin/activate
(avocado)thinkpad:~ rmoura% 
(avocado)thinkpad:~ rmoura% 
(avocado)thinkpad:~ rmoura% python
Python 2.7.10 (default, May 27 2015, 18:11:38) 
[GCC 5.1.1 20150422 (Red Hat 5.1.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import yum
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named yum
>>> import dnf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named dnf
```

Both modules are available in my python, outside the virtual env.

**Comment by ruda** [comment]
@lmr not yet, this module requires some code changes, and putting this to `None` and not allowing other methods that uses the `yum` module to run, should be a better improvement in the code, indeed. I will improve this.

**Comment by lmr** [comment]
@ruda the virtual envs will not copy these modules anyway. It's one of the selling points of `virtualenv` actually.

**Comment by lmr** [comment]
https://github.com/autotest/autotest/issues/935 is an issue recently opened in autotest, that directly relates to this.

**Comment by lmr** [comment]
I'll just wait Travis to do its thing, then merge. I'll apply the same patch to the autotest copy. Thanks!

**Comment by ruda** [comment]
@lmr I've made some modifications in this PR and accepted your suggestion of declaring `self.yum_base` to `None` if the `yum module` is not present.

**Comment by ruda** [comment]
I looked at `dnf ` vs `yum` differences (http://dnf.readthedocs.org/en/latest/cli_vs_yum.html) and I think it would be desirable in a new feature to include dnf support, but for Fedora 22 it's OK to use the way it is now.

**Comment by lmr** [comment]
Thanks @ruda !

**Pull request merged**
