### PR TITLE
Test API: Isolate avocado.aexpect for being used by the test developers.

### PR DESCRIPTION
**Pull request by ruda**
Move avocado.aexpect to avocado.core.aexpect in conformance to
our purpose of keep things not related to test developers,
inside avocado.core.

Signed-off-by: Rudá Moura <rmoura@redhat.com>

### CODE REVIEW

**Comment by lmr** [comment]
@ruda I disagree with this change. `aexpect` is important to test developers, since it's a way to interact with interactive programs in a programatic way. It's used extensively in `virt-test` and it's still in use by the avocado-virt plugin.

**Comment by ruda** [comment]
@lmr, at least in the context of avocado-virt, `aexpect` is used inside the method `power_on`. In the context of avocado-virt-tests, the tests makes use of `power_on`. From this perspective, I think it's OK to move `aexpect` to `avocado.core`, but I admit it's a gray area. If it don't belongs to `avocado.core` it should move to `avocado.utils`.

**Comment by ruda** [comment]
I wonder if `aexpect` don't belongs exclusively to `avocado-virt`, no other parts of `avocado` make use of it yet.

**Comment by lmr** [comment]
I don't think it's exclusive to avocado-virt, in fact I've been thinking about turning it into a stand alone library. Interacting with external interactive programs such as `ssh`, `scp`, `telnet` and others is a fairly common occurrence.

**Comment by ruda** [comment]
@lmr  I agree, this library (aexpect) has a very specific role and it's part of other projects too.

**Comment by lmr** [comment]
I'm closing this one and taking a look at separating aexpect to a separate project.

**Comment by lmr** [comment]
@ruda, I've worked on it. After some cleaning up and separating the client/server portions and picking only the necessary functions from avocado, I've got:

https://github.com/autotest/aexpect

It can even generate an rpm. Now, this is not up to 'production' standards, such as, the rpm name should've been `python-aexpect`, the `aexpect-helper` should install to `/usr/libexec`, generate documentations and tests, and all that fancy stuff I hope @clebergnu can help us with :) In fact, all those details were preventing me from starting this work. Not anymore :)

**Comment by clebergnu** [comment]
@lmr sure thing. Let's push it to the next level.

**Pull request closed without merging**
