### PR TITLE
avocado.core: show the subcommand help on unknown argparse option [v3]

### PR DESCRIPTION
**Pull request by apahim**
v1 #981
v1 #982 

Changes:
  - Changed from print_usage() to print_help() on invalid argument.

### CODE REVIEW

**Comment by clebergnu** [comment]
Hits all the right bells IMHO!

**Comment by apahim** [comment]
Minor wrong version issue. Fixing.

**Comment by apahim** [comment]
There we go.

**Comment by clebergnu** [comment]
Works for me! Merged! Thanks!

**Pull request merged**
