### PR TITLE
Enchanced a function in pci.py program

### PR DESCRIPTION
**Pull request by vrbagalkote**
Enchanced the function to return the interface of all types
Earlier it was only valid for nic, now it will work for ant type

Signed-off-by: Venkat R B <vrbagal1@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by vrbagalkote** [comment]
>> host = pci.get_interface_in_pci_address("0001:01:00.0", "net")
>> print host
['enP1p1s0f0']
>> host = pci.get_interface_in_pci_address("0004:01:00.0", "fc_host")
>> print host
['host6']
>> host = pci.get_interface_in_pci_address("0003:0a:00.0", "scsi_host")
>> print host
['host5', 'host3', 'host4', 'host2']

**Comment by vrbagalkote** [comment]
Hi,

My apologies, I am not sure whats wrong with pep8. When I run pep8 and pylint manually, I dont see any errors/warnings. But Travis CI reporting error in pep8 at line 120.

I have added a line at 120, still its throwing the error. Am I missing anything here. Please let me know.

PEP8 disabled: E501,E265,W601,E402,E722
/home/travis/build/avocado-framework/avocado/avocado/utils/pci.py:120:1: E302 expected 2 blank lines, found 1
Style check fail: /home/travis/build/avocado-framework/avocado/avocado/utils/pci.py
PEP8 compliance FAIL
style FAILED

Thanks in advance,
Venkat.

**Comment by apahim** [comment]
@vrbagalkote there were 2 new lines before the next function definition (line 120), now there's only 1. It is required to have 2.

**Comment by apahim** [comment]
Btw, you can run `make check` in your machine to have the same tests as in Travis.

**Pull request closed without merging**
