### PR TITLE
Docs: fix `make requirements-selftests` instruction.

### PR DESCRIPTION
**Pull request by willianrampazzo**
Signed-off-by: Willian Rampazzo <willianr@redhat.com>

### CODE REVIEW

**Comment by clebergnu** [comment]
@willianrampazzo I don't think I'm following the reason for this change.  IIUC, that section in the documentation is addressing users, and not Avocado developers.  Avocado users should not need to run Avocado's own selftests, and should not need those extra requirements.

**Comment by clebergnu** [comment]
@willianrampazzo one more point, now the requirements are inside the `setup.py` files, so that step should, assuming IUC, be removed.

**Comment by beraldoleal** [comment]
I missed that, I agree with @clebergnu .

**Comment by willianrampazzo** [comment]
I also missed that, I agree with @clebergnu :D I'll send a different PR to fix that.

**Pull request closed without merging**
