### PR TITLE
Test API: Isolate avocado.job for being used by test developers.

### PR DESCRIPTION
**Pull request by ruda**
Move avocado.job to avocado.core.job, in conformance to our
purpose of keep things not related to test developers,
inside avocado.core.

Signed-off-by: Rudá Moura <rmoura@redhat.com>

### CODE REVIEW

**Comment by clebergnu** [comment]
So, to document what was discussed on IRC, I believe this should introduce a `main()` API function that can be used in place of `avocado.core.job.main()`, which is now off limits to users.

**Comment by ruda** [comment]
@clebergnu Agree, I'm going to submit as V2.

**Comment by lmr** [comment]
Ruda, a couple of things that you need to fix:

Isolate avocado.job for being used by test developers -> Isolate avocado.job from being used by test developers

Move avocado.job to avocado.core.job, in conformance to our
purpose of keep things not related to test developers,
inside avocado.core. -> Move avocado.job to avocado.core.job, in conformance to our
purpose of keeping things not related to test developers,
inside avocado.core, isolated from users.

**Comment by ruda** [comment]
Closing this in favor of #575.

**Pull request closed without merging**
