### PR TITLE
Replacing time.time() with time.monotonic() occurrences

### PR DESCRIPTION
**Pull request by t0xic0der**
- Made changes in 13 files
- Overlooked docs and other arrears

### CODE REVIEW

**Review by willianrampazzo — APPROVED** [review]
Code looks good to me, thanks!

**Comment by t0xic0der** [comment]
@willianrampazzo A lot of tests are failing. Is that ok?

**Comment by willianrampazzo** [comment]
> @willianrampazzo A lot of tests are failing. Is that ok?

Which tests are you referring to?

**Comment by t0xic0der** [comment]
The CI checks I mean

**Comment by willianrampazzo** [comment]
> > @willianrampazzo A lot of tests are failing. Is that ok?
> 
> Which tests are you referring to?

The `codeclimate` issue was not introduced by your changes.

We are mostly worried about Travis failures and I see just one job has started, but that already have a fail, `selftests/signedoff-check.sh`.

You forgot to sign off your commits :) 

Check here how to do that: https://avocado-framework.readthedocs.io/en/82.0/guides/contributor/chapters/styleguides.html#commit-style-guide

**Comment by t0xic0der** [comment]
> You forgot to sign off your commits :)

Do I need to repeat the commits with the sign or are they okay to go?

**Comment by willianrampazzo** [comment]
> > > @willianrampazzo A lot of tests are failing. Is that ok?
> > 
> > 
> > Which tests are you referring to?
> 
> The `codeclimate` issue was not introduced by your changes.
> 
> We are mostly worried about Travis failures and I see just one job has started, but that already have a fail, `selftests/signedoff-check.sh`.
> 
> You forgot to sign off your commits :)
> 
> Check here how to do that: https://avocado-framework.readthedocs.io/en/82.0/guides/contributor/chapters/styleguides.html#commit-style-guide

Also, make sure you run `make check` before submitting the pull request. This will run the same tests that run on Travis and you will have the failures soon, on your machine.

**Comment by willianrampazzo** [comment]
> > You forgot to sign off your commits :)
> 
> Do I need to repeat the commits with the sign or are they okay to go?

You need to amend the signoff on each of your commits. This ensures we will not have failures on Travis and also, that you agree with the contribution to our project.

Also, make sure you have a descriptive and detailed message in your commits.

**Review by willianrampazzo — CHANGES_REQUESTED** [review]
Waiting for the commit message changes to approve.

**Comment by t0xic0der** [comment]
> You need to amend the signoff on each of your commits.

Can it be done without rolling back the commits? Need some pointers here.

**Comment by clebergnu** [comment]
@t0xic0der first of all, thanks for your contribution.

This kind of mass change, when you can describe the change easily but it's spread around multiple files, is better done in a single commit.  As it is, this just "pollutes" the history, and makes things such as bisecting harder.

And as @willianrampazzo has said, the resulting commit message can use more descriptive information.

**Comment by clebergnu** [comment]
Another thing to consider is that each change should be evaluated.  The `monotonic` clock is useful when trying to measure the duration of some task/routine/whatever, and *is not* suitable when the *current* date/time is needed.

**Comment by t0xic0der** [comment]
> Another thing to consider is that each change should be evaluated. The monotonic clock is useful when trying to measure the duration of some task/routine/whatever, and is not suitable when the current date/time is needed.

True but how do I distinguish between the two applications of it?

**Comment by t0xic0der** [comment]
> And as @willianrampazzo has said, the resulting commit message can use more descriptive information.

Yes. Some commit messages went beyond 50 chars so I had to add it to extended description.

**Comment by t0xic0der** [comment]
Hi @clebergnu,

I am listing all the occurrences of `time.time()` below. Please mark out which ones of them need replacement and which ones of them don't.

- 2 occurrences in `avocado/core/job.py`
- 9 occurrences in `avocado/core/runner.py`
- 3 occurrences in `avocado/core/test.py`
- 8 occurrences in `avocado/plugins/runner.py`
- 1 occurrence in `avocado/core/asset.py`
- 2 occurrences in `avocado/utils/debug.py`
- 2 occurrences in `avocado/utils/filelock.py`
- 3 occurrences in `avocado/utils/gdb.py`
- 8 occurrences in `avocado/utils/process.py`
- 6 occurrences in `selftests/functional/test_basic.py`
- 4 occurrences in `selftests/functional/test_loader.py`
- 2 occurrences in `selftests/functional/test_utils.py`
- 2 occurrences in `selftests/unit/test_utils/process.py`

You can save time by simply copy-pasting the message and putting the indices of occurrences to be replaced (Use 1-based indexing please :sweat_smile:). The indices not told about would be kept intact.

For instance, something like this.
```
- 6 occurrences in `selftests/functional/test_basic.py` [1, 3, 4, 6]
- 4 occurrences in `selftests/functional/test_loader.py` [1, 4]
```

**Comment by t0xic0der** [comment]
Please refer to #4249.

**Comment by beraldoleal** [comment]
> Please refer to #4249.

Closing in favor of ##4249.

**Pull request closed without merging**
