### PR TITLE
 Add spell checker as Makefile target [v3]

### PR DESCRIPTION
**Pull request by apahim**
v3:
 - Add pyenchant to the requirements-travis.

v2: #1298 
 - Fix some spelling errors.
 - Clean white-list.
 - `echo OK` when spell check passes.

v1: #1297 
This patch adds the `make spell` command so developers can easily
check the spelling on docstrings and comments. False positives
words should be added to spell.ignore file.

Signed-off-by: Amador Pahim <apahim@redhat.com>

### CODE REVIEW

**Comment by ldoktor** [comment]
Yep, this is what I had been talking about. Thanks for adding the travis requirement, but you also need to add `hunspell-en-US` to the `.travis.yaml` (well the deb alternative of this package).

**Comment by ldoktor** [comment]
Although the top commit is not checked with `make check` so you need to add it to the `.travis.yaml` as well.

**Comment by apahim** [comment]
Ok, too much trouble adding this to travis. It requires sudo to install packages (what means not to use containers anymore) and the dictionary package available for ubuntu is hugely outdated, so we have to maintain the spell.ignore for ubuntu as well. Not worth it. So, back to the KISS, just a `make spell` command that developers can run locally.

**Comment by ldoktor** [comment]
yes, I agree...

**Pull request merged**
