### PR TITLE
pre-release-test: fixes to pass

### PR DESCRIPTION
**Pull request by beraldoleal**
Fedora copr builds are failing because HTML plugin is not enabled.
Because of that, html outputs are not generated. I could not reproduce
this locally yet, and couldn't find any other hint on debug.log. There
is a mention to "package init file 'avocado_result_html/__init__.py' not
found (or not a regular file)" and this *might be* the root cause.

Probably this is is not the best solution, but I would like to check if
copr build will pass until we find the best one.

I'm also, doing a small fix on our pre-release plan.

Signed-off-by: Beraldo Leal <bleal@redhat.com>

### CODE REVIEW

**Comment by ana** [comment]
@beraldoleal Let's see if I understand the problem: the html is not properly generated when running it from the fedora packages? if so, which fedora version?

**Comment by beraldoleal** [comment]
> @beraldoleal Let's see if I understand the problem: the html is not properly generated when running it from the fedora packages? if so, which fedora version?

copr is trying to build this on centos-stream-8 and it is failing, logs are here:

https://download.copr.fedorainfracloud.org/results/@avocado/avocado-latest/centos-stream-8-aarch64/03294756-python-avocado/builder-live.log.gz

**Comment by ana** [comment]
> > @beraldoleal Let's see if I understand the problem: the html is not properly generated when running it from the fedora packages? if so, which fedora version?
> 
> copr is trying to build this on centos-stream-8 and it is failing, logs are here:
> 
> https://download.copr.fedorainfracloud.org/results/@avocado/avocado-latest/centos-stream-8-aarch64/03294756-python-avocado/builder-live.log.gz

Ok, in that case replace the first commit with:

`git revert 2e426bd81395444b6bbfb771f3af995776e87cfc`

**Comment by beraldoleal** [comment]
> 2e426bd81395444b6bbfb771f3af995776e87cfc

Yes, makes sense. I was just trying to make sure this makes sense. Thanks.

**Review by ana — APPROVED** [review]

**Review by richtja — APPROVED** [review]
LGTM

**Pull request merged**
