### PR TITLE
Adding Multipath Module [v3]

### PR DESCRIPTION
**Pull request by narasimhan-v**
avocado.utils.multipath: Adds multipath related modules.

Changelog from v1 #1547 :
*) Used utils.service to restart and to check status of multipath service
*) Added a check to see if multipath devices exist, on all required functions, so that IndexError is not encountered.
*) Using logging.debug(open().read()) to display contents of the file, as per comments.
*) Based on comments, changed function name to device_exists
*) Removed raising of Exception, since its codepath is not existing anymore.
*) Mentioned that the module needs to be used only by root user.

Changelog from v2 #1559 :
*) Made use of process.can_sudo() to fail early in case sudo access is not there in test.
*) Used sudo=True in functions of process module, as necessary.
*) Made sure return types are consistent.
*) Added a helper function for finding the multipath service name based on distro,

Signed-off-by: Narasimhan V <sim@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by narasimhan-v** [comment]
Travis CI fails due to import error, which is a feature in the module.
Please advise.

/home/travis/build/avocado-framework/avocado/docs/source/api/utils/avocado.utils.rst:195: WARNING: autodoc: failed to import module u'avocado.utils.multipath'; the following exception was raised:

Traceback (most recent call last):

  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 378, in import_object

    __import__(self.modname)

  File "/home/travis/build/avocado-framework/avocado/avocado/utils/multipath.py", line 29, in <module>

    raise ImportError('This module requires superuser rights.')

ImportError: This module requires superuser rights.

@apahim

**Comment by apahim** [comment]
Yep, bad idea.  Please remove the check and also the `print` that was left in the line before. You can update this PR then.

**Comment by narasimhan-v** [comment]
@apahim Sure.

**Comment by narasimhan-v** [comment]
Created new PR #1650

**Pull request closed without merging**
