### PR TITLE
[V7] Test discovery and load (Phase II)

### PR DESCRIPTION
**Pull request by lmr**
This is a follow up to #358. 

This has the full functionality, including the list functionality and fixes to the remote and vm plugins.

Changes from V6:
 
* Rebased the code
* Improved the 'list' subcommand to take a list of paths, and overhauled the output of that command.
* Fixed remote and VM plugins

Changes from V4 and V5:

 * Rebase the code
 * Consolidated commits
 * Now when users provide paths to explicit files, then it analyzes them. If a dir is provided, non tests are not listed/their execution is attempted. Fixing comments by @ldoktor.

Changes from V3:

Fixed problems found by @ldoktor, mainly:

* Remove remaining references to MissingTests inside the code
* Fix crash when tests have bugs that prevent their modules from being imported
* Append base test directory to `sys.path` to ensure dependent modules in the same dir are importable

Changes from V2:

* Completely remove the concept of MissingTests. It wasn't very useful to begin with.
* Break the need for test classes to be named after the module names.
* Mass rename the current avocado test class names
* Update docs to reflect the new *status quo*

Changes from V1:

* avocado.loader: Locate SimpleTests using the full path.
* avocado.job: Set different messages when the number of tests found is zero [No tests found within the  specified path(s)] or when the number of variants is zero [The number of test variants is zero].
* avocado.loader: Skip directory if we don't have permission to walk. Also skip tests that are not tests, so Avocado stops crashing when walking in a directory, looking for tests.
* avocado.utils.process: Use shell glob style when matching wrap scripts.
test_lister plugin: Sort output in alphabetic order.

### CODE REVIEW

**Comment by ldoktor** [comment]
Hi Lucas, this version lacks the fix I mentioned in https://github.com/lmr/avocado/commit/343bbc1efc5338a1ffc8372aa055149a54da697e and remote is still failing:
```
[medic@t530 avocado 1]$ ./scripts/avocado run examples/tests/passtest.py importerror.py corrupted.py pass.py passtest  --remote-hostname 192.168.122.235 --remote-username root --remote-password 123456
Avocado crashed: TypeError: tuple indices must be integers, not str
Traceback (most recent call last):

  File "/home/medic/Work/Projekty/avocado/avocado/avocado/job.py", line 272, in _run
    failures = self.test_runner.run_suite(test_suite)

  File "/home/medic/Work/Projekty/avocado/avocado/avocado/plugins/remote.py", line 65, in run_suite
    urls = [x['id'] for x in params_list]

TypeError: tuple indices must be integers, not str

Please include the traceback info and command line used on your bug report
Report bugs visiting https://github.com/avocado-framework/avocado/issues/new
```

Please merge the fix into the cff0b8d (it needs to be applied for booth, `vm` and `remote` plugins) to prevent broken avocado versions.

**Comment by lmr** [comment]
@ldoktor, oh, true, sorry about that. It's fixed now!

**Comment by lmr** [comment]
The point of this patch is to make avocado to not show dirs with tons of non tests when only the dirs were specified. I'll check your commits on the previous PR and see if I can replace this.

**Comment by lmr** [comment]
Closing in favor of #366

**Pull request closed without merging**
