### PR TITLE
Suite dependency

### PR DESCRIPTION
**Pull request by richtja**
This PR introduces job dependency feature. With this feature, you can
define common dependency for each test inside job or with Job API inside suite.
With this feature, it should be easier to create tests which share their
dependencies.

It reads all the dependencies from the json file, where the user can specify
all the dependencies needed for this job. It uses the same json format as is
used in test docstrings. Part of this commit is a documentation update which
describes this feature more deeply.

Reference: https://github.com/avocado-framework/avocado/issues/5504
Signed-off-by: Jan Richter <jarichte@redhat.com>

### CODE REVIEW

**Review by clebergnu — CHANGES_REQUESTED** [review]
Hi @richtja,

I've played with this PR, and while I've thought of other approaches, such as making a distinction between dependencies that are capable of being fulfilled in parallel and those that can not, this one is sufficient to handle all sorts of dependencies.

But, that dependency handling bug exists right now, and can be triggered with a test like this:

```python
from avocado import Test


class PassTest(Test):
    """
    Example test that passes.

    :avocado: dependency={"type": "package", "name": "hello"}
    :avocado: dependency={"type": "package", "name": "hello"}
    :avocado: dependency={"type": "package", "name": "hello"}
    :avocado: dependency={"type": "package", "name": "hello"}
    :avocado: dependency={"type": "package", "name": "hello"}
    """

    def test(self):
        """
        A test simply doesn't have to fail in order to pass
        """
```

And then running it in parallel like this:

```
$ avocado run -- passtest_with_dependency.py passtest_with_dependency.py passtest_with_dependency.py passtest_with_dependency.py passtest_with_dependency.py passtest_with_dependency.py passtest_with_dependency.py passtest_with_dependency.py passtest_with_dependency.py passtest_with_dependency.py 
JOB ID     : 9e24c01717368b5b94a61430a267bacc46b315ff
JOB LOG    : /home/cleber/avocado/job-results/job-2024-04-12T08.05-9e24c01/job.log
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 10 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/cleber/avocado/job-results/job-2024-04-12T08.05-9e24c01/results.html
JOB TIME   : 3.74 s
```

Even with the dependency fulfilled in the cache (or without it), Avocado fails to run any of the tests.

My suggestion is that we separate that issue from the suite support.  Something like getting the last commit here and making sure it addressed the reproducer above.

I believe this will lead to, at the very least, a better history on this issue.

Thanks!

**Comment by richtja** [comment]
Hi @clebergnu thank you for your review, and thank you for investigating the duplicity issue. I did a `force-push` without the last commit and create #5904 to track the duplicity issue.

**Comment by richtja** [comment]
Hi @clebergnu, I have updated this after merge of #5905, please have a look.

**Review by clebergnu — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
