### PR TITLE
[Release 81] fix spelling

### PR DESCRIPTION
**Pull request by willianrampazzo**
Signed-off-by: Willian Rampazzo <willianr@redhat.com>

### CODE REVIEW

**Review by pevogam — COMMENTED** [review]
Do you think we could also check the documentation extensions? I think I saw quite some typos there.

**Comment by willianrampazzo** [comment]
> Do you think we could also check the documentation extensions? I think I saw quite some typos there.

I'm running `make spell` here to find the typos in the code. Maybe we can extend it to run against the documentation.

**Comment by pevogam** [comment]
> > Do you think we could also check the documentation extensions? I think I saw quite some typos there.
> 
> I'm running `make spell` here to find the typos in the code. Maybe we can extend it to run against the documentation.

Alright, then I guess it is just something to note for the future.

**Review by pevogam — APPROVED** [review]

**Comment by clebergnu** [comment]
> > > Do you think we could also check the documentation extensions? I think I saw quite some typos there.

Hopefully we'll catch most during the documentation review for LTS, but yes, there's no reason not to include the docs on `make spell`.

> > 
> > 
> > I'm running `make spell` here to find the typos in the code. Maybe we can extend it to run against the documentation.
> 
> Alright, then I guess it is just something to note for the future.

**Pull request merged**
