### PR TITLE
Xunit results missing attributes

### PR DESCRIPTION
**Pull request by richtja**
Gathering more metadata from resolvers and runners. It will provide better information about test and its failures, which can be used by result plugins.

Reference: https://github.com/avocado-framework/avocado/issues/5332
Signed-off-by: Jan Richter <jarichte@redhat.com>

### CODE REVIEW

**Review by clebergnu — CHANGES_REQUESTED** [review]
Hi @richtja,

This certainly does the job, but I'm quite opposed to expanding the Runnable class with "core" attributes that are not generic enough.

IMO, the individual runners that may have extra information about tests (such as module, class, method) can send that information along at the appropriate time -- exactly like it's being done with failure related information.

I've put a prototype at [this branch](https://github.com/clebergnu/avocado/commits/xunit_results_5332).  While possibly not complete, it's way simpler IMO and it's enough to make the newly added tests pass:

```
$ avocado run selftests/functional/plugin/test_xunit.py 
JOB ID     : f6eb15c20e72ff17504715cbef8f88d8f17e0840
JOB LOG    : /home/cleber/avocado/job-results/job-2023-01-24T15.44-f6eb15c/job.log
 (3/3) selftests/functional/plugin/test_xunit.py:JsonResultTest.test_error_reason: STARTED
 (1/3) selftests/functional/plugin/test_xunit.py:JsonResultTest.test_testcase: STARTED
 (2/3) selftests/functional/plugin/test_xunit.py:JsonResultTest.test_fail_reason: STARTED
 (1/3) selftests/functional/plugin/test_xunit.py:JsonResultTest.test_testcase:  PASS (1.76 s)
 (2/3) selftests/functional/plugin/test_xunit.py:JsonResultTest.test_fail_reason:  PASS (1.89 s)
 (3/3) selftests/functional/plugin/test_xunit.py:JsonResultTest.test_error_reason:  PASS (1.89 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/cleber/avocado/job-results/job-2023-01-24T15.44-f6eb15c/results.html
JOB TIME   : 3.04 s
```

Let me know what you think of it.

**Comment by richtja** [comment]
> Hi @richtja,
> 
> This certainly does the job, but I'm quite opposed to expanding the Runnable class with "core" attributes that are not generic enough.
> 
> IMO, the individual runners that may have extra information about tests (such as module, class, method) can send that information along at the appropriate time -- exactly like it's being done with failure related information.
> 
> I've put a prototype at [this branch](https://github.com/clebergnu/avocado/commits/xunit_results_5332). While possibly not complete, it's way simpler IMO and it's enough to make the newly added tests pass:
> 
> ```
> $ avocado run selftests/functional/plugin/test_xunit.py 
> JOB ID     : f6eb15c20e72ff17504715cbef8f88d8f17e0840
> JOB LOG    : /home/cleber/avocado/job-results/job-2023-01-24T15.44-f6eb15c/job.log
>  (3/3) selftests/functional/plugin/test_xunit.py:JsonResultTest.test_error_reason: STARTED
>  (1/3) selftests/functional/plugin/test_xunit.py:JsonResultTest.test_testcase: STARTED
>  (2/3) selftests/functional/plugin/test_xunit.py:JsonResultTest.test_fail_reason: STARTED
>  (1/3) selftests/functional/plugin/test_xunit.py:JsonResultTest.test_testcase:  PASS (1.76 s)
>  (2/3) selftests/functional/plugin/test_xunit.py:JsonResultTest.test_fail_reason:  PASS (1.89 s)
>  (3/3) selftests/functional/plugin/test_xunit.py:JsonResultTest.test_error_reason:  PASS (1.89 s)
> RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
> JOB HTML   : /home/cleber/avocado/job-results/job-2023-01-24T15.44-f6eb15c/results.html
> JOB TIME   : 3.04 s
> ```
> 
> Let me know what you think of it.

Hi @clebergnu thanks for the review. I had thought about your solution, but then I decided to expand the Runnable, even that your solution is definitely way simpler. IMO, it is a question of responsibility. My decision was based on Single responsibility principle, where the Resolver is responsible for resolving the test files and has all the information for storing the klass and method. The runner is responsible for running the tests and gather logs and results. IMO, the runner shouldn't do resolving again, even the parsing of the uri is wrong. Therefore, I tried to fix that.

**Comment by clebergnu** [comment]
> > Hi @richtja,
> > This certainly does the job, but I'm quite opposed to expanding the Runnable class with "core" attributes that are not generic enough.
> > IMO, the individual runners that may have extra information about tests (such as module, class, method) can send that information along at the appropriate time -- exactly like it's being done with failure related information.
> > I've put a prototype at [this branch](https://github.com/clebergnu/avocado/commits/xunit_results_5332). While possibly not complete, it's way simpler IMO and it's enough to make the newly added tests pass:
> > ```
> > $ avocado run selftests/functional/plugin/test_xunit.py 
> > JOB ID     : f6eb15c20e72ff17504715cbef8f88d8f17e0840
> > JOB LOG    : /home/cleber/avocado/job-results/job-2023-01-24T15.44-f6eb15c/job.log
> >  (3/3) selftests/functional/plugin/test_xunit.py:JsonResultTest.test_error_reason: STARTED
> >  (1/3) selftests/functional/plugin/test_xunit.py:JsonResultTest.test_testcase: STARTED
> >  (2/3) selftests/functional/plugin/test_xunit.py:JsonResultTest.test_fail_reason: STARTED
> >  (1/3) selftests/functional/plugin/test_xunit.py:JsonResultTest.test_testcase:  PASS (1.76 s)
> >  (2/3) selftests/functional/plugin/test_xunit.py:JsonResultTest.test_fail_reason:  PASS (1.89 s)
> >  (3/3) selftests/functional/plugin/test_xunit.py:JsonResultTest.test_error_reason:  PASS (1.89 s)
> > RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
> > JOB HTML   : /home/cleber/avocado/job-results/job-2023-01-24T15.44-f6eb15c/results.html
> > JOB TIME   : 3.04 s
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Let me know what you think of it.
> 
> Hi @clebergnu thanks for the review. I had thought about your solution, but then I decided to expand the Runnable, even that your solution is definitely way simpler. IMO, it is a question of responsibility. My decision was based on Single responsibility principle, where the Resolver is responsible for resolving the test files and has all the information for storing the klass and method. The runner is responsible for running the tests and gather logs and results. IMO, the runner shouldn't do resolving again, even the parsing of the uri is wrong. Therefore, I tried to fix that.

Using the descriptions from the [docs](https://avocado-framework.readthedocs.io/en/100.1/guides/contributor/chapters/plugins.html?highlight=resolver#new-test-type-plugin-example):

* resolvers: they resolve references into proper test descriptions that Avocado can run.
* runners: these make use of the resolutions made by resolvers and actually execute the tests, reporting the results back to Avocado

The resolver is *not* responsible for resolving test *files*, but *references*, which can be quite abstract.  The example on the docs (and references on Avocado-VT) prove that.

The discussion here is really about if we add type specific information to the `Runnable`, or use an abstract and possibly opaque data.  Your proposal is doing both: the `uri` (abstract) and the set of `module_path`, `class` and `test_method` (specific) overlap.

One question that may help us get to the best solution: imagine there's a test type, that is not wrapped in a class and method, but it's simple a set of lines to be executed in a file.  Would we extend the `Runnable` class with the fields:

* `line_start`
* `line_end`

Or, would we define the URI as being composed of:

* `test_file`
* `line_start`
* `line_end`

Looking something like `/path/to/file:1:5`.

Summarizing my thoughts:

1. We should *definitely* not be adding overlapping information to the `Runnable` class
2. If we decide that we want to move from the generic description approach on the `Runnable` to an specific approach, we should do it at once
3. I don't think the runner responsibility is going beyond what is described in its goal

**Comment by richtja** [comment]
> > > Hi @richtja,
> > > This certainly does the job, but I'm quite opposed to expanding the Runnable class with "core" attributes that are not generic enough.
> > > IMO, the individual runners that may have extra information about tests (such as module, class, method) can send that information along at the appropriate time -- exactly like it's being done with failure related information.
> > > I've put a prototype at [this branch](https://github.com/clebergnu/avocado/commits/xunit_results_5332). While possibly not complete, it's way simpler IMO and it's enough to make the newly added tests pass:
> > > ```
> > > $ avocado run selftests/functional/plugin/test_xunit.py 
> > > JOB ID     : f6eb15c20e72ff17504715cbef8f88d8f17e0840
> > > JOB LOG    : /home/cleber/avocado/job-results/job-2023-01-24T15.44-f6eb15c/job.log
> > >  (3/3) selftests/functional/plugin/test_xunit.py:JsonResultTest.test_error_reason: STARTED
> > >  (1/3) selftests/functional/plugin/test_xunit.py:JsonResultTest.test_testcase: STARTED
> > >  (2/3) selftests/functional/plugin/test_xunit.py:JsonResultTest.test_fail_reason: STARTED
> > >  (1/3) selftests/functional/plugin/test_xunit.py:JsonResultTest.test_testcase:  PASS (1.76 s)
> > >  (2/3) selftests/functional/plugin/test_xunit.py:JsonResultTest.test_fail_reason:  PASS (1.89 s)
> > >  (3/3) selftests/functional/plugin/test_xunit.py:JsonResultTest.test_error_reason:  PASS (1.89 s)
> > > RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
> > > JOB HTML   : /home/cleber/avocado/job-results/job-2023-01-24T15.44-f6eb15c/results.html
> > > JOB TIME   : 3.04 s
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Let me know what you think of it.
> > 
> > 
> > Hi @clebergnu thanks for the review. I had thought about your solution, but then I decided to expand the Runnable, even that your solution is definitely way simpler. IMO, it is a question of responsibility. My decision was based on Single responsibility principle, where the Resolver is responsible for resolving the test files and has all the information for storing the klass and method. The runner is responsible for running the tests and gather logs and results. IMO, the runner shouldn't do resolving again, even the parsing of the uri is wrong. Therefore, I tried to fix that.
> 
> Using the descriptions from the [docs](https://avocado-framework.readthedocs.io/en/100.1/guides/contributor/chapters/plugins.html?highlight=resolver#new-test-type-plugin-example):
> 
>     * resolvers: they resolve references into proper test descriptions that Avocado can run.
> 
>     * runners: these make use of the resolutions made by resolvers and actually execute the tests, reporting the results back to Avocado
> 
> 
> The resolver is _not_ responsible for resolving test _files_, but _references_, which can be quite abstract. The example on the docs (and references on Avocado-VT) prove that.
> 
> The discussion here is really about if we add type specific information to the `Runnable`, or use an abstract and possibly opaque data. Your proposal is doing both: the `uri` (abstract) and the set of `module_path`, `class` and `test_method` (specific) overlap.
> 
> One question that may help us get to the best solution: imagine there's a test type, that is not wrapped in a class and method, but it's simply a set of lines to be executed in a file. Would we extend the `Runnable` class with the fields:
> 
>     * `line_start`
> 
>     * `line_end`
> 
> 
> Or, would we define the URI as being composed of:
> 
>     * `test_file`
> 
>     * `line_start`
> 
>     * `line_end`
> 
> 
> Looking something like `/path/to/file:1:5`.
> 
> Summarizing my thoughts:
> 
>     1. We should _definitely_ not be adding overlapping information to the `Runnable` class
> 
>     2. If we decide that we want to move from the generic description approach on the `Runnable` to an specific approach, we should do it at once
> 
>     3. I don't think the runner responsibility is going beyond what is described in its goal

Thanks for the explanation. I can see that my assumptions were wrong so I will continue with your proposal.

**Review by clebergnu — COMMENTED** [review]
LGTM, thanks!

**Review by clebergnu — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
