### PR TITLE
avocado.Test cleanup: low hanging fruits

### PR DESCRIPTION
**Pull request by clebergnu**
These are a collection of low hanging fruits in an attempt to give `avocado.Test` users (test writers) a better sense of what is the API allowed/intended for their use.

Related to:

https://trello.com/c/cVehsq2J/421-review-avocado-test-api

### CODE REVIEW

**Comment by adereis** [comment]
Minor minor: there's no plural for low hanging fruit. ;-)

**Comment by clebergnu** [comment]
Totally confused where. Why not?

I know that searching the web for many typos/errors will give you so many hits you'll end up thinking something is right, *but*, I got some quite dependable hits here!

Can you enlighten me on *why*? Please??? :smile:

**Comment by lmr** [comment]
It's admissible to use low hanging fruits (after all, it's admissible that there are fruits (plural) hanging low, literally speaking):

https://en.wiktionary.org/wiki/low-hanging_fruits#English

**Comment by lmr** [comment]
I thought these renames were going to reach other parts of avocado but they don't. Great, I'm going to merge this.

**Comment by clebergnu** [comment]
These are the ones that don't. There are some other stuff that does. Slated for part 2.

**Pull request merged**
