### PR TITLE
avocado.multiplexer: Use !mux and support for recursive mux [v0]

### PR DESCRIPTION
**Pull request by ldoktor**
This patch modifies the multiplexer logic to support full recursive
multiplexation, unlike the old version which only flattened the
multiplexed nodes. This allows greater flexibility.

Additionally it removes the !join flag and inverts the logic to use !mux
instead. By default leaves are not multiplexed and all are part of the
current params. Users can specify exact nodes which get multiplexed by
using !mux keyword.

Signed-off-by: Lukáš Doktor <ldoktor@redhat.com>

_PS: Documentation was not modified and the code is not optimized (it's 20-times slower than previous version, still it's incomparably faster then the original solution so it's probably not that bad)_

### CODE REVIEW

**Comment by ldoktor** [comment]
@clebergnu, @ruda, can you please take a look at this one today so I can work on it tomorrow.

**Comment by ruda** [comment]
The idea of using `!mux` is better to understand. I will look on the changes, later this day.

**Comment by ldoktor** [comment]
Also @bonzini, does this work as you expect? (put code style and optimization aside for now...)

**Comment by ruda** [comment]
OK, so it clear for me now, thanks @ldoktor. Great!

**Comment by ldoktor** [comment]
Thanks, @ruda, so apart of the code style, do you see any problems or can I proceed to documentation and hopefully to mergeable version?

**Comment by ruda** [comment]
@ldoktor, it looks good, it's on the right direction, please continue with documentation so we can start to merge it.

**Pull request closed without merging**
