### PR TITLE
[V4]Network fix

### PR DESCRIPTION
**Pull request by PraveenPenguin**
cleanup and some new utilities added

Signed-off-by: Praveen K Pandey praveen@linux.vnet.ibm.com

### CODE REVIEW

**Comment by PraveenPenguin** [comment]
> @PraveenPenguin in is_link_up() get_link_state() should be get_link_status() right.

@smruti77 yes `get_link_state()` it just a function name so seems should be fine, it will work for both the cases check below code 
`https://github.com/avocado-framework/avocado/pull/3629/files#diff-191591862061ffbb8613f7232ebc0fddR155-R156`

**Comment by smruti77** [comment]
> > @PraveenPenguin in is_link_up() get_link_state() should be get_link_status() right.
> 
> @smruti77 yes `get_link_state()` it just a function name so seems should be fine, it will work for both the cases check below code
> `https://github.com/avocado-framework/avocado/pull/3629/files#diff-191591862061ffbb8613f7232ebc0fddR155-R156`

@PraveenPenguin i got it that,but function name is incorrect here that should be get_link_status().

**Comment by PraveenPenguin** [comment]
> > > @PraveenPenguin in is_link_up() get_link_state() should be get_link_status() right.
> > 
> > 
> > @smruti77 yes `get_link_state()` it just a function name so seems should be fine, it will work for both the cases check below code
> > `https://github.com/avocado-framework/avocado/pull/3629/files#diff-191591862061ffbb8613f7232ebc0fddR155-R156`
> 
> @PraveenPenguin i got it that,but function name is incorrect here that should be get_link_status().

@smruti77 ah nice catch there is typo as while sending PR some thing went wrong , rectificed it please check

**Comment by smruti77** [comment]
> > > > @PraveenPenguin in is_link_up() get_link_state() should be get_link_status() right.
> > > 
> > > 
> > > @smruti77 yes `get_link_state()` it just a function name so seems should be fine, it will work for both the cases check below code
> > > `https://github.com/avocado-framework/avocado/pull/3629/files#diff-191591862061ffbb8613f7232ebc0fddR155-R156`
> > 
> > 
> > @PraveenPenguin i got it that,but function name is incorrect here that should be get_link_status().
> 
> @smruti77 ah nice catch there is typo as while sending PR some thing went wrong , rectificed it please check

@PraveenPenguin one more question before we used to get interface name form the  ip address that not handle here.
what function is their now it will return ip address.

**Comment by PraveenPenguin** [comment]
> > > > > @PraveenPenguin in is_link_up() get_link_state() should be get_link_status() right.
> > > > 
> > > > 
> > > > @smruti77 yes `get_link_state()` it just a function name so seems should be fine, it will work for both the cases check below code
> > > > `https://github.com/avocado-framework/avocado/pull/3629/files#diff-191591862061ffbb8613f7232ebc0fddR155-R156`
> > > 
> > > 
> > > @PraveenPenguin i got it that,but function name is incorrect here that should be get_link_status().
> > 
> > 
> > @smruti77 ah nice catch there is typo as while sending PR some thing went wrong , rectificed it please check
> 
> @PraveenPenguin one more question before we used to get interface name form the ip address that not handle here.
> what function is their now it will return ip address.

@smruti77 added utility you can have a look

**Comment by smruti77** [comment]
@PraveenPenguin now i see  in set_ip() 
'''                if interface_type:
                    interface_type = 'Ethernet'
                                      '''
here should be, interface_type is None:

**Comment by beraldoleal** [comment]
@PraveenPenguin @smruti77 thanks for that.

I will work on top of this.

**Comment by beraldoleal** [comment]
@PraveenPenguin @smruti77 btw, now I got why of the `decode('utf-8')`... :)

**Comment by beraldoleal** [comment]
@PraveenPenguin, A few things was not working here. I'm closing this in favor of pull/#3636, please feel free to add your comments there.

**Pull request closed without merging**
