### PR TITLE
WIP change the avocado plugins output

### PR DESCRIPTION
**Pull request by dkarpelevich**
The idea of current change is to improve the output of the command `avocado plugins`. Header `Package   | Provides | Description` and separators were added, `Provides` shows the namepace for the plugin.

Issue: https://github.com/avocado-framework/avocado/issues/3476

After the change it'll look like:
```
[user@host avocado]$ avocado plugins
Plugins that add new commands (cli.cmd):
Package   | Provides | Description
=========================================================================================
assets    | cli.cmd  | Manage assets
config    | cli.cmd  | Shows avocado config keys
diff      | cli.cmd  | Shows the difference between 2 jobs.
distro    | cli.cmd  | Shows detected Linux distribution
exec-path | cli.cmd  | Returns path to avocado bash libraries and exits.
list      | cli.cmd  | List available tests
nlist     | cli.cmd  | *EXPERIMENTAL* list tests (runnables)
nrun      | cli.cmd  | *EXPERIMENTAL* runner: runs one or more tests
plugins   | cli.cmd  | Displays plugin information
run       | cli.cmd  | Runs one or more tests (native test, test alias, binary or script)
sysinfo   | cli.cmd  | Collect system information
variants  | cli.cmd  | Tool to analyze and visualize test variants and params
vmimage   | cli.cmd  | Provides VM images acquired from official repositories
```

It should also help to understand which plugin do we use running `avocado plugins` with `grep`.
Before:
```
[user@host avocado]$ avocado plugins | grep json
json           JSON output options for 'run' command
json_variants  JSON serialized based Varianter options for the 'run' subcommand
json           JSON result support
json_variants  JSON serialized based Varianter
```
After:
```
[user@host avocado]$ avocado plugins | grep json
json           | cli      | JSON output options for 'run' command
json_variants  | cli      | JSON serialized based Varianter options for the 'run' subcommand
json           | result   | JSON result support
json_variants  | varianter | JSON serialized based Varianter
```

### CODE REVIEW

**Comment by beraldoleal** [comment]
The idea was to avoid multiple lines and try to remove a possible "ambiguity".  So my initial idea was to display in only *one* line each plugin. And if it provides multiple interfaces will be displayed at the same line.

Also, in order to replace the current implementation, we need to implement an "avocado plugins show plugin_here", in order to show a more detailed view of the plugins. (Sorry if this was not described at the issue)

But again, this was not discussed enough during the summit.

**Comment by dkarpelevich** [comment]
> And if it provides multiple interfaces will be displayed at the same line.

Ok, but which description should be in the `description` column in this case?

**Comment by beraldoleal** [comment]
@dkarpelevich sorry for the delay.

IMO, what makes sense is to add a generic description of the plugin module, not a description of each class. But this is just my option and this issue is here to be an open discussion.

For instance, `plugins/tap.py` it is a 'plugin module" to generate `TAP results`. To do that it uses two "plugin subsystems": `CLI` and `ResultsEvents` and produces two "plugins": `cli.tap` and `results_events.tap`.

For me, this is not so clear/obvious, when trying to learning a new framework. IMO the user **should not** be aware of the internal/details of the "avocado plugin architecture". Maybe, we could hide something and show only if explicitly required by the user, *again IMO*, this could reduce the learning curve of Avocado. 

So, without thinking on where are the information today, but focusing on the user experience, on a clean and simple UI, I would say that a nice output could be (showing only tap) something like that:

```
$ avocado plugins list
Name     Description
======= ========================================
tap         Provides results in Test Anything Protocol (TAP)
....

Version, Author, and other global information could be added in the future when supported.

But maybe we need to discuss more this because right now, we don't have a place to get the "module description". It could be from the module short_description docstring, for instance, but not sure if is the best solution.

My point is that today if I run `avocado plugins` on a system A and would like to install the same set plugins on a system B, this is not so straightforward, because I have to guess the name of the plugins packages in order to install them. IMO, we could ease that by displaying the name of the package/module that provides the functionality instead of the internal plugin name.

**Comment by dkarpelevich** [comment]
> It could be from the module short_description docstring, for instance, but not sure if is the best solution.

I think it's an option and there is a `description` variable in all plugin classes that's already used as a description. 
> My point is that today if I run avocado plugins on a system A and would like to install the same set plugins on a system B

I didn't get it. @beraldoleal could you please give an example of how to install plugin? Are you talking about a 3-party plugins that aren't listed with `avocado plugins`? Or, is it something like 'squash/combine' (for instance `tap`) plugins and show general description for `cli.tap` and `results_events.tap`?

**Comment by beraldoleal** [comment]
> I didn't get it. @beraldoleal could you please give an example of how to install plugin? Are you talking about a 3-party plugins that aren't listed with `avocado plugins`? Or, is it something like 'squash/combine' (for instance `tap`) plugins and show general description for `cli.tap` and `results_events.tap`?

Any kind of plugin, including a third-party. Today to install plugins we need to do pip install or dnf install. And in most of the cases, the name of the package to install does not match to the name of the plugins.

One idea was to squash/combine, to facilitate the plugin management (install  / uninstall / enable / disable)

**Comment by clebergnu** [comment]
Closing in favor of #4440

**Pull request closed without merging**
