### PR TITLE
[V2] Python 2.6 (RHEL6) compatibility

### PR DESCRIPTION
**Pull request by lmr**
Second version of the RHEL6 compatibility work.

### CODE REVIEW

**Comment by clebergnu** [comment]
OK, I've read all the `git log -p master..` on my machine, and it all makes sense. Let me go through each patch not on github and see what (if) comments I have.

Great work btw!

**Comment by clebergnu** [comment]
@lmr this will hopefully help with the packaging work: In a EL6 machine, I added the EPEL6 repo and lmr/Autotest COPR repo. After that, I installed the following list of packages:

`python-argparse python-unittest2 python-logutils python-importlib python-nose python-requests PyYAML pyliblzma libvirt-python pystache python-sphinx10 python-flexmock inspektor`

Of couse some of this will have to make into `BuildRequires` and not `Requires`.

**Comment by clebergnu** [comment]
One sad news: `selftests/run` does not work properly with neither `python-nose` or `python-nose1.1`.

**Comment by clebergnu** [comment]
Oh, and only now I noticed that `inspektor` is not built on EL6.

**Comment by lmr** [comment]
@clebergnu https://github.com/autotest/inspektor/pull/10 for inspektor

**Comment by lmr** [comment]
`selftests/run` was ported to run under older nose

**Comment by lmr** [comment]
See 86289e4e

**Comment by clebergnu** [comment]
@lmr wrt to nose, the thing is that `EPEL 6` ships versions (two of them) of `python-nose` that won't give `selftests/run` what it needs (`nose.selector`).

But, as I was telling you on IRC, this is only an issue if we were targeting a completely RPMfied development environment, and we're not targeting that. We're targeting a completely RPMfied user environment.

**Comment by clebergnu** [comment]
So, just to sum it: we're only short of `nose`, `sphix` and `inspektor` for a completely RPMfied EL6 development environment. With those installed via `pip`, `make check` runs great.

**Comment by lmr** [comment]
@clebergnu, now with the spec adjustments, I've been able to get a clean build of avocado in F20, F21, EL6 and EL7:

https://copr.fedoraproject.org/coprs/lmr/Autotest/build/82016/

I think we are done here, finally.

**Comment by ldoktor** [comment]
Hi Lucas, you overrode my questions without any response, nor reflects in the code. Do you have any comments about them?

**Comment by ldoktor** [comment]
Previous commits:
https://github.com/lmr/avocado/commit/ae6e57ad0e2498ef6080a735e1ec44223cfaf49f
https://github.com/lmr/avocado/commit/c71fa78bb418e4a9ea49877ab5a2302f6b548558
https://github.com/lmr/avocado/commit/6254c2e885505a81d3292b2d4ae7a7b02ffa21e6
https://github.com/lmr/avocado/commit/6f478a79d4dd8baecb01d383c4438ab907609c7e
https://github.com/lmr/avocado/commit/86289e4e75185d300958e71bd1ef9f42bc9c375b
https://github.com/lmr/avocado/commit/c9dd18401bec8b3d13939c168ca4fe0d9937d71c
https://github.com/lmr/avocado/commit/24242746b9dfd878f716b2ef74d48c3f84fc5ccf
https://github.com/lmr/avocado/commit/99a9f4544a5a4fc01413fef41c02da90fc4e2b0b
https://github.com/lmr/avocado/commit/4595cf6b117ecd00e76e1c90deab123be33f41b6
https://github.com/lmr/avocado/commit/20cd107cc91da1326e633ab2bb8eed5f87d7f044

**Comment by lmr** [comment]
@ldoktor I had no idea, sorry.

**Comment by lmr** [comment]
@ldoktor I made comments in all your comments there. Long story short, I'm making most of the changes suggested and taking them for a test.

**Comment by lmr** [comment]
Closing in favor of #489

**Pull request closed without merging**
