### PR TITLE
avocado.core.test: fix syntax

### PR DESCRIPTION
**Pull request by xutian**
this patch fix syntax issue on python2.6 

Signed-off-by: Xu Tian <xutian@redhat.com>

### CODE REVIEW

**Comment by xutian** [comment]
@ldoktor can you help to review this PR,  we have test blocked by this issue, thanks.

**Comment by apahim** [comment]
@xutian Avocado dropped python2.6 support. The last version that is guaranteed to support python2.6 is v45.0.

Btw, for the travis build, there is a PR here: https://github.com/avocado-framework/avocado-vt/pull/907.

**Comment by xutian** [comment]
@apahim thanks your comments, just see that PR. it looks we need update our CI script to checkout code at v45.0 for rhel6 host.
Thanks,
Xu

**Comment by ldoktor** [comment]
Yep, the `avocado-vt` fix was already merged and it makes Travis happy. Don't forget to freeze your downstream execution to 45.0 or 36lts...

**Pull request closed without merging**
