### PR TITLE
RPM: cleanups and Python 3 packaging prep work

### PR DESCRIPTION
**Pull request by clebergnu**
This is a collection of cleanups and prep work for the upcoming Python 3 RPM packages.

### CODE REVIEW

**Comment by clebergnu** [comment]
[Python 3: Avocado RPM packaging](https://trello.com/c/XdWoIQ1E/1268-python-3-avocado-rpm-packaging)

**Comment by wainersm** [comment]
I tried to  build the rpm but it failed with message below. It seems not related with changes on this patch since the build also fails on master branch. So just a head's up...

```
ERROR: test_basic (selftests.unit.test_utils_partition.TestPartition)
Test the basic workflow
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/avocado-20959161cd65237a32cc34c877941696e4215f51/selftests/unit/test_utils_partition.py", line 51, in test_basic
    self.disk.mkfs()
  File "/builddir/build/BUILD/avocado-20959161cd65237a32cc34c877941696e4215f51/avocado/utils/partition.py", line 198, in mkfs
    raise PartitionError(self, "Failed to mkfs", error)
PartitionError: Partition(/tmp/avocado_selftests.unit.test_utils_partitionwUPYjc/block): Failed to mkfs: Command 'yes | mkfs -t ext2  -F /tmp/avocado_selftests.unit.test_utils_partitionwUPYjc/block' failed (rc=1)
```

**Comment by clebergnu** [comment]
@wainersm can you share your environment details and how you're attempting to build the packages?

**Comment by clebergnu** [comment]
Merging according to review by @wainersm

**Pull request merged**
