### PR TITLE
nrunner: failfast: make failfast return AVOCADO_JOB_INTERRUPTED and nice message

### PR DESCRIPTION
**Pull request by beraldoleal**
It will make it consistent with the current runner returning
AVOCADO_JOB_INTERRUPTED, also this is adding a
message to the user about the failfast.

Signed-off-by: Beraldo Leal <bleal@redhat.com>

### CODE REVIEW

**Review by clebergnu — CHANGES_REQUESTED** [review]
There's one major problem introduced here: the indiscriminately writing to the "UI" log.   If you run:

```
avocado run --test-runner=nrunner --failfast --nrunner-max-parallel-tasks=1 --tap - -- /bin/true /bin/false /bin/true
```

You should *not* get the last line:

```
1..3
ok 1 /bin/true
not ok 2 /bin/false
Interrupting job (failfast).
```

The `runner` implementation avoid that by setting the failure reason to the job, and letting the human UI plugin handle that when it controls the stdout/stderr.

**Comment by beraldoleal** [comment]
> There's one major problem introduced here: the indiscriminately writing to the "UI" log. If you run:
> 
> ```
> avocado run --test-runner=nrunner --failfast --nrunner-max-parallel-tasks=1 --tap - -- /bin/true /bin/false /bin/true
> ```
> 
> You should _not_ get the last line:
> 
> ```
> 1..3
> ok 1 /bin/true
> not ok 2 /bin/false
> Interrupting job (failfast).
> ```
> 
> The `runner` implementation avoid that by setting the failure reason to the job, and letting the human UI plugin handle that when it controls the stdout/stderr.

Thanks for the hint. I wasn't sure about it. Fixed on the force-push [here](https://github.com/avocado-framework/avocado/compare/114ae9042aacad261b442b486d7823608bcc760e..e7bfa4bbf636335044852a2a67f0f94fa4831e4a)

**Comment by beraldoleal** [comment]
@clebergnu ping.

**Review by clebergnu — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
