### PR TITLE
Move nrunner standalone runners to a new runners dir

### PR DESCRIPTION
**Pull request by willianrampazzo**
With the possibility of having new runners added to the nrunner architecture, let's move the standalone runners to a specific directory, just like the spawners' structure.

Signed-off-by: Willian Rampazzo <willianr@redhat.com>

### CODE REVIEW

**Review by clebergnu — CHANGES_REQUESTED** [review]
Hi @willianrampazzo , you should also look into the `avocado.core.nrunner.Runnable.pick_runner_command()` method.  Basically, it allows Python modules to be used as runners, in addition to the `avocado-runner-$kind` scripts.  It'd need a change change as:

```diff
diff --git a/avocado/core/nrunner.py b/avocado/core/nrunner.py
index 7eee00c15..37cbc9abd 100755
--- a/avocado/core/nrunner.py
+++ b/avocado/core/nrunner.py
@@ -255,10 +255,10 @@ class Runnable:
         # Looking for the file only avoids an attempt to load the module
         # and should be a lot faster
         core_dir = os.path.dirname(os.path.abspath(__file__))
-        module_name = "nrunner_%s" % self.kind.replace('-', '_')
+        module_name = self.kind.replace('-', '_')
         module_filename = '%s.py' % module_name
-        if os.path.exists(os.path.join(core_dir, module_filename)):
-            full_module_name = 'avocado.core.%s' % module_name
+        if os.path.exists(os.path.join(core_dir, 'runners', module_filename)):
+            full_module_name = 'avocado.core.runners.%s' % module_name
             candidate_cmd = [sys.executable, '-m', full_module_name]
             if self.is_kind_supported_by_runner_command(candidate_cmd):
                 runners_registry[self.kind] = candidate_cmd
```

**Comment by willianrampazzo** [comment]
> Hi @willianrampazzo , you should also look into the `avocado.core.nrunner.Runnable.pick_runner_command()` method. Basically, it allows Python modules to be used as runners, in addition to the `avocado-runner-$kind` scripts. It'd need a change change as:
> 
> ```diff
> diff --git a/avocado/core/nrunner.py b/avocado/core/nrunner.py
> index 7eee00c15..37cbc9abd 100755
> --- a/avocado/core/nrunner.py
> +++ b/avocado/core/nrunner.py
> @@ -255,10 +255,10 @@ class Runnable:
>          # Looking for the file only avoids an attempt to load the module
>          # and should be a lot faster
>          core_dir = os.path.dirname(os.path.abspath(__file__))
> -        module_name = "nrunner_%s" % self.kind.replace('-', '_')
> +        module_name = self.kind.replace('-', '_')
>          module_filename = '%s.py' % module_name
> -        if os.path.exists(os.path.join(core_dir, module_filename)):
> -            full_module_name = 'avocado.core.%s' % module_name
> +        if os.path.exists(os.path.join(core_dir, 'runners', module_filename)):
> +            full_module_name = 'avocado.core.runners.%s' % module_name
>              candidate_cmd = [sys.executable, '-m', full_module_name]
>              if self.is_kind_supported_by_runner_command(candidate_cmd):
>                  runners_registry[self.kind] = candidate_cmd
> ```

ops, thanks!

**Comment by willianrampazzo** [comment]
@clebergnu, I added the missing changes in a force-push here.

**Review by richtja — APPROVED** [review]

**Review by beraldoleal — APPROVED** [review]
Hi @willianrampazzo, Thanks for this. This is really welcome, IMO. Much better organization.

**Review by clebergnu — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
