### PR TITLE
Test: make workdir initialization lazy

### PR DESCRIPTION
**Pull request by clebergnu**
Avocado is currently creating the workdir directory at the class
initialization, which means that it's wasted for tests that get
skipped, canceled, or simply don't use them.

To avoid the extra overhead, and possibly leave stale dirs, let's make
the creation of workdir (and the ones used as the basis of workdir)
lazy.

For SIMPLE tests, the test itself can not request the creation of
workdir lazily, so it gets created manually.

Signed-off-by: Cleber Rosa <crosa@redhat.com>

### CODE REVIEW

**Review by richtja — COMMENTED** [review]
Hi @clebergnu the code LGTM, but IIUC this change is part of legacy code and I thought that we won't be creating new features for the legacy runner, just the bug fixes. And this is not the bug fix, am I right?

**Review by ana — COMMENTED** [review]
I tested it and works fine. However, there are still empty directories created by the tests.

**Comment by clebergnu** [comment]
> Hi @clebergnu the code LGTM, but IIUC this change is part of legacy code and I thought that we won't be creating new features for the legacy runner, just the bug fixes. And this is not the bug fix, am I right?

Hi @richtja, this change is *not* part of legacy code, it's part of the `avocado.Test` class that we is needed whenever we run `avocado-instrumented` tests in the nrunner.

About it being a fix or not, it's a bit of a gray line.  This is a follow up to a report from the QEMU maintainer, about temporary directories not being cleaned up.  There's a fix in QEMU itself:

https://lists.gnu.org/archive/html/qemu-devel/2021-08/msg00461.html

But this takes care of one minor issue which is empty temporary directories on skipped tests.

**Comment by clebergnu** [comment]
> I tested it and works fine. However, there are still empty directories created by the tests.

Hi @ana, do you mean that `data` directories?  If so, I ignored those for now, because they are connected to the "output check" feature, and probably trickier to eliminate.

**Review by beraldoleal — APPROVED** [review]

**Comment by richtja** [comment]
> > Hi @clebergnu the code LGTM, but IIUC this change is part of legacy code and I thought that we won't be creating new features for the legacy runner, just the bug fixes. And this is not the bug fix, am I right?
> 
> Hi @richtja, this change is _not_ part of legacy code, it's part of the `avocado.Test` class that is needed whenever we run `avocado-instrumented` tests in the nrunner.

What I meant, is that this is not the problem of nrunner because the canceled and skipped tests won't be initialized on the nrunner. So as I see this, it  is a legacy problem. I just wanted to be sure, I won't be blocking this because of that.

**Review by richtja — APPROVED** [review]

**Review by ana — APPROVED** [review]

**Pull request merged**
