### PR TITLE
optional_plugins/html: Produce a single html page result

### PR DESCRIPTION
**Pull request by ldoktor**
Currently the results are spread into multiple files, which does not
work nicely when results are compressed and only the result.html is
uncompressed. Let's embed everything into `result.html` to make things
easier.

Signed-off-by: Lukáš Doktor <ldoktor@redhat.com>

### CODE REVIEW

**Comment by ldoktor** [comment]
[BUG: Create single HTML page results instead of multiple files (css/js/...)](https://trello.com/c/k5RWiU73/1061-bug-create-single-html-page-results-instead-of-multiple-files-css-js)

**Comment by sathnaga** [comment]
screenshot from 2017-06-21 10-47-10

**Comment by apahim** [comment]
@lmr indeed, it's not a bug in Avocado but it's a bug somewhere and it's affecting Avocado users. This PR is a workaround for it. Without that bug, this PR would not exist. This is important because if it does not qualify as a bug, then it cannot get into this version. We are in LTS-beta, when only bugfixes and documentation are allowed. As consequence, the LTS version which is about to be released would not ship this code.
Anyway, in the last sprint meeting we agreed that we should merge this code in this sprint as it's ready and it solves an issue affecting our users.

**Comment by apahim** [comment]
LGTM. Merging.

**Pull request merged**
