### PR TITLE
Remove the unused local variable 'hint_resolutions'

### PR DESCRIPTION
**Pull request by KeyLee123**
Local variable 'hint_resolutions' value is not used, and In the following if statement, this variable will be reassigned.

### CODE REVIEW

**Review by richtja — COMMENTED** [review]
Hi @KeyLee123, good catch, thank you very much. Since you are already doing this change, I think we can remove the `hint_resolutions` variable completely. What do you think?

```
@@ -261,12 +261,10 @@ def _extend_directory(path):

 def resolve(references, hint=None, ignore_missing=True, config=None):
     resolutions = []
-    hint_resolutions = []
     hint_references = {}

     if hint:
-        hint_resolutions = hint.get_resolutions()
-        hint_references = {r.reference: r for r in hint_resolutions}
+        hint_references = {r.reference: r for r in hint.get_resolutions()}

     if not references and hint_references:
         references = list(hint_references.keys())


```

**Comment by KeyLee123** [comment]
Hi @richtja, I completely agree with you, `hint_resolutions` variable can be removed completely.

**Comment by richtja** [comment]
Hi @KeyLee123, gentle ping here. Do you plan to continue with this by completely removing the `hint_resolutions` variable?

**Comment by KeyLee123** [comment]
Hi @richtja , I agree and plan to continue with this by completely removing the `hint_resolutions` variable. I will make the necessary changes and push the updates soon.
Thanks for the reminder!

**Pull request closed without merging**
