### PR TITLE
  Review command line options. [V3]

### PR DESCRIPTION
**Pull request by ruda**
Follow up of PR #488 

--

Changes:

* Rebase code from the current master (Python 2.6 stuff).

### CODE REVIEW

**Comment by lmr** [comment]
I guess the bugfix I made by introducing `--disable-paginator` would have to be rewritten by this PR, but I love your work here overall. I think that there are more options we'd need to work on, though (the virt plugin options come to mind). 

I also suggest that the subject of the commit messages are worded like:

    avocado app: Review test output options

I think that looks better on a commit list.

**Comment by ldoktor** [comment]
Btw `--disable-paginator

**Comment by lmr** [comment]
@ldoktor Yep!

**Comment by ruda** [comment]
Thanks for reviewing, I'm going to prepare V4 soon, regarding the comments that you did.

**Comment by ruda** [comment]
Closing this in favor of #497.

**Pull request closed without merging**
