### PR TITLE
Test-ID: change the format to make it play better with Windows filesystems

### PR DESCRIPTION
**Pull request by clebergnu**
This addresses the issue #2189, also according to the discussions and suggestions on https://trello.com/c/iPZihxhn/1120-serialized-test-ids-contain-the-character-invalid-in-windows.

### CODE REVIEW

**Comment by clebergnu** [comment]
[Serialized Test IDs contain the ':' character, invalid in Windows](https://trello.com/c/iPZihxhn/1120-serialized-test-ids-contain-the-character-invalid-in-windows)

**Comment by ldoktor** [comment]
Well I'd suggest first patch to modify the `string_to_safe_path` to make sure to replace all unsafe characters in case they occur and then perhaps a second commit to make test-id filesystem-friendly. First it can unveil potential issues with symlinks and second it'll work properly if users use unsafe characters in any other component.

As for the character `+` I think it's likely to be used in variant names and IIRC we excluded the separator from allowed names. Besides it's quite common to use character `@` to declare location or current conditions, wouldn't it be easier to parse? Let's mention other possibilities to see how they look like (sorted by mine preferences):

```
1-passtest.py@short
1-passtest.py`short
1-passtest.py^short
1-passtest.py!short
1-passtest.py'short
1-passtest.py"short
1-passtest.py#short
1-passtest.py%short
1-passtest.py[short
1-passtest.py$short
1-passtest.py&short
1-passtest.py(short
1-passtest.py)short
1-passtest.py*short
1-passtest.py+short
1-passtest.py,short
1-passtest.py-short
1-passtest.py.short
1-passtest.py:short
1-passtest.py=short
1-passtest.py?short
1-passtest.py\short
1-passtest.py]short
1-passtest.py_short
1-passtest.py{short
1-passtest.py|short
1-passtest.py}short
1-passtest.py~short
```

**Comment by clebergnu** [comment]
@ldoktor I can relate to `+`, because for `1-passtest.py+short", I "read it as":

"passtest.py" with the addition of special conditions (parameters) brought in by variant "short".

Now, one issue is about *this* specific case we identified.  I was not trying to address *all* possible unsafe characters.  This can be done either before or after this specific change.

**Comment by ldoktor** [comment]
OK, created card about the astring change https://trello.com/c/TJXAuAVA/1127-improve-the-astringstringtosafepath-to-work-on-windows

Now considering this as a hotfix it's fine by me, only I'd like to get @apahim's opinion about the format, because parsing of the `+` is hard for me as it's close to our `-` separator so with multiple leaves it takes me way longer to find where the test name finishes and variant name begins. When I try the same with `@` or ``` the situation is better, anyway I agree it's subjective. Some examples:

```
 (01/12) passtest.py:PassTest.test+sys-version-i386-workstation-20-3f96: PASS (0.01 s)
 (02/12) passtest.py:PassTest.test@sys-version-x86_64-workstation-20-983f: PASS (0.01 s)
 (03/12) passtest.py:PassTest.test`sys-version-i386-cloud-20-e7ee: PASS (0.01 s)
 (04/12) passtest.py:PassTest.test^sys-version-x86_64-cloud-20-9457: PASS (0.01 s)
 (05/12) passtest.py:PassTest.test!sys-version-i386-workstation-21-746e: PASS (0.01 s)
 (06/12) passtest.py:PassTest.test'sys-version-x86_64-workstation-21-453a: PASS (0.01 s)
 (07/12) passtest.py:PassTest.test"sys-version-i386-cloud-21-a56a: PASS (0.01 s)
 (08/12) passtest.py:PassTest.test#sys-version-x86_64-cloud-21-87f8: PASS (0.01 s)
...
```
(anyway I suggest putting them in terminal as font matters)

**Comment by clebergnu** [comment]
@ldoktor you certainly have a good intention here, but even if @apahim likes `@` better than `+`, we'd have two "votes" for `+`, and two "votes" for `@`.  This is one of those times that we should favor getting things done, as opposed to getting how we'd like to have things.

**Comment by apahim** [comment]
`@` leads me to think about location/host. It can be probably used in multihost testsIDs. I'd merge this PR as is.

**Comment by ldoktor** [comment]
OK, merging...

**Pull request merged**
