### PR TITLE
avocado: Refactor logging initialization [3]

### PR DESCRIPTION
**Pull request by ldoktor**
Hello guys,

this complex PR is a first step to refactor the logging. What it does is it changes the initialization of logging to by design avoid problems with --silent not ready during parser initialization.

v1: https://github.com/avocado-framework/avocado/pull/946
v2: https://github.com/avocado-framework/avocado/pull/949

Chagnes:

    v2: Renamed cryptic variable names in log (eg. appl->app_logger)
    v2: Output which streams are incorrect when incorrect streams supplied
    v2: Remove false fix for typo (excerpt is a word ...)
    v2: Squash the late python2.6 fix where it was produced
    v3: Simplifies the "scripts/avocado" fatal failure handler
    v3: Renames DEBUG env variables to "AVOCADO_LOG_..."
    v3: Fixes some docstrings
    v3: Added commit which removes "View"
    v3: The "View" commit fixes the error which prevented v2 from being applied

### CODE REVIEW

**Comment by clebergnu** [comment]
@ldoktor since I've merged the replay feature, I rebased your work on top of it (resolved the conflicts) and changed the replay code to use the new logging mechanism.

You can find that to save you some time at:

https://github.com/clebergnu/avocado/tree/logging3.5

Please review if the changes make sense.

**Comment by ldoktor** [comment]
well don't hurry it. I think it could (and should) wait for the beginning of the next sprint so we can catch all the problems before we release it in rpm... I'll rebase it on Monday, you can test it with older master...

**Comment by clebergnu** [comment]
The idea of pushing the rebase I did is that then you don't have to waste time doing the same thing. And, I have a few comments and question on this PR, so I'm not thinking about merging it straight away.

**Comment by ldoktor** [comment]
Hey guys (@adereis, @clebergnu, @apahim)

I thought about the naming issue and how about `--show` to enable logging streams and `--log` to produce files in the results dir?

As for the `early` stream log how about calling it `root`, because it is what it actually is.

There is one problem regarding the `custom` stream. If we want to let users specify custom streams by naming them in the `--log` or `--show`, we might have problems with clashes. The question is whether do we care. Currently we define `app,test,debug,remote,early,all,none` (where `early` might be renamed to `root`, so these will have a special meaning. On the other hand, users would easily enable other custom loggers to get messages from it's logger.

**Comment by clebergnu** [comment]
I do like `--show` and actually thought about it during the call, but immediately discard it because I reckoned it was too simple. **But** now I think being too simple is a good thing. Command options are free to use `--show-foo` and not cause clashes.

**Comment by lmr** [comment]
Closing in favor of #980

**Pull request closed without merging**
