### PR TITLE
travis: Remove smokechecks and nightly builds to save some time

### PR DESCRIPTION
**Pull request by beraldoleal**
Travis new credits are not much, let's save some time while GH actions is not
ready. If @ana's work on GH actions is good for merge, then this can be
discarded.

Signed-off-by: Beraldo Leal <bleal@redhat.com>

### CODE REVIEW

**Review by richtja — APPROVED** [review]

**Review by willianrampazzo — APPROVED** [review]
So, `make check` runs inside the copr build. IMHO, we could remove it from Travis and leave just the "free" offers, s390x and ppc64. Anyway, code LGTM.

**Comment by beraldoleal** [comment]
> So, `make check` runs inside the copr build. IMHO, we could remove it from Travis and leave just the "free" offers, s390x and ppc64. Anyway, code LGTM.

How many python versions are copr are running? My point here was the cross version feature that I was not sure with copr.

**Comment by willianrampazzo** [comment]
> > So, `make check` runs inside the copr build. IMHO, we could remove it from Travis and leave just the "free" offers, s390x and ppc64. Anyway, code LGTM.
> 
> How many python versions are copr are running? My point here was the cross version feature that I was not sure with copr.

That is true, it runs just one version of python.

**Comment by clebergnu** [comment]
> > > So, `make check` runs inside the copr build. IMHO, we could remove it from Travis and leave just the "free" offers, s390x and ppc64. Anyway, code LGTM.
> > 
> > 
> > How many python versions are copr are running? My point here was the cross version feature that I was not sure with copr.
> 
> That is true, it runs just one version of python.

I think @willianrampazzo has a point here, because we only run checks on **one** version of Python (3.8) on s390x and ppc64.  Packit is building on F33 and F34, which has 3.9, so it's actually a version bump, but I don't see a problem.

**Review by clebergnu — COMMENTED** [review]
LGTM, thanks!

**Pull request merged**
