### PR TITLE
Passwordless ssh

### PR DESCRIPTION
**Pull request by smruti77**
This patch enables the access to remote machine through
login and password details given in the yaml file
and enables running of commands on peer machine.

Signed-off-by: bismurti bidhibrata pattajoshi <bbidhibr@in.ibm.com>

### CODE REVIEW

**Comment by clebergnu** [comment]
Hi @smruti77 , have you looked at `avocado.utils.ssh`? You can use it like this:

```python
import avocado.utils.ssh
with avocado.utils.ssh.Session(('hostname', 22), ('username', '/path/to/key')) as session:
...     print(session.cmd('command').stdout_text)

I'd like to understand if your use case, and why it can't be done with that existing module.  Thanks!

**Comment by PraveenPenguin** [comment]
@smruti77 can you please reply , i think `avocado.utils.ssh` serve your purpose

**Comment by smruti77** [comment]
> @smruti77 ping

@clebergnu hi, actually i am trying to use that ssh.py. if it is working fine then i will let you know.

**Comment by smruti77** [comment]
@clebergnu for credentials, is there a way to provide `username and password` ? or is `id_rsa.pub` the preferred way ?

**Comment by smruti77** [comment]
@clebergnu can we have any avocado utils file to handle pxssh things.its not possible to generate key everytime so and can you please give suggusetion for one issue which i was created based up on this i will working on that next.

**Comment by smruti77** [comment]
@clebergnu ping

**Comment by clebergnu** [comment]
@smruti77 I understand your point, specially the fact that you cannot inject a key on some images.  I've created a Trello about it:

https://trello.com/c/uetpIgML/1517-avocadoutilssh-implement-password-based-auth

**Comment by smruti77** [comment]
> @smruti77 I understand your point, specially the fact that you cannot inject a key on some images. I've created a Trello about it:
> 
> https://trello.com/c/uetpIgML/1517-avocadoutilssh-implement-password-based-auth
@clebergnu can i start work on this ?

**Comment by clebergnu** [comment]
> > @smruti77 I understand your point, specially the fact that you cannot inject a key on some images. I've created a Trello about it:
> > https://trello.com/c/uetpIgML/1517-avocadoutilssh-implement-password-based-auth
> > @clebergnu can i start work on this ?

Of course!

**Comment by clebergnu** [comment]
@smruti77 I also needed to work on this, please see #3299 .  I'm closing this one.

**Pull request closed without merging**
