### PR TITLE
RPM Packages: add requirements for versioned sub-packages

### PR DESCRIPTION
**Pull request by clebergnu**
And a number of other RPM package fixes.

### CODE REVIEW

**Comment by clebergnu** [comment]
[[BUG] v60.0 - dnf install is not requiring stevedore](https://trello.com/c/TRHACAcr/1294-bug-v600-dnf-install-is-not-requiring-stevedore)

**Comment by clebergnu** [comment]
A tip to reviewers:

``` 
make MOCK_CONFIG=fedora-27-x86_64 rpm-release
```

On this branch will build the `60.0` tag tarball with the SPEC file changes, resulting in 60.0-2 packages.  `MOCK_CONFIG` can (and should) be changed to `fedora-26-x86_64` and `epel-7-x86_64` to make sure those changes work on the other supported distros.

**Comment by apahim** [comment]
```
$ rpm -qpR python2-avocado-60.0-2.20180409git70abdd81.fc27.noarch.rpm
gdb
gdb-gdbserver
procps-ng
pyliblzma
python(abi) = 2.7
python-avocado-common = 60.0
python2
python2-requests
python2-setuptools
python2-six
python2-stevedore
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PartialHardlinkSets) <= 4.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
```

**Comment by apahim** [comment]
```
$ rpm -qpR python3-avocado-60.0-2.20180409git70abdd81.fc27.noarch.rpm
gdb
gdb-gdbserver
procps-ng
pyliblzma
python(abi) = 3.6
python-avocado-common = 60.0
python3
python3-requests
python3-setuptools
python3-six
python3-stevedore
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PartialHardlinkSets) <= 4.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
```

**Pull request merged**
