### PR TITLE
plugins.list: Adding a machine-readable output for 'avocado list' (v2)

### LINKED ISSUE #4538: Add machine-readeable output to `avocado list`
So that scripts could more easily use its output to implement complex workflows. Examples of workflows can be found at https://github.com/avocado-framework/avocado/issues/4430

Currently `avocado list` prints to stdout as human-readable text. If you use options like `--verbose` it will print detailed information about the tests, however, this isn't easily consumed as one would need to implement a parser. Thus, an ouput on json format would be very welcomed.

### PR DESCRIPTION
**Pull request by beraldoleal**
Introducing the --json option to the 'list' command.
Fixes #4538.

Signed-off-by: Beraldo Leal bleal@redhat.com

### Changes from v1:
 - renamed --save-to-json to --json
 - Removed "append" mode (now using "write" mode);
 - Tags are saved as dict instead of string;
 - Lazy format of tags (only at display() method)

### CODE REVIEW

**Review by willianrampazzo — APPROVED** [review]
LGTM, I'll leave testing for @wainersm :D

**Review by richtja — APPROVED** [review]

**Comment by beraldoleal** [comment]
@wainersm ;)

**Comment by clebergnu** [comment]
I'm getting the following crash:

```
$ avocado list --resolver --json /tmp/json -- /bin/true 
exec-test /bin/true
Avocado crashed unexpectedly: LoaderProxy.discover has to be called before LoaderProxy.get_type_label_mapping
You can find details in /home/cleber/avocado/data/crashes/avocado-traceback-2021-05-11_13:51:28-criwysuc.log


$ cat /home/cleber/avocado/data/crashes/avocado-traceback-2021-05-11_13:51:28-criwysuc.log
Avocado crashed:
Traceback (most recent call last):
  File "/home/cleber/.local/bin/avocado", line 11, in <module>
    load_entry_point('avocado-framework', 'console_scripts', 'avocado')()
  File "/home/cleber/src/avocado/avocado/avocado/core/main.py", line 76, in main
    return app.run()
  File "/home/cleber/src/avocado/avocado/avocado/core/app.py", line 112, in run
    return method(self.parser.config)
  File "/home/cleber/src/avocado/avocado/avocado/plugins/list.py", line 284, in run
    self._save_to_json(matrix, write_to_json_file, verbose)
  File "/home/cleber/src/avocado/avocado/avocado/plugins/list.py", line 176, in _save_to_json
    type_label_mapping = loader.loader.get_type_label_mapping()
  File "/home/cleber/src/avocado/avocado/avocado/core/loader.py", line 200, in get_type_label_mapping
    raise RuntimeError("LoaderProxy.discover has to be called before "
RuntimeError: LoaderProxy.discover has to be called before LoaderProxy.get_type_label_mapping
```

Also, I was expecting to be able to do:

```
$ avocado list --json - -- /bin/true
```

Just as I'm able to do:

```
avocado run --json - -- /bin/true
```

**Review by clebergnu — APPROVED** [review]
LGTM, thanks!

**Review by wainersm — APPROVED** [review]
Hi people! I've tested this PR, it works! Thanks @beraldoleal !

**Pull request merged**
