### PR TITLE
[V10] Test discovery and load (Phase II)

### PR DESCRIPTION
**Pull request by lmr**
This is a follow up to #363.

This has the full functionality, including the list functionality and fixes to the remote and vm plugins.

Changes from V9:
* Properly handle broken symlinks (pointed by @adereis)
* Consolidated commits

Changes from V8:
* Error on missing and non tests, introducing input validation to the list of tests (suggested by @adereis)
* Updated documentation (suggested by @adereis)
* Removed (once again) the concept of MissingTest (suggested by @adereis)

Changes from V7:

* Fixed a misleading commit message, per @ldoktor's comments.
* Simplified the selective showing of tests per @ldoktor's comments.

Changes from V6:
 
* Rebased the code
* Improved the 'list' subcommand to take a list of paths, and overhauled the output of that command.
* Fixed remote and VM plugins

Changes from V4 and V5:

 * Rebase the code
 * Consolidated commits
 * Now when users provide paths to explicit files, then it analyzes them. If a dir is provided, non tests are not listed/their execution is attempted. Fixing comments by @ldoktor.

Changes from V3:

Fixed problems found by @ldoktor, mainly:

* Remove remaining references to MissingTests inside the code
* Fix crash when tests have bugs that prevent their modules from being imported
* Append base test directory to `sys.path` to ensure dependent modules in the same dir are importable

Changes from V2:

* Completely remove the concept of MissingTests. It wasn't very useful to begin with.
* Break the need for test classes to be named after the module names.
* Mass rename the current avocado test class names
* Update docs to reflect the new *status quo*

Changes from V1:

* avocado.loader: Locate SimpleTests using the full path.
* avocado.job: Set different messages when the number of tests found is zero [No tests found within the  specified path(s)] or when the number of variants is zero [The number of test variants is zero].
* avocado.loader: Skip directory if we don't have permission to walk. Also skip tests that are not tests, so Avocado stops crashing when walking in a directory, looking for tests.
* avocado.utils.process: Use shell glob style when matching wrap scripts.
test_lister plugin: Sort output in alphabetic order.

### CODE REVIEW

**Comment by lmr** [comment]
@ldoktor, Well, I *think* now all demands have been satisfied, except the fact that the code is not optimized for resource consumption. I guess we could work on that on a later stage.

**Comment by ldoktor** [comment]
Hi Lucas, I'm sorry to say, but there is a little inconsistency. Broken symlink on directory url should probably be ignored, similarly to not_a_test. Or did I miss something?

**Comment by ldoktor** [comment]
OK I made some tweaks, @lmr please have a look:

```diff
From b84d2510488b6126b7914fb9c7563a4550301fc1 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Luk=C3=A1=C5=A1=20Doktor?= <ldoktor@redhat.com>
Date: Fri, 30 Jan 2015 11:05:44 +0100
Subject: [PATCH 1/2] avocado.loader: Interrupt inspect after first
 avocado.test.Test match
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

We support only single avocado.test.Test per module so it's safe
to interrupt test inspecting with first positive match.

Signed-off-by: Lukáš Doktor <ldoktor@redhat.com>
---
 avocado/loader.py | 1 +
 1 file changed, 1 insertion(+)

diff --git a/avocado/loader.py b/avocado/loader.py
index a1eef41..727c1c7 100644
--- a/avocado/loader.py
+++ b/avocado/loader.py
@@ -99,6 +99,7 @@ class TestLoader(object):
                 if inspect.isclass(obj):
                     if issubclass(obj, test.Test):
                         test_class = obj
+                        break
             if test_class is not None:
                 # Module is importable and does have an avocado test class
                 # inside, let's proceed.
-- 
1.9.3

From 8bca037d71b582d22f501b5614afb87cbb42a732 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Luk=C3=A1=C5=A1=20Doktor?= <ldoktor@redhat.com>
Date: Fri, 30 Jan 2015 11:15:59 +0100
Subject: [PATCH 2/2] avocado.loader: Don't add failures when exploring
 directory
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

When user provides full invalid path, we want to fail. When user
provides path to a directory, we have to ignore not only missing and
not_a_test's but also broken symlinks.

Signed-off-by: Lukáš Doktor <ldoktor@redhat.com>
---
 avocado/loader.py | 6 +-----
 1 file changed, 1 insertion(+), 5 deletions(-)

diff --git a/avocado/loader.py b/avocado/loader.py
index 727c1c7..fd17000 100644
--- a/avocado/loader.py
+++ b/avocado/loader.py
@@ -212,11 +212,7 @@ class TestLoader(object):
                          '__main__.py')
         params_list = []
 
-        def onerror(exception):
-            params_list.append({'id': exception.filename,
-                                'omit_non_tests': False})
-
-        for dirpath, dirnames, filenames in os.walk(url, onerror=onerror):
+        for dirpath, dirnames, filenames in os.walk(url):
             for dir_name in dirnames:
                 if dir_name.startswith('.'):
                     dirnames.pop(dirnames.index(dir_name))
-- 
1.9.3
```

**Comment by adereis** [comment]
The symlink handling is broken, but now in a different way:

    $ ./scripts/avocado run ~/tmp/
    Cannot access '/home/ademar/tmp/mux': Broken symlink
    $ ls -l ~/tmp
    total 12
    lrwxrwxrwx  1 ademar ademar   10 Jan 30 09:07 asfasfasf -> /asfasfasf
    drwxr-xr-x  2 ademar ademar 4096 Jan 30 09:08 bla/
    ----------  1 ademar ademar    0 Jan 29 12:57 bla.txt
    ---x------  1 ademar ademar    0 Jan 29 12:58 ble.sh*
    d--x------  4 ademar ademar 4096 Set 10 16:24 mux/
    drwxr-xr-x. 2 ademar ademar 4096 Nov  6 19:05 foobar/

Besides, I understand your motivation here, but this should not be in the list when running in non-verbose mode (I think the information is welcome in verbose mode):

    $ ./scripts/avocado list ~/tmp/
    BROKEN_SYMLINK /home/ademar/tmp/asfasfasf 
    ACCESS_DENIED  /home/ademar/tmp/ble.sh    
    ACCESS_DENIED  /home/ademar/tmp/bla.txt   
    ACCESS_DENIED  /home/ademar/tmp/mux    

(the same way as "NOT A TEST" files are only shown in the list when running in verbose mode)

**Comment by adereis** [comment]
Regarding my previous item about including BROKEN_SYMLINK and ACCESS_DENIED files to the output of avocado list, @lmr convinced me that it's worth including them in non-verbose mode. The idea is that avocado list will, by default, show detected tests and anything that's potentially broken or unexpected. "list --verbose" will include additional info, such as headers, a summary and files which are plain ignored (NOT_A_TEST).

**Comment by lmr** [comment]
Closing this in favor of #379.

**Pull request closed without merging**
