### PR TITLE
utils: fixes root logger

### PR DESCRIPTION
**Pull request by beraldoleal**
As discussed before, we are using a new approach where each module is logging in its own namespace.

### CODE REVIEW

**Review by richtja — CHANGES_REQUESTED** [review]
Hi @beraldoleal, nice work thanks, the code LGTM I just found another occurrence in [process utils](https://github.com/avocado-framework/avocado/blob/master/avocado/utils/process.py#L297)

**Comment by richtja** [comment]
I am not sure if it's related to this PR because this is just about utils, but during the review I found out that we are manipulating with root logger also in [avocado-instrumented runner](https://github.com/avocado-framework/avocado/blob/master/avocado/core/test.py#L607)

**Comment by beraldoleal** [comment]
> Hi @beraldoleal, nice work thanks, the code LGTM I just found another occurrence in [process utils](https://github.com/avocado-framework/avocado/blob/master/avocado/utils/process.py#L297)

Yes, I left process for a second round because I need to discuss with you a few things there.

**Comment by beraldoleal** [comment]
> I am not sure if it's related to this PR because this is just about utils, but during the review I found out that we are manipulating with root logger also in [avocado-instrumented runner](https://github.com/avocado-framework/avocado/blob/master/avocado/core/test.py#L607)

I don't think is related to this pr, but for sure we need to fix this as well.

**Comment by beraldoleal** [comment]
Thank you @richtja. Closing this and creating a new PR (not a v2 since I'm using a different approach).

**Pull request closed without merging**
