### PR TITLE
–store-logging-stream for non-avocado loggers fix

### PR DESCRIPTION
**Pull request by richtja**
This will enable non-avocado logging streams in `debug.log` by usage of
`–store-logging-stream` option.

Reference: #5290
Signed-off-by: Jan Richter <jarichte@redhat.com>

### CODE REVIEW

**Comment by richtja** [comment]
Hi @luckyh, can you please check if this solves your problem in [#3369](https://github.com/avocado-framework/avocado-vt/issues/3369)

**Comment by luckyh** [comment]
Hi @richtja, it works as expected, thank you for the quick fix!

_job.log_
```
...
2022-03-28 03:35:11,211 avocado.test INFO | Command line: /usr/local/bin/avocado run --store-logging-stream=aexpect --journal --vt-config /root/avocado/data/avocado-vt/backends/qemu/cfg/tests-example.cfg --force-job-id bc1d270232e711b41b20a9e5a724167263b9cf82 --disable-tap-job-result --vt-short-names-when-config --vt-qemu-bin /usr/libexec/qemu-kvm --vt-qemu-dst-bin /usr/libexec/qemu-kvm
...
```
_debug.log_
```
...
[stdlog] 2022-03-28 03:35:42,125 aexpect.client DEBUG| Sending command: ls
[stdlog] 2022-03-28 03:35:42,228 aexpect.client DEBUG| Sending command: echo $?
...
```

**Review by beraldoleal — APPROVED** [review]
Thanks.

**Review by ana — APPROVED** [review]

**Comment by ana** [comment]
@richtja I don't know why, but this PR is missing the packit tests. Could you please force-push an update to see if they run?

**Comment by YongxueHong** [comment]
Hi, @richtja 
Thank you for fixing this issue so quick, it is really helpful for us to debug automation bugs.
And I tried to apply it through running the case `virtio_fs_share_data` https://github.com/autotest/tp-qemu/blob/master/qemu/tests/virtio_fs_share_data.py.
Checked the debug.log then I didn't find the aexpect log info.
The details of log:

job.log:
```
2022-03-28 23:17:18,021 avocado.test INFO | Command line: /home/yhong/kar/workspace/bin/avocado run --store-logging-stream=aexpect --test-runner=runner --journal --vt-config /home/yhong/kar/workspace/root/avocado/data/avocado-vt/backends/qemu/cfg/tests-example.cfg ....
```

The debug log of https://github.com/autotest/tp-qemu/blob/ca0a84d8c9eba81a737ca5d64adbfb62163b7e70/qemu/tests/virtio_fs_share_data.py#L281 :
```
23:17:58 INFO | Context: Create a destination directory /mnt/myfs inside guest.
23:17:58 INFO | Context: Mount virtiofs target myfs to /mnt/myfs inside guest.
23:17:58 INFO | The guest file in shared dir is /mnt/myfs/test_file
23:17:58 INFO | Context: Creating file under /mnt/myfs inside guest.
23:18:39 INFO | 3f054d29cbb0f4ee3e3cd5f633a731d6
23:18:39 INFO | Running 'md5sum /home/yhong/kar/workspace/root/avocado/data/avocado-vt/virtio_fs_test/test_file'
23:18:43 DEBUG| [stdout] 3f054d29cbb0f4ee3e3cd5f633a731d6  /home/yhong/kar/workspace/root/avocado/data/avocado-vt/virtio_fs_test/test_file
```
The session log of https://github.com/autotest/tp-qemu/blob/ca0a84d8c9eba81a737ca5d64adbfb62163b7e70/qemu/tests/virtio_fs_share_data.py#L281 :
```
2022-03-28 23:17:58: [root@localhost ~]#
2022-03-28 23:18:33: 2048+0 records in
2022-03-28 23:18:33: 2048+0 records out
2022-03-28 23:18:33: 2147483648 bytes (2.1 GB, 2.0 GiB) copied, 34.4927 s, 62.3 MB/s
2022-03-28 23:18:33: [root@localhost ~]#
2022-03-28 23:18:33: 0
2022-03-28 23:18:33: [root@localhost ~]#
2022-03-28 23:18:39: 3f054d29cbb0f4ee3e3cd5f633a731d6  /mnt/myfs/test_file
```
Maybe I missed some external information to verify this patch,
Would you like to help me figure out?
Thanks. 
CC @luckyh

**Comment by luckyh** [comment]
> job.log:
> 
> ```
> 2022-03-28 23:17:18,021 avocado.test INFO | Command line: /home/yhong/kar/workspace/bin/avocado run --store-logging-stream=aexpect --test-runner=runner --journal --vt-config /home/yhong/kar/workspace/root/avocado/data/avocado-vt/backends/qemu/cfg/tests-example.cfg ....
> ```
> ...
>  Maybe I missed some external information to verify this patch,
Would you like to help me figure out?

@YongxueHong looks like this only works properly with `nrunner` (see [here](https://github.com/avocado-framework/avocado/blob/master/avocado/core/runners/avocado_instrumented.py#L73)), while you were using the legacy runner which was specified by the option `--test-runner=runner` in the given command line.

@richtja do you think if it is better to fix the issue for the legacy runner as well at the current stage? thanks!

**Comment by YongxueHong** [comment]
> > job.log:
> > ```
> > 2022-03-28 23:17:18,021 avocado.test INFO | Command line: /home/yhong/kar/workspace/bin/avocado run --store-logging-stream=aexpect --test-runner=runner --journal --vt-config /home/yhong/kar/workspace/root/avocado/data/avocado-vt/backends/qemu/cfg/tests-example.cfg ....
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ...
> > Maybe I missed some external information to verify this patch,
> > Would you like to help me figure out?
> 
> @YongxueHong looks like this only works properly with `nrunner` (see [here](https://github.com/avocado-framework/avocado/blob/master/avocado/core/runners/avocado_instrumented.py#L73)), while you were using the legacy runner which was specified by the option `--test-runner=runner` in the given command line.
> 

Hi @luckyh 
Thanks for your explanation.

> @richtja do you think if it is better to fix the issue for the legacy runner as well at the current stage? thanks!

**Comment by richtja** [comment]
Hi @luckyh and @YongxueHong, yes, this change is only for `nrunner`. Also, the legacy runner has been deprecated after the 92lts version. Right now, we are working on removing the legacy code and the --test-runner=runner option will be removed soon. For more information, see #5138 and #5246. So to answer your question, at this stage, we won't be fixing the legacy runner on master branch.

**Comment by luckyh** [comment]
> Hi @luckyh and @YongxueHong, yes, this change is only for `nrunner`. Also, the legacy runner has been deprecated after the 92lts version. Right now, we are working on removing the legacy code and the --test-runner=runner option will be removed soon. For more information, see #5138 and #5246. So to answer your question, at this stage, we won't be fixing the legacy runner on master branch.

ok, that makes sense to me, thanks!

**Comment by ana** [comment]
rpm-build:centos-stream-8-x86_64  fails because a problem with pack it.

**Pull request merged**
