### PR TITLE
README: add build and quality badges

### PR DESCRIPTION
**Pull request by clebergnu**
Besides Copr, which provides a build status badge, let's also
(proudly) display the ratings and issues that lgtm gives us.

Signed-off-by: Cleber Rosa <crosa@redhat.com>

### CODE REVIEW

**Comment by clebergnu** [comment]
> The build status inside readme is different from the status inside Copr. Now inside readme, the status is "succeeded", but the last build on Copr is failing. It's built of [ebce18f](https://github.com/avocado-framework/avocado/commit/ebce18f2a0f035b8baa0a35d4ab22a3578a7b08f). I didn't find out why the status isn't updated.
> 

This link:

https://copr.fedorainfracloud.org/coprs/g/avocado/avocado-latest/package/python-avocado/status_image/last_build.png

Gives you the right (failed) status.  I can relate to you finding a "pass", but I think that's a caching issue.  Try to reload that link and it'll show a "failed" status.  Now, that was a very good thing, because the failure is due to the drop in Python 2, and the attempt to build EPEL 7 packages on Copr.  So, I'm adjusting the Copr configuration for that.

> And also I was thinking if the end of readme is the best place for Build and Quality Status. I think that this information should be more visible. I would put it somewhere at the beginning, for example before chapter Installing Avocado.

That was a hard call indeed.  I did that thinking of the users, in the sense that they shouldn't be bothered by what we should be bothered.  They usually come looking for instructions, not a "project status dashboard" IMO.

**Comment by clebergnu** [comment]
BTW, I've added an item here:

https://trello.com/c/l3F40qn6/1403-use-copr-for-continuous-rpm-builds

Because it'd be helpful to have a Copr repo for LTS as well.

**Comment by richtja** [comment]
> This link:
> 
> https://copr.fedorainfracloud.org/coprs/g/avocado/avocado-latest/package/python-avocado/status_image/last_build.png
> 
> Gives you the right (failed) status. I can relate to you finding a "pass", but I think that's a caching issue. Try to reload that link and it'll show a "failed" status. 

The link works fine, but I have a problem with image inside README.rst because there is old status. I think that GitHub somehow downloaded the image and loads it from it's cache servers, not from copr. So when copr changes [last_build.png ](https://copr.fedorainfracloud.org/coprs/g/avocado/avocado-latest/package/python-avocado/status_image/last_build.png) the readme won't be changed and there still be the old status.
I found out that the same problem is at [Latest Development RPM Packages from COPR](https://github.com/avocado-framework/avocado#latest-development-rpm-packages-from-copr)

**Comment by clebergnu** [comment]
> > This link:
> > https://copr.fedorainfracloud.org/coprs/g/avocado/avocado-latest/package/python-avocado/status_image/last_build.png
> > Gives you the right (failed) status. I can relate to you finding a "pass", but I think that's a caching issue. Try to reload that link and it'll show a "failed" status.
> 
> The link works fine, but I have a problem with image inside README.rst because there is old status. I think that GitHub somehow downloaded the image and loads it from it's cache servers, not from copr. So when copr changes [last_build.png ](https://copr.fedorainfracloud.org/coprs/g/avocado/avocado-latest/package/python-avocado/status_image/last_build.png) the readme won't be changed and there still be the old status.
> I found out that the same problem is at [Latest Development RPM Packages from COPR](https://github.com/avocado-framework/avocado#latest-development-rpm-packages-from-copr)

That was my point, it's all a caching issue.  If you hit a "CTRL+Shift+R" (in chromium) you should see the updated image, reflecting the current status.

**Comment by clebergnu** [comment]
BTW, I've looked for a restructuredText option to set "don't cache" on the generated HTML, but there's no such thing.

**Comment by clebergnu** [comment]
@richtja sure! And thanks for the review!

**Pull request merged**
