### PR TITLE
Add new APIs to avocado to accomodate avocado-vt's needs

### PR DESCRIPTION
**Pull request by lmr**
In the process of merging virt-test into avocado-vt (see https://github.com/avocado-framework/avocado-vt/pull/30), we mostly dropped virt-test's autotest API calls, replacing them with equivalent avocado API calls. Of course, avocado didn't have some of the expected APIs, and that's the purpose of this Pull Request: to add the missing ones.

Update: There's no more `exceptions.context` API added here. We decided it was best to find a better way to do that in avocado, so virt-test's got its own implementation of the context APIs.

### CODE REVIEW

**Comment by lmr** [comment]
@ldoktor, If you could take a look at this PR, please. I'm in the process of finishing up the gigantic PR to avocado-vt, but the avocado side should be good to go.

**Comment by ldoktor** [comment]
@lmr OK I finished. I have not executed all functions, only reviewed the changes from autotest version. It looks good although I'm concern about the GPL. I'm not sure what must be done, but at least a pointer to the origin should be mentioned there.

Additionally I'm worried about the `unittests`. There are lots of untested functions added into the avocado `utils` and we should support and maintain that. So far we kept pretty high unittest coverage and we should do the same here.

**Comment by lmr** [comment]
@ldoktor, now that I've managed to make RPM install functional in https://github.com/avocado-framework/avocado-vt/issues/30, I'll go back to this one to address your comments. Hold on, I'll have updates soon.

**Comment by lmr** [comment]
Closing in favor of #725

**Pull request closed without merging**
