### PR TITLE
NextRunner: Remove the ambiguity of "status" and introduce the "result" keyword

### PR DESCRIPTION
**Pull request by dkarpelevich**
`status` keyword in `avocado-runner-tap` is being used for both: runner execution status and test result status.
After fix `avocado-runner-tap` output will be:
```
$ avocado-runner-tap runnable-run -k "tap" -u "/bin/sh" -a "/tmp/foo.sh"
{'status': 'running', 'timestamp': 1585773826.9089062}
{'status': 'running', 'timestamp': 1585773828.913483}
{'status': 'finished', 'result': 'pass', 'returncode': 0, 'timestamp': 1585773828.9147718}
```
`make check` passed: [job.log](https://cpaste.org/?ce009b9759f250cf#5JjRo1QKvpT7NBBbQdQpg5KaEaqusyHfdNmHFJVjsWKA)

One more test `test_runner_tap_error` added:
 `Task complete (pass): 143-selftests.unit.test_nrunner.Runner.test_runner_tap_error`

Issue: https://github.com/avocado-framework/avocado/issues/3547

### CODE REVIEW

**Comment by clebergnu** [comment]
@dkarpelevich thanks for this contribution and initiative. The "protocol" between a runner and the "status server" is still pretty much loose and we can change it and improve at will. But, while we discuss and settle on the meaning of each field, we should do it for all known runners. Also, this moment while we discuss these fields names and values, is the perfect timing to document it.

So in short, this is a welcome change, and I think it makes sense to be more explicit about what is status, and what is the overall outcome, that is, the result.  But, we need to take into account other runners: `ExecRunner`, `ExecTestRunner`, `PythonUnittestRunner`, `AvocadoInstrumentedRunner`, etc, and make sure the idea applies well to them all.

**Comment by dkarpelevich** [comment]
@clebergnu, I agree that it runners outputs should be the same. According to [Tip](https://avocado-framework.readthedocs.io/en/latest/future/core/nrunner.html#runner-output) it shouldn't be done in `BaseRunner` class.
I prepared a patch with similar updates for `ExecTestRunner`, `PythonUnittestRunner`, `NoOpRunner` and `RobotRunner`. I think `ExecRunner` and `AvocadoInstrumentedTestRunner` don't have clear final (finished) state now. So I decided not touching it. 
For example this is an output from `AvocadoInstrumentedTestRunner`:
```
{'logdir': '/tmp/tmp1h64drlc/test-results/1-Assert.test_assert_raises', 'logfile': '/tmp/tmp1h64drlc/test-results/1-Assert.test_assert_raises/debug.log', 'status': 'pass', 'running': False, 'paused': False, 'time_elapsed': 0.00043320655822753906, 'time_end': 1585853381.467525, 'fail_reason': None, 'fail_class': None, 'traceback': None, 'timeout': None, 'whiteboard': '', 'phase': 'FINISHED', 'class_name': 'Assert', 'job_logdir': None, 'job_unique_id': 
'cd34dded9864aee64bb35f4e9bf628bb9d4fca77', 'params': []}
```

**Comment by beraldoleal** [comment]
@dkarpelevich Thanks for this.

Looks like we need a rebase here. There are commits from master.

**Comment by dkarpelevich** [comment]
> @dkarpelevich Thanks for this.
> 
> Looks like we need a rebase here. There are commits from master.

@beraldoleal Thank you. Travis-ci passed after rebase

**Comment by beraldoleal** [comment]
@dkarpelevich something is still wrong, please look for the "commits" and "File changed" tabs here.

**Comment by dkarpelevich** [comment]
@beraldoleal  To avoid confusion I've preapred another PR with the same changes from branch created from master https://github.com/avocado-framework/avocado/pull/3692.Packit tests will fail because I can't trigger it.

**Comment by willianrampazzo** [comment]
Closing in favor of #3692.

**Pull request closed without merging**
